[WIP]Allow background video playback
brave/brave-ios pull request #1068
Opened 2019-04-24 01:00 UTC by danishjafri88

- [x] Remove video on tab close
- [x] Keep record of videos and their state
- [x] Play on background
- [ ] Handle Dynamic Video add
- [ ] Multiple videos?
- [ ] Control videos -> mute/etc
- [x] Stop videos from playing in background -> on background pauseAll -> Improve
- [ ] Optimize

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [ ] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New files have MPL-2.0 license header.

## Test Plan:

### Screenshots:

## Reviewer Checklist:

- [ ] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [ ] Issues are assigned to at least one epic.
- [ ] Issues include necessary QA labels:
  - [ ] `QA/(Yes|No)`
  - [ ] `release-notes/(include|exclude)`
  - [ ] `bug` / `enhancement`
- [ ] Necessary security reviews have taken place.
- [ ] Adequate test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable)

2019-04-25 09:31 UTC, iccub requested changes
Left few comments, going to run the branch now and look for functional bugs

2019-04-25 09:31 UTC, iccub commented on Client/Frontend/Browser/BackgroundMediaPlayback.swift
> +            print(response)
replace prints with `XCLogger`

2019-04-25 09:31 UTC, iccub commented on Client/Frontend/Browser/BackgroundMediaPlayback.swift
> +import MediaPlayer
Most of those imports aren't needed in this file right? Could be removed

2019-04-25 09:31 UTC, iccub commented on Client/Frontend/Browser/UserScriptManager.swift
> +        var alteredSource: String = source
`: String` can be removed

2019-04-25 09:31 UTC, iccub commented on Client/Frontend/UserContent/UserScripts/BackgroundPlay.js
> +//WIP Mute functions
Is it needed anymore?

2019-04-25 09:31 UTC, iccub commented on Client/Application/AppDelegate.swift
> +           print(error)
replace with `log.error()`

2019-04-25 09:31 UTC, iccub commented on Client.xcodeproj/project.pbxproj
> +				59C730FD225EC48200995E16 /* AVFoundation.framework in Frameworks */,
This can be removed, we already `import AVFoundation` in `AppDelegate`

2019-04-25 10:11 UTC, iccub commented on Client/Frontend/Browser/Tab.swift
> +        webView?.evaluateJavaScript("pauseAll()", completionHandler: nil)
Make sure `evaluateJavascript` happens on main thread

My debugger caught this

<img width="1552" alt="Zrzut ekranu 2019-04-25 o 12 09 15" src="https://user-images.githubusercontent.com/6950387/56728523-3fb0ab00-6753-11e9-8309-da891a3901ba.png">

2019-04-25 10:12 UTC, iccub commented on Client/Frontend/Browser/Tab.swift
> +        webView?.evaluateJavaScript("didEnterBackground()", completionHandler: nil)
Same as above, make sure `evaluateJavascript` happens on main thread

2019-04-25 11:16 UTC, danishjafri88 commented on Client/Frontend/UserContent/UserScripts/BackgroundPlay.js
> +//WIP Mute functions
Yeah they are needed for v2

2019-04-25 21:05 UTC, iccub commented on Client/Frontend/Browser/BackgroundMediaPlayback.swift
> +            debugPrint(response)
Do you need it for debugging? 
Despite `debug` in name, this will also get printed in release builds.

2019-11-19 15:50 UTC, iccub commented
Will be fixed in https://github.com/brave/brave-ios/pull/1306

2019-11-19 15:50 UTC, closed without merging