Shields string update
brave/brave-ios pull request #1190
Opened 2019-06-25 22:07 UTC by rossmoody

Closes https://github.com/brave/brave-ios/issues/765: Update shields off description

I saw this and reached out to Karen about updating the string to match desktop. Instead of dynamically changing the title, I added the snippet about shields being down.

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [ ] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New files have MPL-2.0 license header.

## Test Plan:

1. Turn shields off.
2. Make sure descriptions matches `Brave Shields are currently down for this site. You\'re browsing without any privacy and security protections.`

### Screenshots:

## Reviewer Checklist:

- [ ] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [ ] Issues are assigned to at least one epic.
- [ ] Issues include necessary QA labels:
  - [ ] `QA/(Yes|No)`
  - [ ] `release-notes/(include|exclude)`
  - [ ] `bug` / `enhancement`
- [ ] Necessary security reviews have taken place.
- [ ] Adequate test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable)

2019-06-28 21:08 UTC, jhreis requested changes

2019-06-28 21:08 UTC, jhreis commented on BraveShared/BraveStrings.swift
> +    public static let Shields_Overview = NSLocalizedString("ShieldsOverview", tableName: "BraveShared", bundle: Bundle.braveShared, value: "Brave Shields are currently down for this site. You\'re bro
Escaping is not needed here for the `'`, please remove.

2019-07-02 13:32 UTC, jhreis commented
@tomlowenthal can you please review this copy change. 

Two main changes:
- Completely removing copy:
> Note: Some sites may require scripts to work properly so this shield is turned off by default.

- Modifying
> Site Shields allow you to control when ads and trackers are blocked for each site that you visit. If you prefer to see ads on a specific site, you can enable them here.
to 
> Brave Shields are currently down for this site. You're browsing without any privacy and security protections.

2019-07-02 13:32 UTC, jhreis commented
@rossmoody one of the issues with the new copy is that this is also shown on the new tab page, which isn't technically insecure, and there is now way to toggle shields on for new tab page.

2019-07-02 17:59 UTC, rossmoody commented
Ah, I see. Well, I'll let @karenkliu or @tomlowenthal chime in on correct direction, I was just trying to help out but it seems like it might require more functionality updates. Could always consider shutting this one down in favor of more specific spec.

2019-07-02 19:23 UTC, karenkliu commented
If we're aiming for desktop parity, then Shields should not be interactive on the new tab page or system preferences pages (it would be in a disabled state).

<img width="37" alt="Screen Shot 2019-07-02 at 12 22 36 PM" src="https://user-images.githubusercontent.com/2388823/60540468-1ae13280-9cc4-11e9-9d17-38eb95233dc9.png">

2019-07-15 22:32 UTC, rossmoody commented
Gonna close this one. Needs a different approach to what is going on here.

2019-07-15 22:32 UTC, closed without merging