Fix #1141: Added locale decimal formatting to Sheild Stats
brave/brave-ios pull request #1201
Opened 2019-07-01 11:49 UTC by andydonzelli

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [ ] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Test Plan:

If you don't have 1000+ blocks, you might want to test the function by temporarily using a constant at line 74 instead of the real block count. Eg: `adsStatView.stat = toLocaleString(num: 12345)`.

### Screenshots:

Old                                      |  New
:-------------------------:|:-------------------------:
![Simulator Screen Shot - iPhone Xs - 2019-07-01 at 09 52 12](https://user-images.githubusercontent.com/6990701/60434154-ce83ed00-9c06-11e9-8a34-72f054459385.png)  | ![Simulator Screen Shot - iPhone Xs - 2019-07-01 at 09 48 27](https://user-images.githubusercontent.com/6990701/60434155-cf1c8380-9c06-11e9-9e21-5698cf0e5e19.png)

## Reviewer Checklist:

- [ ] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [ ] Issues are assigned to at least one epic.
- [ ] Issues include necessary QA labels:
  - [ ] `QA/(Yes|No)`
  - [ ] `release-notes/(include|exclude)`
  - [ ] `bug` / `enhancement`
- [ ] Necessary security reviews have taken place.
- [ ] Adequate test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable)

2019-07-02 13:27 UTC, jhreis requested changes
Really useful PR and clean too. Just a couple of comments, but nothing serious.

2019-07-02 13:27 UTC, jhreis commented on Client/Frontend/Browser/HomePanel/BraveShieldStatsView.swift
> +    private func toLocaleString(num: Int) -> String {
Let's create a `BinaryInteger` (or even just an `Int`) extension here can even be private inside of this file.

```
extension BinaryInteger {
  func localeDisplayString() {}
}```

2019-07-02 13:27 UTC, jhreis commented on Client/Frontend/Browser/HomePanel/BraveShieldStatsView.swift
> +        return numberFormatter.string(from: num as NSNumber) ?? ""
To be more explicit, let's return `nil`, and then in usage locations we can fallback to `"0"` (making the return type `String?` here).

2019-08-04 12:14 UTC, andydonzelli commented
I applied the requested changes with a force-push in order to squash the changes... But it seems like this didn't trigger a new request to review those changes. Let me know how to proceed.

2019-08-04 13:30 UTC, iccub commented
I will review it next week, thanks for bumping this PR :)

2019-08-05 18:33 UTC, iccub requested changes

2019-08-05 18:33 UTC, iccub commented on Client/Frontend/Browser/HomePanel/BraveShieldStatsView.swift
> +extension BinaryInteger {
Make this `fileprivate`

2019-08-05 18:33 UTC, iccub commented on Client/Frontend/Browser/HomePanel/BraveShieldStatsView.swift
> +    func toLocaleString() -> String? {
I'm thinking of better name for this, maybe `decimalFormattedString`?
And change it to computed property `var decimalFormattedString: String? { code }`

2019-08-05 18:33 UTC, iccub commented on Client/Frontend/Browser/HomePanel/BraveShieldStatsView.swift
> +        return numberFormatter.string(from: self as! NSNumber)
Unwrap this and return nil if it fails

2019-08-05 18:33 UTC, iccub commented on Client/Frontend/Browser/HomePanel/BraveShieldStatsView.swift
> +extension BinaryInteger {
Can't `extension Int be used?`

2019-08-05 18:33 UTC, iccub commented on Client/Frontend/Browser/HomePanel/BraveShieldStatsView.swift
> +        return numberFormatter.string(from: self as! NSNumber)
Also with `extension Int` we can cast it to `NSNumber` without optional

2019-08-08 01:02 UTC, jhreis commented
@andydonzelli force push is great, but we can also squash before merging, so don't worry too much about keeping your commits clean, since you already have at least one nice one. Thanks!

2019-08-08 01:02 UTC, jhreis commented
@andydonzelli force push is great, but we can also squash before merging, so don't worry too much about keeping your commits clean, since you already have at least one nice one. Thanks!

2019-08-21 17:02 UTC, jhreis commented
@andydonzelli This PR is really close, if you could wrap up the comments, we'll get it merged in.

2019-08-21 19:49 UTC, andydonzelli commented
Two tests *crashed* (not failed). I can't work out the details of why they crashed, but I suspect it's because the version of the repo from which I branched from is so old. Maybe the tests expect some code that just isn't there yet?

I can try merging my branch with a later commit of the base repo and see if that fixes things?

2019-08-21 19:53 UTC, iccub commented
Perhaps need to rebase to latest development branch. We have updated the project to XCode11/Swift5 recently

Thanks for taking your time on this

2019-08-26 12:07 UTC, andydonzelli commented
Should be good to go.

2019-08-26 15:21 UTC, iccub commented
@andydonzelli looks like development branch is really outdated and a lot of commits were included.
Can you fix this by:
1. Update your local `development` branch to be equal with ours
2. Run rebase pointing to your development branch

This will make all those additional commits go away

2019-08-26 16:58 UTC, andydonzelli commented
Is this what you mean? I can squash too if that's easier.

2019-08-26 17:48 UTC, iccub commented
thanks :) I will do a final review later today

2019-08-27 10:06 UTC, iccub approved these changes

2019-08-27 10:08 UTC, iccub commented
Thank you for for contribution Andy!

@jhreis please re-review and merge

2019-08-31 01:30 UTC, jhreis approved these changes

2019-08-31 01:30 UTC, merged