Fixed Passcode UI not resetting when going to foreground
brave/brave-ios pull request #1202
Opened 2019-07-02 13:57 UTC by Brandon-T

Issue:
1. Have passcode set.
2. Restart application.
3. Authenticate with passcode.
4. Go to private browsing.
5. Search for anything.. Stackoverflow for example.
6. Minimize app to background
7. It prompts to authenticate but authentication is already filled in from the first time we authenticated..

Solution:
Fixed Passcode UI not resetting when going to foreground by calling "resetCode" when successfully entered.

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [ ] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New files have MPL-2.0 license header.

## Test Plan:

### Screenshots:

## Reviewer Checklist:

- [ ] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [ ] Issues are assigned to at least one epic.
- [ ] Issues include necessary QA labels:
  - [ ] `QA/(Yes|No)`
  - [ ] `release-notes/(include|exclude)`
  - [ ] `bug` / `enhancement`
- [ ] Necessary security reviews have taken place.
- [ ] Adequate test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable)

2019-07-10 15:13 UTC, kylehickinson requested changes

2019-07-10 15:13 UTC, kylehickinson commented on Client/Frontend/AuthenticationManager/PasscodeEntryViewController.swift
> +            passcodePane.codeInputView.resetCode()
Since we also call this in the else flow just below, lets move both to be after the if-block so its executed regardless

2019-07-20 15:48 UTC, kylehickinson approved these changes

2019-07-23 17:52 UTC, danishjafri88 approved these changes

2019-07-24 22:23 UTC, merged