Conform to NSSecureCoding instead due to security vulnerability on #0…
brave/brave-ios pull request #1325
Opened 2019-08-02 19:54 UTC by Brandon-T

Conform to NSSecureCoding instead due to security vulnerability on #003831-DataTheorem.

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [ ] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New files have MPL-2.0 license header.

## Test Plan:

### Screenshots:

## Reviewer Checklist:

- [ ] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [ ] Issues are assigned to at least one epic.
- [ ] Issues include necessary QA labels:
  - [ ] `QA/(Yes|No)`
  - [ ] `release-notes/(include|exclude)`
  - [ ] `bug` / `enhancement`
- [ ] Necessary security reviews have taken place.
- [ ] Adequate test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable)

2019-08-05 18:42 UTC, iccub commented
Does it need security review?

2019-08-06 10:48 UTC, iccub commented on Push/PushRegistration.swift
> +public class PushRegistration: NSObject, NSSecureCoding {
we don't sure this `Push` framework, it's Firefoxes, but doesn't hurt to change it

2019-08-06 14:27 UTC, iccub approved these changes

2019-08-06 14:35 UTC, iccub commented
related ticket https://github.com/brave/brave-ios/issues/1330

2019-08-06 14:41 UTC, kylehickinson requested changes
If we intend to truly use `NSSecureCoding` we should be updating our decoder methods to use `decodeObject(of:key:)` instead of casting (edit: when needed*)

2019-08-08 01:00 UTC, jhreis commented
This will require sec review since datatheorem ticket.

2019-08-09 18:21 UTC, kylehickinson approved these changes
Probably needs a double check to make sure each still work, but otherwise seems fine.

One random thing: why cast like `as String?` instead of `as? String`?

2019-08-09 19:28 UTC, jumde commented
@Brandon-T - Please update the test plan to include some OpenSearch/Analytics/SessionData/KeychainAuth workflows to make sure the updated code is not causing any regressions.

I think add a test/lint check to make sure NSCode is not used in future would be great but, I'm not sure if its possible with the current test ecosystem. Thoughts @jhreis

2019-08-09 19:28 UTC, jumde approved these changes

2019-08-09 19:32 UTC, jumde commented
May be worth an PR against `SwiftLint` for https://github.com/brave/brave-ios/pull/1325#issuecomment-520036808

2019-09-26 15:36 UTC, merged