Fix #1078: Add npm and node version to README
brave/brave-ios pull request #1351
Opened 2019-08-08 19:44 UTC by iccub

We had few people complaining about node version incompatibility, would be good to add it to readme. As for now, node version 12 works well

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Test Plan:

### Screenshots:

## Reviewer Checklist:

- [ ] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [ ] Issues are assigned to at least one epic.
- [ ] Issues include necessary QA labels:
  - [ ] `QA/(Yes|No)`
  - [ ] `release-notes/(include|exclude)`
  - [ ] `bug` / `enhancement`
- [ ] Necessary security reviews have taken place.
- [ ] Adequate test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable)

2019-08-08 19:45 UTC, iccub commented
I canceled CI builds as this is only a readme update

2019-08-08 23:30 UTC, jhreis requested changes

2019-08-08 23:30 UTC, jhreis commented on README.md
> +2. Make sure `npm` is installed, `node` version 12 is recommended
Should be `1.`, markdown will automatically handle numbering for us.

2019-08-09 19:04 UTC, jhreis approved these changes

2019-08-09 19:04 UTC, merged