Fix #1340: Reader mode websites can't be shared/added to Bookmarks
brave/brave-ios pull request #1372
Opened 2019-08-10 10:34 UTC by quangDecember

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [ ] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Test Plan:

### Screenshots:

## Reviewer Checklist:

- [ ] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [ ] Issues are assigned to at least one epic.
- [ ] Issues include necessary QA labels:
  - [ ] `QA/(Yes|No)`
  - [ ] `release-notes/(include|exclude)`
  - [ ] `bug` / `enhancement`
- [ ] Necessary security reviews have taken place.
- [ ] Adequate test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable)

2019-08-12 10:31 UTC, iccub requested changes
Can you add the same menu button logic for `Share` action?

From what I see only `add bookmark` button was changed, and we want both add and share action to be available

2019-08-12 10:31 UTC, iccub commented on Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift
> +        let mode: BookmarkEditMode = {
Extract only `url` from this. `BookmarkEditMode.addBookmark(title: title` always stays the same for both conditions so we only need to set a correct url string

can be done as simply as 
```
var bookmarkUrl = url.absoluteString
if url.isReaderModeURL, let decodedURL = url.decodeReaderModeURL { bookmarkUrl = decodedURL.absoluteString }
```

2019-08-12 15:43 UTC, quangDecember commented
> Can you add the same menu button logic for `Share` action?
> 
> From what I see only `add bookmark` button was changed, and we want both add and share action to be available

I already checked it before submit the PR: iOS already handled the Reader mode URL

2019-08-12 15:50 UTC, iccub commented
@quangDecember you are right, just verified it, thanks :) so the one small code change and your PR is ready to be merged

2019-08-12 16:09 UTC, iccub approved these changes
Looks nice, thank you for your first contributions :) will merge after CI passes

2019-08-13 22:31 UTC, merged

2019-08-13 22:31 UTC, jhreis commented
Very nice! Thank a bunch! This should be included in the 1.12 release!