Fix #1359: Updating U2f/WebAuthn modals to include site host
brave/brave-ios pull request #1392
Opened 2019-08-13 23:00 UTC by jumde

Fix #1359 

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [ ] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New files have MPL-2.0 license header.

## Test Plan:

### Screenshots:

![Screen Shot 2019-08-13 at 3 59 12 PM](https://user-images.githubusercontent.com/1903815/62983178-530b8300-bde3-11e9-8343-c91814dc87b1.png)

![Screen Shot 2019-08-13 at 3 37 16 PM](https://user-images.githubusercontent.com/1903815/62983157-3f601c80-bde3-11e9-829f-d3d50d9b9bcd.png)

![Screen Shot 2019-08-13 at 3 41 12 PM](https://user-images.githubusercontent.com/1903815/62983154-3c652c00-bde3-11e9-965c-e32c9f21dccb.png)

## Reviewer Checklist:

- [ ] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [ ] Issues are assigned to at least one epic.
- [ ] Issues include necessary QA labels:
  - [ ] `QA/(Yes|No)`
  - [ ] `release-notes/(include|exclude)`
  - [ ] `bug` / `enhancement`
- [ ] Necessary security reviews have taken place.
- [ ] Adequate test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable)

2019-08-13 23:33 UTC, karenkliu requested changes
Hi @jumde, thanks for your update. Please see my design feedback below (some minor revisions requested):

![design QA 1](https://user-images.githubusercontent.com/2388823/62984341-a8499380-bde7-11e9-8312-073b866ab259.png)
![design QA 2](https://user-images.githubusercontent.com/2388823/62984342-a8499380-bde7-11e9-943b-48a56b378d28.png)
![design QA 3](https://user-images.githubusercontent.com/2388823/62985312-97028600-bdeb-11e9-8c83-26c5ee881acb.png)

2019-08-14 09:29 UTC, iccub commented
@karenkliu thanks for the feedback.

Regarding all these small font/spacing changes, we use a general purpose framework for these yubikey screens, which mean if we change for example spacing between title and image, it will affect all popups in our application.

Same for changing font weight, although this is easier to be modified only for these screens.

For the PIN verification image, could you provide us an image with extra empty bottom padding? So we will have to change nothing on our side, just replace the image

ccing @jamesmudgett as he's worked on the general purpose popup implementation on iOS

2019-08-14 17:39 UTC, karenkliu commented
Hi @iccub - here is the updated image for the PIN screen. Thanks for making these updates!
[PNG.zip](https://github.com/brave/brave-ios/files/3502570/PNG.zip)

2019-08-14 19:18 UTC, karenkliu approved these changes

2019-08-14 22:11 UTC, iccub approved these changes

2019-08-20 18:10 UTC, merged