Tabs bar
brave/brave-ios pull request #14
Opened 2018-03-21 16:56 UTC by iccub

Removed existing firefox implementation of tabs on iPads and copied tabs from 1.0.

2018-03-29 15:31 UTC, iccub commented
Added ability to move tabs in the tabs tray.

2018-04-20 19:07 UTC, jhreis requested changes

2018-04-20 19:07 UTC, jhreis commented on Client/Frontend/BraveUX.swift
> +struct BraveUX {
What about just naming this `UX`?

2018-04-20 19:07 UTC, jhreis commented on Client/Frontend/Browser/TabManager.swift
> +        return UIApplication.isInPrivateMode ? privateTabs.index(of: selectedTab) : normalTabs.index(of: selectedTab)
This should be able to just use:
`return displayedTabsForCurrentPrivateMode.index(of: selectedTab)`

Since that variable will automatically give us the correct `[Tab]`

2018-04-20 19:07 UTC, jhreis commented on Client/Frontend/Browser/TabScrollController.swift
> +        return (scrollDirection == .down && tabsBar.view.isHidden == false) ? BraveUX.TabsBar.height : 0
`isHidden` here is not an optional, right? So can just use `!tabsBar.view.isHidden`?

2018-04-20 19:07 UTC, jhreis commented on Client/Frontend/Browser/TabTrayController.swift
> +        if url != nil, !(url?.isLocal ?? true) {
We should unwrap `url` here, much cleaner:

`if let url = url, !url.isLocal`

2018-04-20 19:07 UTC, jhreis commented on Client/Frontend/Browser/TabTrayController.swift
> +        let dragItem = UIDragItem(itemProvider: itemProvider)
Rather than having the `?? NSItemProvider()` above, let's put it here instead:

`let dragItem = UIDragItem(itemProvider: itemProvider ?? .init())`

2018-04-20 19:07 UTC, jhreis commented on Client/Frontend/Browser/TabsBar/TabBarCell.swift
> +            make.height.equalTo(self)
Let's be consistent here. Above we combine `top.bottom`, here `left` and `height` are separated.

2018-04-20 19:07 UTC, jhreis commented on Client/Frontend/Browser/TabsBar/TabBarCell.swift
> +            make.height.equalTo(self)
Ditto.

2018-04-20 19:07 UTC, jhreis commented on Client/Frontend/Browser/TabsBar/TabBarCell.swift
> +            closeButton.tintColor = UIApplication.isInPrivateMode ? UIColor.white : UIColor.black
We may need to revisit using `isInPrivateMode` to set styles, we should be creating style classes for this instead. But we should probably talk a bit more about this.

2018-04-20 19:07 UTC, jhreis commented on Client/Frontend/Browser/TabsBar/TabsBarViewController.swift
> +    private let leftOverflowIndicator = CAGradientLayer()
Move these on top of the lazy vars

2018-04-20 19:07 UTC, jhreis commented on Client/Frontend/Browser/TabsBar/TabsBarViewController.swift
> +    weak var tabManager: TabManager?
Can we make this private and take it in via the `init`?

2018-04-20 19:07 UTC, jhreis commented on Client/Frontend/Browser/TabsBar/TabsBarViewController.swift
> +        guard let tabsToUpdate = UIApplication.isInPrivateMode ? tabManager?.privateTabs : tabManager?.normalTabs else {
Can just use `displayedTabsForCurrentPrivateMode` instead, right?

2018-04-20 19:07 UTC, jhreis commented on Client/Frontend/Browser/TabsBar/TabsBarViewController.swift
> +        if let selectedTab = tabManager?.selectedTab, let tabManager = tabManager {
Unwrap `tabManager` first, as you use that for the `selectedTab`

2018-04-20 19:07 UTC, jhreis commented on Client/Frontend/Browser/TabsBar/TabsBarViewController.swift
> +            collectionView.updateInteractiveMovementTargetPosition(gesture.location(in: gesture.view!))
Remove force unwrapping here.

2018-04-20 19:07 UTC, jhreis commented on Client/Frontend/Browser/TabsBar/TabsBarViewController.swift
> +        case UIGestureRecognizerState.began:
Should be able to just use `.began`, `.ended`, etc...

2018-04-20 19:07 UTC, jhreis commented on Client/Frontend/Browser/TabsBar/TabsBarViewController.swift
> +        return overflow > 0 ? overflow : 0
`return max(overflow, 0)` is cleaner

2018-04-20 19:07 UTC, jhreis commented on Client/Frontend/Browser/TabsBar/TabsBarViewController.swift
> +        if offset < startFade {
Can remove this entire if/else block
`leftOverflowIndicator.opacity = min(1, offset / startFade)`
No divide issues here as `startFade` is a constant.

Would need to read docs, but pretty sure it is totally fine to set `opacity` > `1` too, so just setting it to `offset / startFade` may work fine.

2018-04-20 19:07 UTC, jhreis commented on Client/Frontend/Browser/TabsBar/TabsBarViewController.swift
> +        if offsetFromRight < CGFloat(startFade) {
Same as above, can remove this if/else

2018-04-20 19:07 UTC, jhreis commented on Client/Frontend/Browser/TabsBar/TabsBarViewController.swift
> +            return CGSize(width: view.frame.width, height: view.frame.height)
We can just `return view.frame.size`

2018-04-20 19:07 UTC, jhreis commented on Client/Frontend/Browser/TabsBar/TabsBarViewController.swift
> +            let maxWidth = (collectionView.frame.width - newTabButtonWidth) / CGFloat(tabList.count())
Just want to verify that `tabList` cannot be empty at this point, right? If it can, this will throw a divide by 0 error.

2018-04-20 19:07 UTC, jhreis commented on Client/Frontend/Browser/TabsBar/TabsBarViewController.swift
> +            guard let strongSelf = self, let tabManager = self?.tabManager, let previousIndex = self?.tabList.index(of: tab) else { return }
After unwrapping `self`, we should use that in the other unwrappings. Also, probably just cleaner to do:

`guard let `self` = self, let ...`, rather than giving it a new name. Makes it harder to explicitly use the incorrect one.

2018-04-20 19:07 UTC, jhreis commented on Shared/WeakList.swift
> +    open func at(_ index: Int) -> T? {
Thoughts about using Swift subscript here? Would use like:

```
let list = WeakList<String> // fill with data
let secondItem = list[1]
```

See [docs](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Subscripts.html).

2018-04-23 12:51 UTC, iccub commented on Client/Frontend/BraveUX.swift
> +struct BraveUX {
There is also `UIConstants` class already, I could merge it together.

2018-04-23 13:13 UTC, iccub commented on Client/Frontend/Browser/TabsBar/TabBarCell.swift
> +            make.height.equalTo(self)
Edge constraints(`top|bottom|left|right`) and `width|height` values are separate concepts, personally, I would not combine them.

2018-04-23 13:48 UTC, iccub commented on Client/Frontend/Browser/TabsBar/TabsBarViewController.swift
> +            guard let strongSelf = self, let tabManager = self?.tabManager, let previousIndex = self?.tabList.index(of: tab) else { return }
I took `strongSelf` convention from https://github.com/raywenderlich/swift-style-guide#extending-object-lifetime. We can decide whether we want to adopt this style over 'self'

2018-04-23 14:43 UTC, iccub commented on Shared/WeakList.swift
> +    open func at(_ index: Int) -> T? {
For some reason it throws `Type 'WeakList<Tab>' has no subscript members`, but the same code works fine in swift playgrounds. Looks like it doesn't work with swift 3.3

2018-04-23 16:40 UTC, jhreis commented on Shared/WeakList.swift
> +    open func at(_ index: Int) -> T? {
Did you create a subscript? You will need to implement the functions yourself, or is that what you are referring to?

2018-04-23 16:59 UTC, jhreis commented on Client/Frontend/Browser/TabManager.swift
> +        tabs.insert(tabs.remove(at: visibleFromIndex), at: visibleToIndex)
This should be moved to the model, _eventually_. Given that we are swapping out our database, may not make sense to do now, but definitely model logic.

2018-04-23 16:59 UTC, jhreis commented on Client/Frontend/Browser/TabTrayController.swift
> +        guard isDragging, let destinationIndexPath = coordinator.destinationIndexPath, let dragItem = coordinator.items.first?.dragItem, let tab = dragItem.localObject as? Tab, let sourceIndex = tabs
Add some line breaks 😄

2018-04-23 16:59 UTC, jhreis commented on Client/Frontend/Browser/TabTrayController.swift
> +        if !isDragging, tabs.index(of: tab) == nil {
Since no unwrappings here I think using `&&` is probably more clear.

2018-04-23 16:59 UTC, jhreis commented on Client/Frontend/Browser/TabTrayController.swift
> +        guard let localDragSession = session.localDragSession, let item = localDragSession.items.first, let tab = item.localObject as? Tab else {
Line breaks may be nice here too.

2018-04-23 16:59 UTC, jhreis commented on Client/Frontend/Browser/TabsBar/TabBarCell.swift
> +            make.height.equalTo(self)
Gotcha, I think that makes sense. Let's remember this for future PRs.

2018-04-23 17:28 UTC, iccub commented on Shared/WeakList.swift
> +    open func at(_ index: Int) -> T? {
Nvm needed to add `open` to it as WeakList is in `Shared` module 🤷‍♂️

2018-06-13 13:05 UTC, iccub commented
Closing in favor of https://github.com/brave/brave-ios/pull/50

2018-06-13 13:05 UTC, closed without merging