Fixed #1397 by creating TabMO when opening popups.
brave/brave-ios pull request #1401
Opened 2019-08-15 19:27 UTC by danishjafri88

Fixes #1397 (Only in normal mode. TabMO will still not be created in private mode.)
TabMO was not created for popups. Hence when relaunching the app, the popups were not restored.

STR: Same as in the ticket #1397 

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [ ] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New files have MPL-2.0 license header.

## Test Plan:

### Screenshots:

## Reviewer Checklist:

- [ ] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [ ] Issues are assigned to at least one epic.
- [ ] Issues include necessary QA labels:
  - [ ] `QA/(Yes|No)`
  - [ ] `release-notes/(include|exclude)`
  - [ ] `bug` / `enhancement`
- [ ] Necessary security reviews have taken place.
- [ ] Adequate test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable)

2019-08-15 19:35 UTC, Brandon-T approved these changes

2019-08-16 09:56 UTC, iccub approved these changes

2019-08-27 01:45 UTC, jhreis requested changes

2019-08-27 01:45 UTC, jhreis commented on Client/Frontend/Browser/TabManager.swift
> +        if parentTab.isPrivate {
This works, but is not a great solution, as it is just copy and pasting code. We should look at abstracting this, potentially, why not place inside Tab init?

2020-02-07 16:42 UTC, closed without merging