Fix #1429: Correct App Group id for Beta/TestFlight builds.
brave/brave-ios pull request #1430
Opened 2019-08-24 11:51 UTC by iccub

## Summary of Changes
1. We fix the app group id for beta builds
2. If it fails we will save profile folder to `Library/Application Support`

This pull request fixes issue #<number>

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/internal/issues/new?assignees=&labels=security%2C+security-reviews&template=security-review.md&title=iOS:%20Security+Review+for) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2019-08-26 18:49 UTC, jhreis commented on Shared/AppInfo.swift
> +            bundleIdentifier = "com.brave.ios.BrowserBeta.unique"
Can we change the app group identifier? I'm guessing this was used (probably by me), due to the group id being taken already.

2019-08-26 18:54 UTC, iccub commented on Shared/AppInfo.swift
> +            bundleIdentifier = "com.brave.ios.BrowserBeta.unique"
Yes it should be possible

2019-08-26 23:24 UTC, iccub commented
I fixed the app group, now it is the same as our beta build id.

2019-08-27 01:46 UTC, jhreis approved these changes

2019-08-27 01:47 UTC, jhreis requested changes
Let's actually add a unit test to check if any files are created in document directory at launch. Basically:
- launch application
- wait 5-10 seconds
- verify documents directory is completely empty

2019-08-27 09:14 UTC, iccub commented
Added the test as separate commit, don't squash please :)

2019-08-31 00:23 UTC, jhreis approved these changes

2019-08-31 00:24 UTC, merged