Adblock rust integration for pre iOS 13 release
brave/brave-ios pull request #1441
Opened 2019-08-28 12:32 UTC by iccub

## Summary of Changes

This pull request fixes issue #<number>

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/internal/issues/new?assignees=&labels=security%2C+security-reviews&template=security-review.md&title=iOS:%20Security+Review+for) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2019-08-28 13:10 UTC, iccub commented
don't merge unless your name starts with a `J`

2019-08-28 13:33 UTC, srirambv commented
Added https://github.com/brave/brave-ios/issues/1442 for 1.11.4. Please link the issue for auto-closing

2019-08-28 15:19 UTC, jhreis requested changes
1. We removed Client/WebFilters/ShieldStats/Adblock/ABPFilterParserData.dat
Don't we still need to ship a .dat file though? 

2. Given that we are changing location of files, does this temporarily impact adblocking while new rules are being compiled (for new / existing users) or does it not, since old rules are already pre-compiled?

2019-08-28 15:19 UTC, jhreis commented on Client/WebFilters/AdblockResourceDownloader.swift
> +    static let endpoint = "https://adblock-data.s3.brave.com/iOS13"
Isn't this supposed to be `/ios/iOS13`? or is it literally just `/iOS13`? (I'm assuming this works)

2019-08-28 15:19 UTC, jhreis commented on Client/Application/Migration.swift
> +        if !Preferences.Migration.documentsDirectoryCleanupCompleted.value {
I'm a bit scared to handle this migration in this release, but might be nice to just knock them both out. 

Code looks pretty small and isolated, so not too worried, but still making a note in case we should rethink this.

2019-08-28 15:19 UTC, jhreis commented on Client/WebFilters/AdblockResourcesMappings.swift
> +    func resourceName(for fileType: FileType) -> String {
Do we need to change this file? We never manipulate `resourceId`, so early returns should be fine, no?

2019-08-28 15:27 UTC, iccub commented on Client/WebFilters/AdblockResourceDownloader.swift
> +    static let endpoint = "https://adblock-data.s3.brave.com/iOS13"
it's `iOS13` only, `ios/iOS13` doesn't work

2019-08-28 15:28 UTC, iccub commented on Client/Application/Migration.swift
> +        if !Preferences.Migration.documentsDirectoryCleanupCompleted.value {
We need to remove `abp-data` folder anyway(or containing files), we can do that isolated, and leave full documents directory cleanup for later

2019-08-28 15:28 UTC, kylehickinson commented on Client/WebFilters/AdblockResourceDownloader.swift
> +    static let endpoint = "https://adblock-data.s3.brave.com/iOS13"
Confirmed in AWS console, folder is iOS13

2019-08-28 15:30 UTC, kylehickinson commented on Client/WebFilters/AdblockResourceDownloader.swift
> +    static let endpoint = "https://adblock-data.s3.brave.com/iOS13"
One thing to wonder though, is that folder temporary? This means older versions will never get updates to their lists

2019-08-28 15:31 UTC, iccub commented on Client/WebFilters/AdblockResourceDownloader.swift
> +    static let endpoint = "https://adblock-data.s3.brave.com/iOS13"
yeah we either need to manually update files in the old endpoint or move the new files to the old enpoint

2019-08-29 19:35 UTC, jhreis approved these changes

2019-08-29 21:53 UTC, jumde approved these changes

2019-08-29 21:54 UTC, jumde commented
lgtm

2019-08-30 00:44 UTC, merged