Fixes: brave/brave-rewards-ios#195 by resetting the verified state on panel fetch mismatch data
brave/brave-ios pull request #1495
Opened 2019-09-06 10:00 UTC by danishjafri88

Fixes: brave/brave-rewards-ios#195 by resetting the verified state on panel fetch mismatch data

## Summary of Changes

This pull request fixes issue #<number>

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/internal/issues/new?assignees=&labels=security%2C+security-reviews&template=security-review.md&title=iOS:%20Security+Review+for) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2019-09-06 14:18 UTC, kylehickinson requested changes

2019-09-06 14:18 UTC, kylehickinson commented on Client/Frontend/Browser/BrowserViewController.swift
> +                self?.resetRewardsButtonVerifiedState()
I don't think this solves the underlying issue, which is that when new tabs are being shown the `fetchedPanelPublisher` observer method is reporting the old tab as the fetched publisher. This is possibly a bug in brave-core side of things (`onTabRetrieved`/reporting methods in BATBraveLedger.mm)

Steps to see this: 
1. Breakpoint on line 233 (guard statement)
2. Open a tab, go to amazon.com (will break showing tabId == selected tab)
3. Open a new tab, breaks again but the tabId being shown is still amazon.com's tab, and should be the new tab

2019-09-11 13:49 UTC, kylehickinson reviewed
Does this PR not require the changes made in brave-core?

2019-09-11 14:06 UTC, danishjafri88 commented
> Does this PR not require the changes made in brave-core?

The core pr makes sure no callback is done on unselected tabs/invalid urls
This one removes the verified mark on new tab(homepage or any other local url)
They are independent of each other

2019-09-11 14:07 UTC, kylehickinson commented
@danishjafri88 Yes I get that, but are both required to actually close the ticket as fixed?

2019-09-11 14:07 UTC, danishjafri88 commented
Yup

2019-09-11 14:09 UTC, kylehickinson commented
Okay, so then we'll want to update the `brave-rewards-ios` library while checked into the ios-pre-v3-fork branch (`./scripts/build_in_core.sh --skip-update ~/git/brave/brave-browser`), push those, and then update the dependency in brave-ios (`carthage update brave-rewards-ios --platform iOS --cache-builds`)  and include the `Cartfile.resolved` update in this PR

2019-09-11 14:12 UTC, danishjafri88 commented
> Okay, so then we'll want to update the `brave-rewards-ios` library while checked into the ios-pre-v3-fork branch (`./scripts/build_in_core.sh --skip-update ~/git/brave/brave-browser`), push those, and then update the dependency in brave-ios (`carthage update brave-rewards-ios --platform iOS --cache-builds`) and include the `Cartfile.resolved` update in this PR

Yes, FYI brave-browser should point to `56f8f74fe222e928a552c45fa2b6a754e51ab88d `

2019-09-11 14:13 UTC, kylehickinson commented
Thats fine, in brave-rewards-ios you'll end up with a README.md update that shows that brave-browser is pointing at said SHA and brave-core is pointing to `f2290c419634ea058a5d6230644ec77d19182522`

2019-09-11 17:08 UTC, kylehickinson approved these changes

2019-09-11 17:08 UTC, merged