Ref #1376: Regression with creating store and old location on 1st launch
brave/brave-ios pull request #1586
Opened 2019-09-27 11:36 UTC by iccub

## Summary of Changes

This pull request fixes issue #<number>

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/internal/issues/new?assignees=&labels=security%2C+security-reviews&template=security-review.md&title=iOS:%20Security+Review+for) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

2019-09-27 11:37 UTC, iccub commented on Data/models/DataController.swift
> -    override init() {
This initalizer was called before migration was fully completed, and on first launch it was using the old documents directory. After removing it all should be working fine.

This was done to fix intermittent bug with data tests, but so far these tests are not failing, I will keep an eye on it

2019-09-27 13:14 UTC, danishjafri88 requested changes

2019-09-27 13:14 UTC, danishjafri88 commented on Data/models/DataController.swift
> -        storeSetup()
This function `storeSetup `. is only used here. We can remove it. perhaps?

2019-10-01 22:04 UTC, jhreis approved these changes

2019-10-01 22:07 UTC, danishjafri88 approved these changes

2019-10-01 22:16 UTC, merged