Ref #1499: Add link preview to long press context.
brave/brave-ios pull request #1625
Opened 2019-10-10 17:00 UTC by iccub

## Summary of Changes

This pull request fixes issue #<number>

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

<img width="544" alt="Zrzut ekranu 2019-10-10 o 18 56 27" src="https://user-images.githubusercontent.com/6950387/66590012-1c0ddf80-eb90-11e9-8667-194e628f0d2e.png">

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

2019-10-10 17:57 UTC, kylehickinson requested changes
Also, Safari provides a way to disable these previews, we may want to give the same option to users

2019-10-10 17:57 UTC, kylehickinson commented on Client/Frontend/Browser/BrowserViewController.swift
> +            return SFSafariViewController(url: url)
Is it possible to make our own preview provider that uses BVC in some way (so shields are loaded in and such)

2019-10-10 17:57 UTC, kylehickinson commented
Sorry that review meant to be `comment`, not `request changes`

2019-10-10 18:26 UTC, iccub commented on Client/Frontend/Browser/BrowserViewController.swift
> +            return SFSafariViewController(url: url)
UIContextMenuContentPreviewProvider accepts any `UIViewController` so we could try to add some custom view with content blocker lists

2019-10-10 18:26 UTC, iccub commented
I think I should add a preference to hide preview links, similar to what Safari does at the moment

2019-10-11 12:54 UTC, iccub commented
Added content blocking to the link preview and an option to hide link previews

<img width="544" alt="Zrzut ekranu 2019-10-11 o 14 53 41" src="https://user-images.githubusercontent.com/6950387/66652836-f38cf080-ec36-11e9-8deb-1d04d83cd65b.png">
<img width="544" alt="Zrzut ekranu 2019-10-11 o 14 53 29" src="https://user-images.githubusercontent.com/6950387/66652837-f38cf080-ec36-11e9-8095-151c0f5d7caf.png">

2019-10-11 13:54 UTC, kylehickinson requested changes
Somehow after disabling link previews, I no longer got the enable link previews option… It seems like something is supposed to be there (you can see the menu has a final separator down there but no text/image.

![IMG_C03DD67E96AA-1](https://user-images.githubusercontent.com/529104/66656942-f4a92800-ec0c-11e9-8dd6-1bd958b9ab7b.jpeg)

2019-10-11 13:55 UTC, kylehickinson commented
Ahhh, never mind, that list scrolls, and wasn't visible because of the super long URL… Not sure if we should truncate it?

2019-10-11 14:01 UTC, iccub commented
Added a 100char truncate to it, Safari truncates it too btw

<img width="544" alt="Zrzut ekranu 2019-10-11 o 15 59 53" src="https://user-images.githubusercontent.com/6950387/66657567-5636ba00-ec40-11e9-9e05-3595ce70884c.png">

2019-10-11 14:03 UTC, kylehickinson approved these changes
Works for me

2019-10-11 15:06 UTC, Brandon-T approved these changes

2019-10-14 12:32 UTC, merged