Rewards: Make the join rewards loader state independent from the panel
brave/brave-ios pull request #1636
Opened 2019-10-11 20:49 UTC by kylehickinson

Fixes brave/brave-rewards-ios#233

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Enable rewards
- Open panel, click join rewards. Verify the regular flow still works
- Reset rewards/Delete & reinstall
- Open panel, click join rewards, close panel quickly, reopen panel. Verify it is animating the loader, you can't click on it again and that when it finishes it moves to the next page
- Reset rewards/Delete & reinstall
- Open panel, click join rewards, click "Learn more". Verify both buttons within the welcome/learn more screen are loading, and you can't click them again and when it finishes, it moves to the next page.

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2019-10-14 09:08 UTC, iccub requested changes

2019-10-14 09:08 UTC, iccub commented on BraveRewardsUI/Welcome/WelcomeViewController.swift
> +    let alertController = UIAlertController(title: "Error", message: "Oops! Something went wrong. Please try again.", preferredStyle: .alert)
Localization missing

2019-10-14 09:08 UTC, iccub commented on BraveRewardsUI/Welcome/WelcomeViewController.swift
> +    alertController.addAction(UIAlertAction(title: "OK", style: .default, handler: nil))
Localization missing

2019-10-14 09:08 UTC, iccub commented on BraveRewardsUI/Create Wallet/CreateWalletViewController.swift
> +    let alertController = UIAlertController(title: "Error", message: "Oops! Something went wrong. Please try again.", preferredStyle: .alert)
Localization missing and this alert code is duplicated. Perhaps we should extract it to some common class.
On other hand this code is very small, not a big deal to duplicate it

2019-10-15 14:00 UTC, iccub approved these changes

2019-10-15 14:40 UTC, merged

2019-10-21 20:49 UTC, srirambv commented
@kylehickinson  I can still click on `Creating Wallet` button while its going on. As per step 3 its not supposed to be clickable
![1664](https://user-images.githubusercontent.com/17010094/67242079-c3a5d000-f422-11e9-834a-33942df00a43.gif)

2019-10-21 20:50 UTC, kylehickinson commented
@srirambv I actually think thats how it works already (unrelated to these changes). It looks clickable but its not doing anything when you click it