Fixes bookmark validation. Fixes #1630
brave/brave-ios pull request #1685
Opened 2019-10-15 15:23 UTC by Brandon-T

## Summary of Changes

This pull request fixes issue https://github.com/brave/brave-ios/issues/1630

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2019-10-15 16:22 UTC, iccub requested changes
fix tests, se CI logs for more details

2019-10-15 18:09 UTC, Brandon-T commented
@iccub I added more unit tests and stricter validation. This helped me catch quite a few bugs. Should be much better now.

2019-10-15 22:26 UTC, iccub commented
tests still failing

2019-10-16 15:32 UTC, iccub approved these changes

2019-10-16 15:57 UTC, merged