Fix 1714: overrides for settings view
brave/brave-ios pull request #1790
Opened 2019-10-24 16:33 UTC by quangDecember

## Summary of Changes

This pull request fixes issue #1714 

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2019-10-24 16:35 UTC, quangDecember commented
Hi I made a fix for #1714 
the problem was Settings page status bar seems to represent the OS, not the current app appearance, so I overrides it again

2019-10-24 17:26 UTC, Brandon-T commented on Client/Frontend/Settings/SettingsNavigationController.swift
> +            } else {
This is so minor imo, but it's worth mentioning just for learning purposes I guess.

```
if condition {
    return a
} else {
    return b
}

//can also be written as (without the else):

if condition {
    return a
}
return b
```

2019-10-24 17:29 UTC, Brandon-T approved these changes

2019-11-08 11:58 UTC, iccub requested changes
Please address the change that Brandon requested and we can merge this PR :)
Looks good

2019-11-08 17:37 UTC, iccub approved these changes
Thank you sir!

2019-11-08 17:39 UTC, merged