Fixes https://github.com/brave/brave-ios/issues/1840
brave/brave-ios pull request #1854
Opened 2019-10-31 17:01 UTC by Brandon-T

## Summary of Changes

This pull request fixes issue https://github.com/brave/brave-ios/issues/1840
- Issue happens because the code originally only checked for the first cell that matches the tip identifier. - However, user/qa would tip the same publisher twice so we can now have duplicate matching identifiers instead of limiting it to just one.
- Solution is to update ALL cells where the identifier matches.
- Tested and works.

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2019-10-31 18:18 UTC, kylehickinson approved these changes

2019-10-31 18:18 UTC, kylehickinson requested changes
Just realized, can you duplicate these fixes in the AutoContributeDetails controller as well?

2019-11-01 17:21 UTC, Brandon-T commented
> Just realized, can you duplicate these fixes in the AutoContributeDetails controller as well?

@kylehickinson AutoContributeDetails doesn't seem to have this problem.

It updates the image in `cellForRow` which means it'll update for every cell perfectly fine.

2019-11-01 18:07 UTC, kylehickinson approved these changes

2019-11-01 18:07 UTC, merged