Fix #1986, Fix #1987 - PBO crash and clearing of PBO data from Normal to Private.
brave/brave-ios pull request #1989
Opened 2019-11-19 21:10 UTC by Brandon-T

## Summary of Changes

- Fix crash in PBO when a zombie tab still has an observer attached to it which gets released in deinit. However, if the tab is loading data while it is being killed (IE: a large PDF, or inbox or webpage), then the observer can trigger `estimatedProgress` or any other keyPath causing a crash because the webView was already killed. Solution is to guard in the observer and let the deinit run its course naturally.

- Fix PBO not clearing data when going from Normal to PBO. Going from PBO to Normal already worked from previous PR. This seems like a regression fix :S Pretty sure I had already done this exact same thing.

This pull request fixes issue #1987 && #1986

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2019-11-19 21:48 UTC, kylehickinson approved these changes
Fine with the first part (#1986), I'll let @iccub take a look at the `Clearables` stuff

2019-11-20 14:37 UTC, iccub requested changes
It still crashed for me
str:
1. Go to private mode
2. Open settings, enable Private browsing only

<img width="1209" alt="Zrzut ekranu 2019-11-20 o 15 37 05" src="https://user-images.githubusercontent.com/6950387/69247984-b14abd80-0bab-11ea-9e9a-9d6b1ab820c7.png">

2019-11-20 14:59 UTC, Brandon-T commented
> It still crashed for me
> str:
> 
> 1. Go to private mode
> 2. Open settings, enable Private browsing only
> 
> <img alt="Zrzut ekranu 2019-11-20 o 15 37 05" width="1209" src="https://user-images.githubusercontent.com/6950387/69247984-b14abd80-0bab-11ea-9e9a-9d6b1ab820c7.png">

https://bravesoftware.slack.com/archives/GB9CJGQV6/p1574261904000100?thread_ts=1574194969.003500&cid=GB9CJGQV6

I really can't reproduce it with the code in this PR.. I don't know what's going on here..

2019-11-20 16:38 UTC, iccub approved these changes
Seems to be working now, nice job

2019-11-20 16:38 UTC, iccub commented on Client/Frontend/Browser/BrowserViewController.swift
> +        //Must handle ALL keypaths
nitpick: please stick to one style for comments, sometimes you add a space after `//` sometimes not :D
we usually add spaces

2019-11-20 16:49 UTC, merged