Fix #2027 - Notification Orientation only stabled on SOME iPads
brave/brave-ios pull request #2030
Opened 2019-11-26 18:58 UTC by Brandon-T

Switch to using a constraint constant and manual calculation because `.multiplier(0.40).priority(.high)` doesn't work on ALL iPads (only some).

This makes the notification width on ALL iPads ALWAYS 40% of the longest side of the view/screen if possible.
Prior to this PR, it somehow only worked for SOME iPads and I really don't know why. IE: Sri was seeing small notifications but other QAs saw large ones. I saw large ones.

With this fix, I have tested iPad Pro 12.9in, 9.7in, iPad Air 2 and 3rd Gen.. iOS 12 and 13.
I have tested split screen and multi-tasking and rotation with all of the former.

## Summary of Changes

This pull request fixes issue #<number>

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2019-11-26 18:59 UTC, Brandon-T commented
I only tested on Simulator. I do not have a physical iPad.

2019-12-13 15:12 UTC, kylehickinson requested changes

2019-12-13 15:12 UTC, kylehickinson commented on BraveRewardsUI/Ads/AdsViewController.swift
>          $0.width.equalTo(view).priority(.high)
Is this needed for iPhone? Since we have leading > 8 and trailing < 8 above?

2019-12-13 15:12 UTC, kylehickinson commented on BraveRewardsUI/Ads/AdsViewController.swift
> +      widthAnchor?.constant = isWidthLarger ? view.bounds.width * 0.40 : view.bounds.height * 0.40
We should probably round these to nearest valid pixel (0, 0.5, 1 on 2x devices, 0, 0.33, 0.66, 1 on 3x devices, though not sure if there's an iPad that supports that currently)

2019-12-13 17:00 UTC, Brandon-T commented on BraveRewardsUI/Ads/AdsViewController.swift
>          $0.width.equalTo(view).priority(.high)
<img width="371" alt="Screen Shot 2019-12-13 at 11 58 54 AM" src="https://user-images.githubusercontent.com/1530031/70817695-1905ba00-1da0-11ea-9311-2705a78eb019.png">

Without it^

2019-12-13 17:27 UTC, kylehickinson approved these changes

2020-01-02 19:30 UTC, merged