(infra) Update constant naming to camelCase based on modern Swift conventions
brave/brave-ios pull request #2172
Opened 2020-01-09 20:35 UTC by freak4pc

## Summary of Changes

This doesn't fix an existing issue, but I noticed that the naming conventions for many constants and properties are Swift 3/4 style (ClassCase), so I've went ahead an renamed them all to classCase based on modern Swift conventions.

It's a big PR, but the changes are quite minor in the broader sense.

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
There should be nothing to test. The compiler and existing tests cover us well enough IMO.

## Reviewer Checklist:

- [-] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2020-01-10 08:18 UTC, freak4pc commented
By the way, might I suggest making sure Travis also works for PRs? you're missing a lot of testing otherwise :)

2020-01-13 12:08 UTC, iccub requested changes
wow, that was a lot of changes to look at

I'm still in talks with my team on whether we want to rename all to camel case now and to enable CI for external contributors

Found few minor issues if you would like to take a look at them, also the branch needs a rebase.
Once all is good I will try to merge that PR as soon as possible, otherwise almost each new merged PRs will result in merge conflicts on this branch

thank you for taking time working on this

2020-01-13 12:08 UTC, iccub commented on BraveRewardsUI/Create Wallet/CreateWalletViewController.swift
> +    alertController.addAction(UIAlertAction(title: Strings.oK, style: .default, handler: nil))
this must be either `ok` or `OK`, whatever sounds better

2020-01-13 12:08 UTC, iccub commented on BraveRewardsUI/Localized Strings/Strings.swift
> +  static let oK = NSLocalizedString("OK", bundle: .rewardsUI, value: "OK", comment: "")
see my previous comment

2020-01-13 12:08 UTC, iccub commented on BraveShared/BraveStrings.swift
> +// MARK:-  Common Strings.here.
remove that extra dot in front of `here`

2020-01-13 12:08 UTC, iccub commented on Client/Frontend/Settings/NewTabPageTableViewController.swift
> +        rows.append(boolRow(title: Strings.newTabPageSettingsAutoOpenKeyboard, option: Preferences.NewTabPage.autoOpenKeyboard))
the `boolRow` now looks like a class starting with small letter.
Could you rename it to `makeBoolRow` or something?

2020-01-13 12:08 UTC, iccub commented on Client/WebAuthN/U2FExtensions.swift
> +    public static let u2FAuthenticationError = NSLocalizedString("U2FAuthenticationError", tableName: "BraveShared", bundle: Bundle.braveShared, value: "Error authenticating your security key", comme
Rename both to `U2F..` 
it should be always capitalized, like here https://www.yubico.com/authentication-standards/fido-u2f/

2020-01-13 18:43 UTC, freak4pc commented on Client/Frontend/Settings/NewTabPageTableViewController.swift
> +        rows.append(boolRow(title: Strings.newTabPageSettingsAutoOpenKeyboard, option: Preferences.NewTabPage.autoOpenKeyboard))
What about `Row.boolRow()`? 

```swift
extension Row {
    func boolRow(title: String, option: Preferences.Option<Bool>, onValueChange: SwitchAccessoryView.ValueChange? = nil) -> Row {
        return Row(
            text: title,
            accessory: .view(SwitchAccessoryView(initialValue: option.value, valueChange: onValueChange ?? { option.value = $0 })),
            cellClass: MultilineValue1Cell.self,
            uuid: option.key
        )
    }
}
```

2020-01-13 19:15 UTC, freak4pc commented on Client/Frontend/Settings/NewTabPageTableViewController.swift
> +        rows.append(boolRow(title: Strings.newTabPageSettingsAutoOpenKeyboard, option: Preferences.NewTabPage.autoOpenKeyboard))
Did this for now, happy for your opinion.

2020-01-13 19:15 UTC, freak4pc commented
Rebased and fixed. I also did another quick pass to fix constants name that had underscores in them and aligned them to the rest of the naming conventions.

2020-01-14 11:11 UTC, iccub approved these changes
Looks great, can you rebase one last time?
I can block incoming PRs until you rebase, if that doesn't take long

2020-01-14 11:11 UTC, freak4pc commented
I'll make it quick ;)

2020-01-14 11:17 UTC, freak4pc commented
@iccub should be good to go

2020-01-14 11:21 UTC, iccub approved these changes
Perfect, thank you for your quick response.
I will run your branch for a bit to make sure strings and translations are working properly and then merge it

Awesome job

2020-01-14 11:22 UTC, freak4pc commented
Sounds good. Good thing we have a compiler to make life easy ;) 
Cheers!

2020-01-14 11:37 UTC, merged