Fix #1966: Show open rewards settings button in settings
brave/brave-ios pull request #2277
Opened 2020-01-29 16:29 UTC by kylehickinson

## Summary of Changes

This pull request fixes issue #1966 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- (Fresh install) Go to settings > Brave Rewards. Verify no open rewards button is there 
- Enable rewards
- Repeat step 1, but verify the open rewards settings button is there
- Tap said button, verify it opens the panel directly to settings

## Screenshots:

| Rewards Enabled | Fresh Install |
| --- | --- | 
| ![Simulator Screen Shot - iPhone 11 Pro - 2020-01-29 at 11 27 26](https://user-images.githubusercontent.com/529104/73375934-9ae76f00-428a-11ea-8d81-a2eb96b75b54.png) | ![Simulator Screen Shot - iPhone 8 - 2020-01-29 at 11 27 11](https://user-images.githubusercontent.com/529104/73375947-9de25f80-428a-11ea-9897-c4a956f2033f.png) |

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2020-01-29 18:53 UTC, Brandon-T requested changes

2020-01-29 18:53 UTC, Brandon-T commented on Client/Frontend/Settings/BraveRewardsSettingsViewController.swift
> +                    Row(text: Strings.openBraveRewardsSettings, selection: {
Does this capture `self` strongly?

2020-01-29 18:53 UTC, Brandon-T commented on Client/Frontend/Settings/SettingsViewController.swift
> +                        self.settingsDelegate?.settingsOpenRewardsSettings(self)
Same question.

2020-01-31 09:43 UTC, iccub approved these changes

2020-02-03 15:56 UTC, kylehickinson commented
pinging @Brandon-T :)

2020-02-03 17:18 UTC, Brandon-T approved these changes

2020-02-03 17:25 UTC, merged