Fixes NTP images not showing when the new assets are downloaded.
brave/brave-ios pull request #2286
Opened 2020-01-30 23:17 UTC by Brandon-T

## Summary of Changes

Not actually sure why `UIImage(named: "/var/UUID/ApplicationSupport/NTPDownloads/someImage.png")` loads "sometimes".. In the debugger, the image NEVER loads.. but in app, it loads "sometimes".. If I change it to `contentsOfFile`, it loads 100% of the time in the debugger so we are doing this to make sure it also loads 100% of the time in app.

This pull request fixes issue #<number>

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2020-01-30 23:20 UTC, iccub approved these changes
Another report to send to Apple, huh? :D

Perhaps it's another bug related to lazy initialization?

2020-01-31 10:35 UTC, iccub requested changes
Is blank for bundled resources, works for resources downloaded over the network

<img width="544" alt="Zrzut ekranu 2020-01-31 o 11 34 57" src="https://user-images.githubusercontent.com/6950387/73532814-c3ec3900-441d-11ea-9f82-4520493d64da.png">

2020-01-31 10:40 UTC, iccub commented on Client/Frontend/Browser/HomePanel/NewTabPageBackgroundDataSource.swift
> +            return UIImage(contentsOfFile: imageUrl)
Leaving this named should work, since all background are bundled.
And use `contentsOfFile` only for sponsored images at line 47

2020-01-31 12:34 UTC, jhreis commented
@iccub we shouldn't bundle resources anymore.

2020-01-31 12:35 UTC, jhreis approved these changes

2020-01-31 13:24 UTC, iccub approved these changes

2020-01-31 13:39 UTC, merged