FSettings Button UI Improvement
brave/brave-ios pull request #2434
Opened 2020-03-30 22:39 UTC by m-henderson

convert setting button from a regular button into an action button so it has a border outline and looks clickable. You can see the discussion here: #2390 

## Summary of Changes

This pull request fixes #<number>

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2020-03-30 22:51 UTC, m-henderson commented
could someone help me with running the unit tests? Didn't see any docs on how to run the tests for the UI. Thanks.

2020-03-31 14:53 UTC, kylehickinson requested changes
Hey @m-henderson, I'm not sure the changes I'm seeing here reflect the image… It looks like you may have removed the intended changeset in the last commit instead of the unintended ones 😅

2020-03-31 14:55 UTC, m-henderson commented
@kylehickinson lol omg. should I just abandon this pr and open another? I had a long day yesterday 🤣

2020-03-31 14:56 UTC, kylehickinson commented
@m-henderson Haha, you can continue in this PR it's no problem 😄

2020-03-31 15:01 UTC, m-henderson commented
@kylehickinson okay........ I converted it to an ActionButton for real this time.

2020-03-31 15:02 UTC, kylehickinson commented
@m-henderson Can you also remove the LaunchScreen and FavouritesViewController change please 🙂

2020-03-31 15:24 UTC, m-henderson commented
@kylehickinson what would be the best way to do that? I am reverting the commit and removing the changes but that leaves me with nothing to push.

2020-03-31 15:47 UTC, kylehickinson commented
There's quite a few ways to in Git, you could [rewite the commit history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History), or just revert everything and recommit just the 1 change you want, or make a new commit [reversing the changes for only those particular files](https://www.shellhacks.com/git-revert-file-to-previous-commit/) 

Depending on the git application you are using, some of this may be easier than others 🙂

2020-03-31 17:17 UTC, m-henderson commented
@kylehickinson I am so sorry for the confusion. we should be good to go now. I reverted the changes and added just the button change.

2020-03-31 18:55 UTC, kylehickinson commented
Thanks a bunch @m-henderson, just going to have design check it out before giving the go-ahead :) 

cc @jamesmudgett @karenkliu

2020-03-31 21:29 UTC, jhreis commented
Talked with design, they aren't entirely sure what they want yet, but it is probably not going to be something quite like this. I will update when I know more. Blocking PR for now.

2020-06-01 16:47 UTC, iccub commented
Talked to the design team and they do not want to go with this UI change, so closing this PR for now.
Please keep track whether this ticket https://github.com/brave/brave-ios/issues/2390 gets `blocked: needs design` label removed, this means the design is finalized and approved by our design team

Thank you for your contribution nonetheless :)

2020-06-01 16:47 UTC, closed without merging