Fix #2611: Update URLs for fetching adblock data
brave/brave-ios pull request #2612
Opened 2020-06-09 20:05 UTC by kylehickinson

## Summary of Changes

This pull request fixes #2611

Blocked: Waiting on updated lambda's/devops to complete

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
- Test adblock downloads to `abp-data` folder correctly
- Test adblock stats increase
- Test regional adblock

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2020-06-09 22:06 UTC, iccub commented
Looks good, have you tested that all resources are getting downloaded correctly? .dat .json files for general blocklists and for regional resources, I will check tomorrow morning

2020-06-10 00:34 UTC, kylehickinson commented
Yeah I put breakpoints on the resources downloaded and confirmed the eTags were the same as they were on s3 in the ios folder. I also tried the regional lists and they are also downloaded correctly.  Only thing I haven't checked is that stat collection as `dat` files were not updated

2020-06-10 15:29 UTC, iccub requested changes

2020-06-10 15:29 UTC, iccub commented on Client/WebFilters/AdblockerType.swift
> +        return URL(string: AdblockResourceDownloader.endpoint)
Doesn't need to be a computed variable anymore

2020-06-15 10:04 UTC, iccub approved these changes

2020-06-15 11:42 UTC, iccub commented
This still blocked? I ran it and it downloads assets correctly and ads are blocked

2020-06-15 13:52 UTC, kylehickinson commented
@iccub I'll follow up today, last I heard there was some issues popping up server side still.

2020-06-16 04:29 UTC, merged