Fix Brave Ads state-level targeting crash
brave/brave-ios pull request #2693
Opened 2020-07-02 18:06 UTC by tmancey

## Summary of Changes

This pull request fixes #<number>

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2020-07-02 18:09 UTC, kylehickinson requested changes

2020-07-02 18:09 UTC, kylehickinson commented on BraveRewardsUI/Settings/Ads/Details/AdsDetailsViewController.swift
> +        cell.accessoryLabel?.text = "Disabled"
This has to be localized

2020-07-07 14:42 UTC, kylehickinson requested changes
Still needs to be localized (put static text in entry in Strings.swift, then use that there)

2020-07-07 18:01 UTC, tmancey commented
@kylehickinson Fixed localization issues

2020-07-07 18:37 UTC, tmancey commented on BraveRewardsUI/Settings/Ads/Details/AdsDetailsViewController.swift
> +        cell.accessoryLabel?.text = "Disabled"
Fixed

2020-07-07 18:40 UTC, kylehickinson approved these changes

2020-07-07 18:40 UTC, merged