Fix: #2695 : Add Release Notes for v1.18
brave/brave-ios pull request #2696
Opened 2020-07-06 04:13 UTC by srirambv

## Summary of Changes

This pull request fixes #2695 

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:

NA

## Screenshots:

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

2020-07-06 14:53 UTC, iccub approved these changes

2020-07-06 18:10 UTC, kjozwiak requested changes

2020-07-06 18:10 UTC, kjozwiak commented on CHANGELOG.md
> + - Implemented enhancments to new tab page and favourites overlay. ([#2578](https://github.com/brave/brave-ios/issues/2578))
* `enhancments ` should be `enhancements`
* let's use `favorites` rather than `favourites` as that's being used throughout this release note as well
* Lets use `New Tab Page` (we capitalize it on Desktop and have done it previously on Android releases)

2020-07-06 18:10 UTC, kjozwiak commented on CHANGELOG.md
> + - Implemented enhancments to favorites to use fallback monogram letters instead of low-resoltuion icons. ([#2579](https://github.com/brave/brave-ios/issues/2579))
* `enhancments ` should be `enhancements`
* `low-resoltuion` should be `low-resolution`

2020-07-06 18:10 UTC, kjozwiak commented on CHANGELOG.md
> + - Fixed new tab page from loading new images when swithcing between tabs. ([#2071](https://github.com/brave/brave-ios/issues/2071))
* `swithcing` should be `switching`
* Lets use `New Tab Page` (we capitalize it on Desktop and have done it previously on Android releases)

2020-07-07 06:21 UTC, kjozwiak requested changes

2020-07-07 06:21 UTC, kjozwiak commented on CHANGELOG.md
> + - Implemented enhancements to new tab page and favorites overlay. ([#2578](https://github.com/brave/brave-ios/issues/2578))
Should change `new tab page` --> `New Tab Page`

2020-07-07 06:21 UTC, kjozwiak commented on CHANGELOG.md
> + - Implemented enhancements to favorites to use fallback monogram letters instead of low-resoltuion icons. ([#2579](https://github.com/brave/brave-ios/issues/2579))
Should change `low-resoltuion` --> `low-resolution`

2020-07-07 06:21 UTC, kjozwiak commented on CHANGELOG.md
> + - Fixed New Tab Page from loading new images when swithcing between tabs. ([#2071](https://github.com/brave/brave-ios/issues/2071))
Should change `swithcing` --> `switching`

2020-07-07 06:27 UTC, kjozwiak approved these changes
LGTM 👍

2020-07-07 06:29 UTC, merged