Fix #2831: Add default browser callouts for iOS14 users.
brave/brave-ios pull request #2850
Opened 2020-08-31 09:34 UTC by iccub

## Summary of Changes

This pull request fixes #2831 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

<img width="529" alt="Zrzut ekranu 2020-08-31 o 11 26 59" src="https://user-images.githubusercontent.com/6950387/91705708-a0d56380-eb7d-11ea-81a6-369fc5522ad4.png">

<img width="529" alt="Zrzut ekranu 2020-08-31 o 11 27 07" src="https://user-images.githubusercontent.com/6950387/91705806-c2cee600-eb7d-11ea-9a80-700821af02c7.png">

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue is assigned to a milestone (should happen at merge time).

2020-08-31 11:04 UTC, iccub commented
blocked, still undecided if we include default browser tickets to 1.20

2020-08-31 14:05 UTC, kylehickinson requested changes
Looks good! Just a few things to check out, and the one accessibility label

2020-08-31 14:05 UTC, kylehickinson commented on Client/Frontend/Browser/New Tab Page/Sections/DuckDuckGoCalloutSectionProvider.swift
> +        collectionView.register(Cell.self)
I would double check that this does not collide registrations, as the reuse ID is derived from the name of the type. Not sure if for typealiases it will resolve to "Cell" or the actual type

2020-08-31 14:05 UTC, kylehickinson commented on Client/Frontend/Browser/New Tab Page/Sections/DefaultBrowserCalloutProvider.swift
> +        $0.contentEdgeInsets = UIEdgeInsets(equalInset: 4)
Missing an `accessibilityLabel` on this button since it's image only.

2020-08-31 14:09 UTC, iccub commented on Client/Frontend/Browser/New Tab Page/Sections/DuckDuckGoCalloutSectionProvider.swift
> +        collectionView.register(Cell.self)
im ok with not using typealias at all, will check

2020-08-31 16:31 UTC, iccub commented on Client/Frontend/Browser/New Tab Page/Sections/DuckDuckGoCalloutSectionProvider.swift
> +        collectionView.register(Cell.self)
cell.reuseIdentifier are as follows:
`Optional("NewTabCenteredCollectionViewCell<DefaultBrowserCalloutView>.Type")`
`Optional("NewTabCenteredCollectionViewCell<FavoritesOverflowButton>.Type")`
`Optional("NewTabCenteredCollectionViewCell<DuckDuckGoCalloutButton>.Type")`

I will rename `Cell` anyway to `DuckDuckGoCalloutSectionCell` etc

2020-08-31 18:54 UTC, kylehickinson approved these changes

2020-09-09 09:37 UTC, iccub commented
After feedback from James

<img width="529" alt="Zrzut ekranu 2020-09-9 o 11 36 52" src="https://user-images.githubusercontent.com/6950387/92582075-cacf0a00-f290-11ea-84e7-5bd070e85303.png">

2020-09-10 08:00 UTC, merged