Fix:#2883: Add Release notes for v1.20
brave/brave-ios pull request #2886
Opened 2020-09-16 14:53 UTC by srirambv

## Summary of Changes

This pull request fixes #2883 

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:

NA

## Screenshots:

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2020-09-16 22:33 UTC, kjozwiak requested changes

2020-09-16 22:33 UTC, kjozwiak commented on CHANGELOG.md
> + - Implemented capability to set Brave as default browser. ([#2785](https://github.com/brave/brave-ios/issues/2785))
I think using `Added ability to set Brave as the default browser` might sound a bit better/easier to understand. I don't think there's a need to use the word `capability` as that's a given due as it's being implemented/added.

2020-09-17 01:02 UTC, MrWaste commented
Please Fix this.
Proof:

![Brave](https://user-images.githubusercontent.com/49108816/93407332-c2557100-f846-11ea-9fef-9c8ae59e4359.png)
![Duck](https://user-images.githubusercontent.com/49108816/93407333-c3869e00-f846-11ea-827f-45d785cc4caf.png)

2020-09-17 04:15 UTC, kjozwiak commented
@MrWaste this issue is for the release notes for the next release. Please create a new issue describing either the issue you're having or a feature request via https://github.com/brave/brave-ios/issues/new/choose.

2020-09-17 04:24 UTC, kjozwiak commented
@srirambv we'll need to add the following into the release notes as well as it's happening on the current release:

* Youtube failing to load next videos #2810 - https://github.com/brave/brave-ios/issues/2810

@diracdeltas should the following security issues be mentioned in the release notes? They're currently set as `release-notes/exclude`:

* another security issue in serialize-javascript #2855 - https://github.com/brave/brave-ios/issues/2855
* Fix Security Token for YoutubeAdblock.js #2813 - https://github.com/brave/brave-ios/issues/2813

@bsclifton @anthonypkeane believe we should probably include the following as well as these changes are user facing. General rule is that if we've changed/fixed/added anything new that the user will see, we need to mention it. Obviously sometimes there's exceptions. Any reason why these are being labeled as `release-notes/exclude`? Is there a reason why we shouldn't be adding them?

* IAP VPN Subscription Text #2747 - https://github.com/brave/brave-ios/issues/2747 <-- `UI text change`
* VPN text update #2825 - https://github.com/brave/brave-ios/issues/2825 <-- another user facing text change
* Rewards text update #2829 - https://github.com/brave/brave-ios/issues/2829 <-- large text change
* Update onboarding flow #2832 - https://github.com/brave/brave-ios/issues/2832 <-- probably important to mention IMO

2020-09-17 05:03 UTC, MrWaste commented
@kjozwiak do you have a time frame when the update will be released?

2020-09-17 06:16 UTC, bsclifton commented
@MrWaste unfortunately not - we submitted 1.20 back on Friday... and we've been waiting to hear back since then. We've had a few rejections from the App Store before this latest attempt- with each attempt, we're addressing items. The rejections we received (for Guideline violations) weren't for anything new, they were for features we have had for quite some time (roughly a year)

2020-09-17 06:18 UTC, MrWaste commented
@bsclifton
Hopefully Epic can stop most the of the Bs from the apps being rejected.. I do some app development too. Good Luck!

2020-09-17 06:32 UTC, MrWaste commented
@bsclifton

I was just wondering, what kind of features got it declined. You said they were there for 1 year ish. Hm..

2020-09-17 20:09 UTC, gh0sti commented
> @MrWaste unfortunately not - we submitted 1.20 back on Friday... and we've been waiting to hear back since then. We've had a few rejections from the App Store before this latest attempt- with each attempt, we're addressing items. The rejections we received (for Guideline violations) weren't for anything new, they were for features we have had for quite some time (roughly a year)

I think its BS for Apple to treat you guys differently from Edge, Chrome, and Firefox. All of them got their default browser option update out with iOS 14 release. Even duckduckgo did. Apple doesn't treat each developer the same.

2020-09-18 07:51 UTC, srirambv commented
@kjozwiak ready for re-review

2020-09-22 19:45 UTC, MrWaste commented
How is the update with apple rejecting the app updates?
Everyday I am checking for update and still nothing. I can't for this update to finally fix the YouTube problem + pus default browser.

2020-09-25 19:53 UTC, iccub commented
We just got approved :)

2020-09-25 19:54 UTC, iccub approved these changes

2020-09-25 21:26 UTC, iccub approved these changes

2020-09-25 21:30 UTC, bsclifton approved these changes
++

2020-09-25 21:31 UTC, kjozwiak approved these changes
LGTM 👍

2020-09-25 21:31 UTC, merged