Show toast before auto filling credentials
brave/brave-ios pull request #2924
Opened 2020-10-02 04:00 UTC by AasthaGupta

## Summary of Changes

This pull request fixes #507 

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2020-10-02 04:11 UTC, AasthaGupta commented
![Uploading Simulator Screen Shot - iPhone 11 Pro Max - 2020-10-02 at 09.40.58.png…]()

2020-10-02 15:36 UTC, kylehickinson commented
Hi @AasthaGupta, first of all thanks for the PR! :) 

I just tested out the code though and it seems like it will show the toast regardless of if you have credentials for that website (tested it on https://gitbub.com/login) so it seems like this may need a bit more work to get the correct behavior (Probably need code to check that the credential exists before showing the toast is all)

Also we may want to include an option for users to do this, but I think we'll have to talk to product to figure that out so I wouldn't worry about it for now :)

2020-10-03 11:03 UTC, AasthaGupta commented
@kylehickinson Sorry about missing it out. I have added the check now.

2020-11-12 15:59 UTC, kylehickinson requested changes

2020-11-12 15:59 UTC, kylehickinson commented on Client/Frontend/Browser/LoginsHelper.swift
> +                })
Sorry for this being so late 🙂 Is there a reason you evaluate the JS here if logins isn't empty? Shouldn't it just return?

2021-08-02 14:50 UTC, iccub commented
We are moving to chromium's autofill implementation soon, going to close this ticket for now

2021-08-02 14:50 UTC, closed without merging