Fix #3034, #3032 - Bookmarks performance & adding/editing & displaying last selected folder/default folder
brave/brave-ios pull request #3043
Opened 2020-11-17 06:50 UTC by Brandon-T

## Summary of Changes
- Fixes performance issues found in #3032 when a LARGE amount of bookmarks are added, synced, and the user goes to add more or edit existing ones.
- Fixes performance issues with displaying of bookmark icons when a large amount of bookmarks are loaded.
- Fixes search suggestions regression so that when the user searches in the URL bar, it will suggest bookmarks as well.
- Adds ability to display the last viewed folder by default. If no folder is viewed, it displays the mobile bookmarks folder. If the root folder was viewed, it displays that. IE: It will always display the last viewed folder by default, and fallback to the mobile bookmarks folder.

This pull request fixes: #3034, #3032

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2020-11-17 10:55 UTC, iccub requested changes
code looks good, need updated brave-core framework to fully test it

2020-11-17 10:55 UTC, iccub commented on Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift
> +extension UIViewController {
Can we make this `private`?

2020-11-17 17:33 UTC, Brandon-T commented on Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/BookmarksViewController.swift
> +extension UIViewController {
Fixed.

2020-11-18 14:31 UTC, iccub requested changes

2020-11-18 14:31 UTC, iccub commented on Client/Frontend/Browser/Search/SearchLoader.swift
> +                let bookmarks = Set<Site>(Bookmarkv2.byFrequency(query: self.query).map { Site(url: $0.url ?? "", title: $0.title ?? "", bookmarked: true) })
This should show bookmarks only - exclude folders.

2020-11-19 23:24 UTC, iccub approved these changes

2020-11-20 14:57 UTC, iccub approved these changes

2020-11-20 15:17 UTC, merged