Renamed `BraveExportedBookmark` to `BookmarkNode`
brave/brave-ios pull request #3117
Opened 2020-12-05 16:37 UTC by Brandon-T

## Summary of Changes
- Renamed `BraveExportedBookmark` to `BookmarkNode` so that it works with the 1.16.x uplift.
- Dependent on https://github.com/brave/brave-core/pull/7355 which is Dependent on: https://github.com/brave/brave-core/pull/7349

- Fixes Browser-Metrics issue where a new file is created every time and is 4.2MB in size.

This pull request fixes #3099

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2020-12-05 16:41 UTC, soner-yuksel approved these changes

2020-12-05 18:35 UTC, iccub requested changes
Need to upload new Rewards lib to gh releases, no?

2020-12-07 11:55 UTC, iccub commented
Do you want to clear current browserMetrics data in this pull request too? or is it done at brave-core

2020-12-07 16:08 UTC, iccub approved these changes

2020-12-08 09:58 UTC, merged