Fix#2933:  Update Brave VPN intro card text + Graphic
brave/brave-ios pull request #3143
Opened 2020-12-11 21:11 UTC by soner-yuksel

Adding new Asset Title - Subtitle - Button Title and Graphic for VPN Intro Banner

## Summary of Changes

This pull request fixes #2933

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Go to settings
- See the intro card
- Check Changes on the banner

## Screenshots:

![test33](https://user-images.githubusercontent.com/6643505/101954994-07313f80-3bcb-11eb-8c26-e01bca04a4c7.png)

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2020-12-16 13:52 UTC, Brandon-T approved these changes

2021-01-04 15:04 UTC, iccub requested changes

2021-01-04 15:04 UTC, iccub commented on BraveShared/BraveStrings.swift
> +            NSLocalizedString("learnMore",
change this key, it is used already, prefix it with `vpn.` to make sure it is unique

2021-01-12 11:26 UTC, iccub approved these changes

2021-01-12 11:27 UTC, merged