Fix #3133 - Implement GPC (DOM only)
brave/brave-ios pull request #3203
Opened 2021-01-15 20:42 UTC by jumde

## Summary of Changes

This pull request fixes #3133 

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:
1. Navigate to https://webtest-pj.herokuapp.com/gpc.html and verify that `navigator.globalPrivacyControl` is true for both the mainframe and the iframe.

## Screenshots:
<img width="349" alt="Screen Shot 2021-01-15 at 12 41 55 PM" src="https://user-images.githubusercontent.com/1903815/104776528-1443d000-572f-11eb-81c2-19e3a1a6924f.png">

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2021-01-15 20:48 UTC, kylehickinson approved these changes

2021-01-15 20:54 UTC, pes10k approved these changes
Looks great w/ configurable change!

2021-01-16 06:18 UTC, pes10k commented
Added tests for QA here https://dev-pages.brave.software/dom-properties.html

2021-01-18 09:58 UTC, iccub commented on Client/Frontend/UserContent/UserScripts/AllFrames/AtDocumentStart/gpc.js
> +/* vim: set ts=2 sts=2 sw=2 et tw=80: */
not a big deal but i am not sure whether we should version vim settings

2021-01-19 15:47 UTC, kylehickinson requested changes
Just piggy backing on @iccub's comment, can we please remove the changes to the files: `AllFramesAtDocumentEnd.js`, `MainFrameAtDocumentEnd.js` and `MainFrameAtDocumentStart.js`. Not sure why these files are changed when you only added a script to all frames start

2021-01-19 17:29 UTC, kylehickinson approved these changes
Discussed on Slack, will deal with webpack'd files in a separate commit as it seems to be generating different files regardless of folder the new JS is added to.

2021-01-19 17:35 UTC, merged