Ref #3177: Add more regions for Ecosia.
brave/brave-ios pull request #3213
Opened 2021-01-19 23:33 UTC by iccub

## Summary of Changes

This pull request fixes #<number>

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2021-01-19 23:38 UTC, kylehickinson approved these changes

2021-01-19 23:38 UTC, Brandon-T approved these changes

2021-01-19 23:39 UTC, soner-yuksel approved these changes

2021-01-20 00:23 UTC, bsclifton commented on Client/Frontend/Browser/Search/InitialSearchEngines.swift
> +    static let ecosiaDefaultRegions = ["AT", "AU", "BE", "BY", "CA", "DK", "ES", "FI", "GR", "HU", "IT",
- I don't think `BY` is supposed to be in here; maybe copy/paste error?
- others look good!

2021-01-20 00:24 UTC, bsclifton requested changes
comment left; I think one was put by accident, otherwise LGTM! 😄

2021-01-20 10:45 UTC, iccub commented
@bsclifton thanks, removed 'BY', added it by mistake

2021-01-20 16:50 UTC, bsclifton approved these changes
Perfect 😄👌

2021-01-20 16:53 UTC, merged