Added New Certificate for CloudFlare
brave/brave-ios pull request #3338
Opened 2021-02-22 20:17 UTC by Brandon-T

## Summary of Changes
- Adds the new CloudFlare root certificate (The CA is Baltimore Cyber Trust)

This pull request fixes #3337

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2021-02-22 20:24 UTC, soner-yuksel approved these changes

2021-02-22 20:50 UTC, jumde approved these changes
lgtm

2021-02-22 22:28 UTC, kylehickinson requested changes
Test still fails:

```
testPinningWithHostValidation, failed - Validation failed but should have succeeded: Error Domain=com.brave.pinning-certificate-evaluator Code=-1 "Trust Evaluation Failed: Error Domain=NSOSStatusErrorDomain Code=-67818 "“p.ssl.fastly.net” certificate is expired" UserInfo={NSLocalizedDescription=“p.ssl.fastly.net” certificate is expired, NSUnderlyingError=0x600002412490 {Error Domain=NSOSStatusErrorDomain Code=-67818 "Certificate 0 “p.ssl.fastly.net” has errors: Certificate is not temporally valid;" UserInfo={NSLocalizedDescription=Certificate 0 “p.ssl.fastly.net” has errors: Certificate is not temporally valid;}}}" UserInfo={NSLocalizedDescription=Trust Evaluation Failed: Error Domain=NSOSStatusErrorDomain Code=-67818 "“p.ssl.fastly.net” certificate is expired" UserInfo={NSLocalizedDescription=“p.ssl.fastly.net” certificate is expired, NSUnderlyingError=0x600002412490 {Error Domain=NSOSStatusErrorDomain Code=-67818 "Certificate 0 “p.ssl.fastly.net” has errors: Certificate is not temporally valid;" UserInfo={NSLocalizedDescription=Certificate 0 “p.ssl.fastly.net” has errors: Certificate is not temporally valid;}}}}
```

2021-02-23 17:41 UTC, kylehickinson approved these changes

2021-02-23 17:42 UTC, merged