fix #3359 - remove 20px margin on show more button
brave/brave-ios pull request #3360
Opened 2021-03-01 02:22 UTC by jamesmudgett

## Summary of Changes

#3359 removes 20px extra margin.

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2021-03-01 09:08 UTC, iccub requested changes
Make the UI change only, npm packages got updated here for some reason,
did you update your local app by running `bootstrap.sh` script?

2021-03-01 15:06 UTC, kylehickinson commented on Client/Frontend/Browser/New Tab Page/Sections/FavoritesOverflowSectionProvider.swift
> +        return UIEdgeInsets(top: 0, left: 0, bottom: 0, right: 0)
Nit: return `.zero` instead

2021-03-02 14:34 UTC, iccub commented
I cleaned up the PR

2021-03-02 14:40 UTC, iccub approved these changes

2021-03-02 15:05 UTC, kylehickinson approved these changes

2021-03-02 15:57 UTC, merged