Fix #3378: Apply theming to TabCell
brave/brave-ios pull request #3379
Opened 2021-03-06 02:32 UTC by otaviocc

## Summary of Changes

This pull request fixes #3378.

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Screenshots:

**Existing tabs in dark and light mode**:

![photo_2021-03-06 03 27 08](https://user-images.githubusercontent.com/139272/110192059-2dfabd00-7e2c-11eb-9179-9d5b2fe09c20.jpeg)

**New tabs in dark and light mode (screenshots right after tapping on "+" to open a new tab)**:

![photo_2021-03-06 03 27 22](https://user-images.githubusercontent.com/139272/110192039-14f20c00-7e2c-11eb-9fd6-3306d92ffda3.jpeg)

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2021-03-08 15:52 UTC, iccub requested changes
Thanks for this PR, it's much easier on eyes when the white screen does not flash in private and dark themes :)

I think we should leave top items as they were before, non themeable
Look at this screen, left is old, right is new, old looks more readable to me, especially icons.
What do you think about it?

<img width="935" alt="Zrzut ekranu 2021-03-8 o 16 50 42" src="https://user-images.githubusercontent.com/6950387/110345073-7b467c80-802e-11eb-82bc-450e79bc57e2.png">

2021-03-09 19:34 UTC, otaviocc commented
> Thanks for this PR, it's much easier on eyes when the white screen does not flash in private and dark themes :)
> 
> I think we should leave top items as they were before, non themeable
> Look at this screen, left is old, right is new, old looks more readable to me, especially icons.
> What do you think about it?

Hi @iccub, my personal opinion? I don't like the gradient and prefer a solid color matching the theme (light for light, dark for dark, and purple(?) for private). But pure personal opinion/taste.

I've reverted the cell top changes, leaving the background changes (no flashing light background anymore! Hehe).

Thank you!

2021-03-10 10:52 UTC, iccub commented
I feel the same, there's no need for gradient, solid color would be enough, Firefox uses solid color afaik.
I will pass your feedback to our design team, thanks

2021-03-10 12:58 UTC, otaviocc commented
> I feel the same, there's no need for gradient, solid color would be enough, Firefox uses solid color afaik.
> I will pass your feedback to our design team, thanks

Thanks @iccub ! But the PR should be good for review now, it fixes the "flashing" background when in non-light mode.

2021-03-10 14:46 UTC, iccub commented
yeah, i am going to rerun the code again and approve, should happen today

2021-03-10 15:09 UTC, iccub approved these changes

2021-03-11 08:58 UTC, merged