Fix #3358 - Update httpse data files
brave/brave-ios pull request #3402
Opened 2021-03-11 00:17 UTC by jumde

## Summary of Changes

This pull request fixes #3358 

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:
1. Navigate to radio.garden and verify the site loads without any redirect loops
2. Navigate to httpse-everywhere.badssl.com and verify that `HTTPS Everywhere` is working

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2021-03-11 08:56 UTC, iccub approved these changes

2021-03-11 08:57 UTC, iccub commented on Client/Frontend/Browser/BrowserViewController.swift
> +        ContentBlockerHelper.clearBlockingRules()
@kylehickinson worked on this more, I will leave this part to him,
if you want me to take over and look closer at it, let me know Kyle

2021-03-11 15:13 UTC, Brandon-T approved these changes

2021-03-11 15:15 UTC, kylehickinson requested changes

2021-03-11 15:15 UTC, kylehickinson commented on Client/Frontend/Browser/BrowserViewController.swift
> +        ContentBlockerHelper.clearBlockingRules()
@jumde to fix potential race condition around not waiting for `removeContentRuleList` completion handler

2021-03-12 15:46 UTC, kylehickinson approved these changes

2021-03-24 15:22 UTC, merged