Added toggle for last visited bookmarks folder.
brave/brave-ios pull request #3435
Opened 2021-03-18 15:10 UTC by Brandon-T

## Summary of Changes
- Added a toggle to enable/disable showing the last visited bookmarks folder.

This pull request fixes #3371

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2021-03-18 21:39 UTC, kylehickinson requested changes

2021-03-18 21:39 UTC, kylehickinson commented on Client/Frontend/Settings/SettingsViewController.swift
> +                }), cellClass: MultilineValue1Cell.self)
Use `boolRow` instead (you can provide both `detailText` and `cellClass`)

2021-03-24 14:53 UTC, soner-yuksel approved these changes

2021-03-24 15:46 UTC, kylehickinson approved these changes

2021-03-25 11:05 UTC, iccub approved these changes

2021-03-25 11:06 UTC, merged