UI Bug Fixes
brave/brave-ios pull request #345
Opened 2018-10-18 18:22 UTC by kylehickinson

Resolves #335, #338, #339, #340, #341, #344

## Pull Request Checklist

- [x] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`
- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

_None included_

## Notes for testing this patch

_None included_

2018-10-18 18:25 UTC, kylehickinson commented
Please "Rebase and merge" when merging so it applies each commit individually

2018-10-19 12:57 UTC, iccub requested changes
Code looks good but found one regression, on safe area iPhones in landscape in private mode.

<img width="950" alt="zrzut ekranu 2018-10-19 o 14 55 55" src="https://user-images.githubusercontent.com/6950387/47219492-3b27c600-d3af-11e8-9818-f77248353793.png">

It looks good on latest development.

2018-10-19 13:16 UTC, kylehickinson commented
Fixed! 
![simulator screen shot - iphone x - 2018-10-19 at 09 16 31](https://user-images.githubusercontent.com/529104/47220396-ad80b200-d37f-11e8-9c94-e27943f7725b.png)

2018-10-19 14:48 UTC, iccub approved these changes

2018-10-19 14:48 UTC, merged