Fix #353: Change copy of new tab page in back/forward list
brave/brave-ios pull request #368
Opened 2018-10-26 20:38 UTC by kylehickinson

## Pull Request Checklist

- [x] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`
- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [x] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

![simulator screen shot - iphone x - 2018-10-26 at 16 37 14](https://user-images.githubusercontent.com/529104/47591426-915fb080-d93d-11e8-9c2f-98aa1723d378.png)

## Notes for testing this patch

_None included_

2018-10-30 14:47 UTC, jhreis requested changes

2018-10-30 14:47 UTC, jhreis commented on Client/Frontend/Browser/BackForwardListViewController.swift
> +            cell.site = Site(url: item.url.absoluteString, title: Strings.New_Tab)
Rename `New_Tab` text to "Home"

per: https://github.com/brave/brave-ios/issues/353

2018-10-30 15:00 UTC, kylehickinson commented
Copy updated to "Home"

2018-10-31 16:12 UTC, jhreis approved these changes

2018-10-31 16:12 UTC, merged