Fix #3665 - Performance issues with playlist
brave/brave-ios pull request #3690
Opened 2021-05-18 13:05 UTC by Brandon-T

## Summary of Changes
- Removed all mutation observers in favour of overridden properties.
- Move all JS communication to a background queue and dispatch to main only when necessary.
- Changed `AVAsset.isPlayable` to load asynchronously.

This pull request fixes #3665

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2021-05-18 16:49 UTC, jumde commented on Client/Frontend/UserContent/UserScripts/Playlist.js
> +        /*function $<observeDynamicElements>(node) {
nit: can we remove the code instead of commenting it out?

2021-05-18 16:50 UTC, jumde approved these changes
++

2021-05-19 09:55 UTC, iccub requested changes
Remove commented out code, rest looks good

2021-05-19 18:43 UTC, iccub approved these changes

2021-05-19 18:45 UTC, merged

2021-05-22 13:55 UTC, Brandon-T commented
For testing:
- Go to YouTube or any media site
- Make sure network link conditioner is set to very very bad network
- While the site is loading, keep trying to scroll the page.
- if the page doesn't scroll properly or exhibits freezing, we have a problem.
- If the page does scroll and load correctly, the toast will come up properly without lagging.
- Page overall should be much snappier.