No Bug: Update PR template
brave/brave-ios pull request #3754
Opened 2021-06-02 18:14 UTC by kylehickinson

This removes the requirement for `release-notes/include` or `release-notes/exclude` labels in the PR template

2021-06-02 18:32 UTC, iccub approved these changes

2021-06-10 17:33 UTC, kylehickinson commented
@kjozwiak Just double checking, did you have a chance to check whether or not ReleaseBoss will have a problem with closing  tickets without `release-notes/*` labels attached to them?

2021-06-10 20:22 UTC, iccub requested changes
We can also mention to always set milestone in opened pull requests

2021-07-05 21:32 UTC, kjozwiak commented
LGTM 👍 I did ask @bbondy to remove those checks from `ReleaseBoss` after we discussed it a while back. Believe @bbondy confirmed it was being removed via https://bravesoftware.slack.com/archives/C06UXF3KJ/p1624461377130400.

2021-07-05 22:07 UTC, iccub approved these changes

2021-07-05 22:07 UTC, iccub commented on PULL_REQUEST_TEMPLATE
>  - [ ] Adequate unit test coverage exists to prevent regressions.
Let's add a point to always set milestone to pull requests, QA asked for it few months ago

2021-07-05 22:19 UTC, bbondy commented
> LGTM 👍 I did ask @bbondy to remove those checks from `ReleaseBoss` after we discussed it a while back. Believe @bbondy confirmed it was being removed via https://bravesoftware.slack.com/archives/C06UXF3KJ/p1624461377130400.

Is it not working?

2021-07-05 22:24 UTC, iccub commented
It works @bbondy, this pull request was on hold until ReleaseBoss changes were done, it is unblocked now

2021-07-12 15:30 UTC, kylehickinson commented on PULL_REQUEST_TEMPLATE
>  - [ ] Adequate unit test coverage exists to prevent regressions.
Done

2021-07-12 15:37 UTC, iccub approved these changes

2021-07-12 15:37 UTC, merged