Fix #3673 - Implements CarPlay + Refactor Playlist
brave/brave-ios pull request #3887
Opened 2021-07-06 01:28 UTC by Brandon-T

## Summary of Changes

This pull request fixes #3673

## Submitter Checklist:

- [X] *Unit Tests* are updated to cover new or changed functionality
- [X] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `release-notes/(include|exclude)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue is assigned to a milestone (should happen at merge time).

2021-08-02 14:38 UTC, iccub requested changes
left few nitpick comments, will run this branch later

Besides that I think there are 2 areas worth looking into:
- See if we can remove tight coupling with BVC/App Delegate. In the future we will move to using SceneDelegates, which means we should think what code will be shared and what will be different for each opened window/scene. You can see if we can utilize delegates or passing bvc in constructor if we ever need access to it
- I had a feeling that some of code between regular player and car play player can be shared. You can see if it makes sense in any place. Of course it may not make sense to share code even if it looks similar. I'm not pro DRY in every case, just something to think about.

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/Controller/PlaylistCarplayController.swift
> +        self.mediaStreamer = PlaylistMediaStreamer(playerView: (UIApplication.shared.delegate as? AppDelegate)?.window ?? UIView())
Could we pass `UIWindow` in constructor somehow?
This is to avoid accessing AppDelegate globally

Asking because in the future we may want to move away from AppDelegate and start using SceneDelegates more

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/Controller/PlaylistCarplayController.swift
> +//        contentManager.delegate = nil
Do we need this commented out code or can be removed?

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/Controller/PlaylistCarplayController.swift
> +        if indexPath.count == 2 {
Why count here is exactly 2? Maybe name this magic number for easier understanding

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/Controller/PlaylistCarplayController.swift
> +        if indexPath.count == 1 {
same about other comment about explaining the `1` and `2` magic numbers in this context

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/Controller/PlaylistCarplayController.swift
> +            item.title = "Brave Playlist"
Does it not have to be translated?

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/Controller/PlaylistCarplayController.swift
> +            return
`return` can be removed

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/Controller/PlaylistCarplayController.swift
> +                .sink(receiveCompletion: { error in
it should be named `completion` or `status` not error, as it can handler either error or success/finished state

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/Controller/PlaylistCarplayController.swift
> +            .sink(receiveCompletion: { error in
it should be named `completion` or `status` not error, as it can handler either error or success/finished state

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/Controller/PlaylistCarplayController.swift
> +    func streamItem(item: PlaylistInfo, completion: ((PlaylistMediaStreamer.PlaybackError) -> Void)?) {
Don't we have to remove state observers here like in `playItem` method?

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/Controller/PlaylistCarplayController.swift
> +        .sink(receiveCompletion: { error in
`error` -> `completion`

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/Controller/PlaylistCarplayController.swift
> +        let browserController = (UIApplication.shared.delegate as? AppDelegate)?.browserViewController
Would it be easy to make a delegate to `bvc` or at least pass it in constructor?

To avoid using the global AppDelegate object

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/Controller/PlaylistCarplayController.swift
> +        set { objc_setAssociatedObject(self, &AssociatedKeys.thumbnailRenderer, newValue, .OBJC_ASSOCIATION_RETAIN_NONATOMIC) }
Maybe put here little explanation why you have to do it this way with objc associated objects?

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/Controller/PlaylistDetailViewController.swift
> +        view.backgroundColor = .black
To be sure, this view should always be black, there's no difference between light and dark theme?

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/Controller/PlaylistViewController.swift
> +            let playbackRate = self.player.rate
I wonder if you could get playback rate directly from the publisher instead of having to access it from `player` ?

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/Controller/PlaylistViewController.swift
> +            switch self.repeatMode {
same here, getting it from `sink` vs from self, seems like it makes sense, im just wondering

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/Controller/PlaylistViewController.swift
> +            .sink(receiveCompletion: { error in
`error` -> `completion`

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/Controller/PlaylistViewController.swift
> +                if !isNewItem {
I have a feeling that some of code between car play and regular player can be shared, might be worth exploring what would be nice to share and if it even makes sense

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/Controller/PlaylistViewController.swift
> +                .sink(receiveCompletion: { error in
`error` -> `completion`

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/Controller/PlaylistViewController.swift
> +        .sink(receiveCompletion: { error in
`error` -> `completion`

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/PlaylistCarplayManager.swift
> +    private(set) var isCarPlayAvailable: Bool = false
`Bool` can be skipped

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/PlaylistCarplayManager.swift
> +    private var contentManager = MPPlayableContentManager.shared()
Does not seem you change it, can this be set as `let`?

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/PlaylistCarplayManager.swift
> +    var currentlyPlayingItemIndex: Int = -1
`Int` can be removed

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/PlaylistCarplayManager.swift
> +        PlaylistCarplayManager()
why a closure is needed here? can we just simply write `static let shared = PlaylistCarplayManager()`

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/PlaylistCarplayManager.swift
> +        // and contentManager.context.endpointAvailable will still return true!
good job, a lot of very important documentation and comments in this class

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/Utilities/PlaylistMediaStreamer.swift
> +            //MPNowPlayingInfoPropertyPlaybackQueueCount: 0
bunch of commented out code here, do you want to leave it or remove?

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/Utilities/PlaylistMediaStreamer.swift
> +        }.resume()
Don't we need `finishTasksAndInvalidate` after resume here?
I remember we had to add it to my BraveSearch Combine code, not sure if we need it in non-Combine places too

2021-08-02 14:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/Utilities/PlaylistStatusObserver.swift
> +    private var context = 0
This does not seem used

2021-08-02 14:38 UTC, iccub commented on Data/models/PlaylistItem.swift
> +        let context = DataController.newBackgroundContext()
Why fetch is done on a background thread?

2021-08-05 19:28 UTC, Brandon-T commented on Client/Frontend/Browser/Playlist/Controller/PlaylistDetailViewController.swift
> +        view.backgroundColor = .black
We have no themes for playlist.

2021-08-05 19:29 UTC, Brandon-T commented on Client/Frontend/Browser/Playlist/Controller/PlaylistCarplayController.swift
> +            return
It can't. It would continue on to the next set of code after the switch statement.

2021-08-06 12:55 UTC, iccub reviewed
feedback review looks good to me, I will run this branch and leave functional review next week

2021-08-13 19:48 UTC, kylehickinson commented
FYI after we merge this we _must_ update provisioning profiles to include the CarPlay entitlement. Apple has made us entitlements that include both Default Web Browser and CarPlay otherwise the app will fail to sign in Release builds

2021-08-26 14:51 UTC, Brandon-T commented on Client/Frontend/Browser/Playlist/Controller/PlaylistViewController.swift
> +            switch self.repeatMode {
The publisher is generic and only returns `AnyPublisher`. The `MP` event emitted does contain the value but it is no different :D
I could pass in the actual value in the event but I'd have to do a cast on this line then from `Any` to `repeatMode` for example.

Not sure which is better.

2021-08-26 14:52 UTC, Brandon-T commented on Client/Frontend/Browser/Playlist/Controller/PlaylistViewController.swift
> +            let playbackRate = self.player.rate
Yes but I would have to cast from `Any` to `double`. Not sure if better than checking on `self`.

2021-08-26 14:54 UTC, Brandon-T commented on Client/Frontend/Browser/Playlist/Controller/PlaylistCarplayController.swift
> +        if indexPath.count == 2 {
In CarPlay, the "section" is IndexPath 1.
The List of Tabs are IndexPath 2. We only have one list of items as we don't have folders yet.
If we add folders, It would still have 1 section but multiple tabs.

2021-08-27 10:16 UTC, iccub approved these changes

2021-08-27 13:32 UTC, merged