Fix #3877 Added autofocus on url bar, when hardware keyboard connected
brave/brave-ios pull request #3928
Opened 2021-07-15 17:56 UTC by KacperWybranski

## Summary of Changes

This pull request fixes #3877 
If hardware keyboard is connected and new tab is opened, url bar will be in focus. If there's no hardware keyboard, url bar will not be in focus.
Works on iOS 14.0+.
I'm not sure though about this placement of a isHardwareKeyboardConnected() function, so opinion would be appreciated.

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2021-07-15 22:39 UTC, iccub commented on Client/Frontend/Browser/Tab Tray/TabTrayController.swift
> +            if GCKeyboard.coalesced != nil {
Can be simplified to `return GCKeyboard.coalesced != nil`

2021-07-16 07:52 UTC, KacperWybranski commented on Client/Frontend/Browser/Tab Tray/TabTrayController.swift
> +            if finished, request == nil, NewTabAccessors.getNewTabPage() == .topSites,
Seems like there were a wrong statement, since getNewTabPage always returns .topSites right now

2021-07-16 13:31 UTC, iccub requested changes
The detection logic works fine, good job :) 
We should add the keyboard check to 2 more places:

1. `BrowserViewController+KeyCommands` - when user presses CMD+T when on new tab page. The code you added applies to tab tray only right now
2. When user taps manually on `+` button from the toolbar

Possibly there is a single method that is called from those 2 places

2021-07-17 10:32 UTC, KacperWybranski commented
Hi, there is one method called from both those places and it is "openNewTab()" method in which I already added check. Everything works well in iOS Simulator although I am not able to test that on physical device right now.

2021-07-19 10:06 UTC, iccub commented
This `openNewTab` method you modified is in `TabTrayController` class which is the screen when you tap on tabs button.

When you look at `BrowserViewController+KeyCommands` file, the cmd+t method points to `openBlankNewTab` function and this function is located in `BrowserViewController`

2021-07-20 15:59 UTC, KacperWybranski commented
You are right, I changed the code in BrowserViewController, for the location focus call I copied line from TabTrayController's openNewTab method.

2021-09-03 16:12 UTC, iccub approved these changes

2021-09-03 17:17 UTC, iccub commented
I want to merge this code @KacperWybranski, could you update your `development` branch and rebase your code on top of it? Otherwise our CI fails

2021-09-04 10:19 UTC, KacperWybranski commented
@iccub sure i will do it shortly

2021-09-04 10:42 UTC, KacperWybranski commented
@iccub is it fine now? Not sure if I did it correctly :D

2021-09-05 09:56 UTC, iccub commented
@KacperWybranski  no, a lot of conflicts now :(

you can first go to your development branch, do a git pull, make sure it points to the same commit as our dev branch
https://github.com/brave/brave-ios/commits/development

then switch back to `hardware-kbrd-support`, run `git rebase development`, and that should do the trick, you may need to find a conflict or two,
this article has few tips
https://codeinthehole.com/guides/resolving-conflicts-during-a-git-rebase/


Other way would be to clone our repo again so development branch is up to date, and just create a new brach and make a new pull request with the same changes as here

We had to wait with this code for a version or two, sorry for that

2021-09-05 17:53 UTC, KacperWybranski commented
@iccub I think I will go with new PR tomorrow, I'm little confused with this :)

2021-09-06 20:55 UTC, iccub commented
Closing in favor of https://github.com/brave/brave-ios/pull/4140

Thank you for taking your time and creating new pull request for it

2021-09-06 20:55 UTC, closed without merging