Localise cleanup
brave/brave-ios pull request #400
Opened 2018-11-13 21:23 UTC by danishjafri88

## Pull Request Checklist

- [ ] My patch has gone through review and I have addressed review comments
- [ ] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have marked the bug with `[needsuplift]`
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

If your patch includes user interface changes that you would like to suggest or that you would like UX to look at, please include them here.

## Notes for testing this patch

If useful, please leave notes for QA, explaining what this patch changes and how it can be best tested and verified.

## Additional Info
The Duplicates.txt file contains list of duplicate strings with different contexts. Though similar contextual duplicates have been removed, please review and mark in the remaining as well. Strings are mostly in BraveStrings.swift and Strings.swift. Some in BraveStrings are marked with their respective usage swift file as PRAGMA MARK. We can either let it be in BraveStrings or move to the respective files.

2018-11-13 21:50 UTC, kylehickinson commented
Please rebase this on `development@HEAD`, Travis shows there are build errors for missing Strings:

```
[21:37:30]: ▸ ❌  /Users/travis/build/brave/brave-ios/Client/Frontend/Browser/Search/SearchSuggestionsPromptView.swift:39:28: type 'Strings' has no member 'Turn_on_search_suggestions'
[21:37:30]: ▸ promptLabel.text = Strings.Turn_on_search_suggestions
[21:37:30]: ▸                                                   ^
[21:37:30]: ▸ ❌  /Users/travis/build/brave/brave-ios/Client/Frontend/Browser/Search/SearchSuggestionsPromptView.swift:46:34: type 'Strings' has no member 'Yes'
[21:37:30]: ▸ promptYesButton.setTitle(Strings.Yes, for: .normal)
[21:37:30]: ▸                            ^~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~
[21:37:30]: ▸ ❌  /Users/travis/build/brave/brave-ios/Client/Frontend/Browser/Search/SearchSuggestionsPromptView.swift:57:33: type 'Strings' has no member 'No'
[21:37:30]: ▸ promptNoButton.setTitle(Strings.No, for: .normal)
[21:37:30]: ▸                                  ^~~~~~~ ~~~
[21:37:30]: ▸ ❌  /Users/travis/build/brave/brave-ios/Client/Frontend/Browser/Search/SearchSuggestionsPromptView.swift:39:28: type 'Strings' has no member 'Turn_on_search_suggestions'
[21:37:30]: ▸ promptLabel.text = Strings.Turn_on_search_suggestions
[21:37:30]: ▸                                            ^~~
[21:37:30]: ▸ ❌  /Users/travis/build/brave/brave-ios/Client/Frontend/Browser/Search/SearchSuggestionsPromptView.swift:46:34: type 'Strings' has no member 'Yes'
[21:37:30]: ▸ promptYesButton.setTitle(Strings.Yes, for: .normal)
[21:37:30]: ▸                            ^~~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~
[21:37:30]: ▸ ❌  /Users/travis/build/brave/brave-ios/Client/Frontend/Browser/Search/SearchSuggestionsPromptView.swift:57:33: type 'Strings' has no member 'No'
[21:37:30]: ▸ promptNoButton.setTitle(Strings.No, for: .normal)
```

2018-11-14 23:02 UTC, iccub requested changes

2018-11-14 23:02 UTC, iccub commented on BraveShared/BraveStrings.swift
> +// PRAGMA MARK: Common Strings Here.
Just `// MARK: xxx` can be used, or `// MARK: - xxx` if you want section to be underlined. Replace it in all places

2018-11-14 23:02 UTC, iccub commented on BraveShared/BraveStrings.swift
>  public extension Strings {
Why is it empty?

2018-11-14 23:02 UTC, iccub commented on l10n/LocalizedMatcher.sh
> +egrep --exclude-dir={ThirdParty,Carthage,fastlane,L10nSnapshotTests,l10n} --include=\*.swift -nR "NSLocalizedString(.*[\n]*)" . > localizedStringLocations.txt
Could you add some comment in the script about what it does?

2018-11-14 23:03 UTC, iccub commented
Also is there any reason for us having `Strings.swift` and `BraveStrings.swift`  separately?

2018-11-14 23:21 UTC, jhreis commented
@iccub in reference to last question about `strings` vs `bravestrings`.

Our initial hope was to leave `strings.swift` as untouched as possible since it is part of the FF `Shared` module. However, I suspect this won't work given how much we needed to remove.

That being said, we can re-address later, but would be part of a larger string refactor at another time.

2018-11-16 09:21 UTC, danishjafri88 commented on BraveShared/BraveStrings.swift
> +// PRAGMA MARK: Common Strings Here.
Done :)

2018-11-16 09:21 UTC, danishjafri88 commented on BraveShared/BraveStrings.swift
>  public extension Strings {
Duplicated entry cause os a script. Removed

2018-11-16 09:27 UTC, danishjafri88 commented on l10n/LocalizedMatcher.sh
> +egrep --exclude-dir={ThirdParty,Carthage,fastlane,L10nSnapshotTests,l10n} --include=\*.swift -nR "NSLocalizedString(.*[\n]*)" . > localizedStringLocations.txt
Added a description.

2018-11-16 10:40 UTC, iccub approved these changes

2018-11-16 16:01 UTC, merged