Fixed invalid crash report
brave/brave-ios pull request #401
Opened 2018-11-14 16:32 UTC by danishjafri88

## Pull Request Checklist

- [ ] My patch has gone through review and I have addressed review comments
- [ ] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

## Screenshots

If your patch includes user interface changes that you would like to suggest or that you would like UX to look at, please include them here.

## Notes for testing this patch

If useful, please leave notes for QA, explaining what this patch changes and how it can be best tested and verified.

2018-11-14 16:51 UTC, jhreis requested changes

2018-11-14 16:51 UTC, jhreis commented on Client.xcodeproj/project.pbxproj
> +						DevelopmentTeam = CZ8C3324BS;
Remove team id

2018-11-14 18:02 UTC, danishjafri88 commented on Client.xcodeproj/project.pbxproj
> +						DevelopmentTeam = CZ8C3324BS;
Done

2018-11-16 16:02 UTC, jhreis commented on Client.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
Can you delete these actual lines? This still overrides the xcconfig files, if it is empty 😄

2018-11-16 19:00 UTC, danishjafri88 commented on Client.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = "";
Oops ! removed

2018-11-16 19:45 UTC, jhreis approved these changes

2018-11-16 19:45 UTC, merged