Fix #4082 - Fix pasteboard URL and in RecentSearch quick search URL
brave/brave-ios pull request #4118
Opened 2021-09-01 13:20 UTC by Brandon-T

## Summary of Changes
- Stop double encoding of URL when quick search or pasteboard searching.
- Note: It is impossible to tell if a "string" in the Pasteboard is a URL or a string. The Apple APIs `UIPasteboard.general.hasStrings` returns true even for URLs and the one for `hasURLs` returns false. So for this reason, I have to check if it can create a URL from the text via `URL(string: ....)` as `URIFixup.getURL(....)` will fail on strings but not URLs (which it will double percent encode).

This pull request fixes #4082

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2021-09-01 14:08 UTC, soner-yuksel approved these changes

2021-09-01 14:09 UTC, soner-yuksel commented
`testOpenURLScheme` is failing after the change, test case needs to be fixed.

2021-09-03 16:14 UTC, iccub requested changes
tests fail

2021-09-09 10:05 UTC, iccub approved these changes
Can you add test plan to it @Brandon-T?

2021-09-09 10:05 UTC, merged

2021-09-10 15:45 UTC, Brandon-T commented
Test Plan:

1. Go to `https://brave.com" in Safari iOS.
2. "Share" the web-page and hit "open in brave".
3. Verify that the URL bar shows the correct URL and the page displayed is correct.

1. Go to `https://www.google.com/search?q=hello%20world` in Safari iOS.
2. "Share" the web-page and hit "open in brave".
3. Verify that the URL bar shows the correct URL and the page displayed is correct and the search bar displays `hello world`.

1. Go to `https://www.google.com/search?q=hello%world` in Safari iOS.
2. "Share" the web-page and hit "open in brave".
3. Verify that the URL bar shows the correct URL and the page displayed is correctly and the search bar displays `hello%world`.

1. Go to `https://www.google.com/search?q=https%3A%2F%2Fbrave.com%3Ftest%26foo%3Dhello%20world` in Safari iOS.
2. "Share" the web-page and hit "open in brave".
3. Verify that the URL bar shows the correct URL and the page displayed is correctly and the search bar displays `https://brave.com?test&foo=hello world`.

1. Open Safari iOS and go to `brave://open-url?url=https%3A%2F%2Fwww.google.com%2Fsearch%3Fq%3Dhello%2520world`
2. Verify that it went to google and searched `hello world`.