Fix #4081 - URL parsing for arithmetic URLs and URLs with more than one dot
brave/brave-ios pull request #4121
Opened 2021-09-01 15:00 UTC by Brandon-T

## Summary of Changes
- If a URL can be converted to a number, it is not considered a valid URL: `120`, `120.5`.
- If a URL is a mathematical expression, it is not considered a valid URL: `125.5 * 100`.
- If a URL contains more than one dot but is not a valid IP address, is schemeless, it is not a valid URL: `brave.new.world`

This mimics the behaviour observed in Safari iOS.

This pull request fixes #4081

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2021-09-01 15:09 UTC, iccub approved these changes
might be worth adding a unit test for it

2021-09-09 15:23 UTC, iccub requested changes
`testURIFixup` fails

2021-09-10 15:34 UTC, iccub approved these changes

2021-09-10 15:39 UTC, soner-yuksel approved these changes

2021-09-10 15:52 UTC, Brandon-T commented
Test Plan:

1. Go to both URLs: `120` AND `120.5` in the URL bar.
2. Verify that it does NOT go to any website, and instead it searches for `120` and `120.5` in the default search engine.
-
1. Go to `125.5 * 100`.
2. Verify that it searched for `125.5 * 100` in the default search engine.
-
1. Go to `brave.new.world`.
2. Verify that it cannot reach that web-page.
-
1. Go to `brave.new.world.whatever`.
2. Verify that it was submitted to the default search engine.
-
1. Go to `brave.com`.
2. Verify that it does go to the website correct.
-
1. Go to `151.101.1.32`.
2. Verify that it shows the `fastly` error page.

2021-09-10 15:58 UTC, kylehickinson approved these changes

2021-09-13 15:44 UTC, jumde requested changes
1. Valid URLs like `jumde.github.io` fail the `checkValidURL` test
2. Omnibox test suite can be used to add more test coverage for valid URLs: https://source.chromium.org/chromium/chromium/src/+/main:components/omnibox/browser/autocomplete_input_unittest.cc;l=29

2021-09-13 18:55 UTC, jumde approved these changes
lgtm

2021-09-13 19:42 UTC, merged