Fix #4191: - Allow sharing Brave Playlist + Fix Time Formatting for >= 1-Hour
brave/brave-ios pull request #4192
Opened 2021-09-17 15:12 UTC by Brandon-T

## Summary of Changes
- Fix Time on Playlist showing incorrectly when Time >= 1-Hour.
- Added Sharing to Playlist.

This pull request fixes #4191

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Screenshots:

![image](https://user-images.githubusercontent.com/1530031/133806444-c91e7fce-6847-4b1a-92d7-a5c3a6a2f8ba.png)
![image](https://user-images.githubusercontent.com/1530031/133806493-ed734668-93e2-42aa-9b90-ceb92767ebd8.png)

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2021-09-17 15:38 UTC, iccub requested changes

2021-09-17 15:38 UTC, iccub commented on Client/Frontend/Browser/Playlist/VideoPlayer/UI/VideoPlayerTrackbar.swift
>      private func timeToString(_ time: CMTime) -> String {
Since we got a bug let's add unit test for this method to catch all tricky cases

2021-09-28 11:07 UTC, iccub commented on Client.xcodeproj/Brave.xctestplan
> +        "PlaylistTests\/testVideoPlayerTrackBarTimeManualFormatter()"
why this test is skipped?

2021-09-28 11:07 UTC, iccub commented on Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDelegate.swift
> +        shareAction.backgroundColor = #colorLiteral(red: 0.1764705926, green: 0.4980392158, blue: 0.7568627596, alpha: 1)
Don't we this or similar color hardcoded somewhere already?

2021-10-04 19:37 UTC, Brandon-T commented on Client.xcodeproj/Brave.xctestplan
> +        "PlaylistTests\/testVideoPlayerTrackBarTimeManualFormatter()"
I added two tests. One is testing my manual code which isn't ever used, and the other is testing the Formatter from Apple. If ever in the future we switch to the manual parsing, this test would be enabled again.

2021-10-04 19:38 UTC, Brandon-T commented on Client/Frontend/Browser/Playlist/Controllers/PlaylistListViewController+TableViewDelegate.swift
> +        shareAction.backgroundColor = #colorLiteral(red: 0.1764705926, green: 0.4980392158, blue: 0.7568627596, alpha: 1)
This colour was made up by me :( There is no design for it, so I chose one sort of in-between existing colours but one that would stand out enough on the swipe menu, and be colour blind friendly.

2021-10-04 19:42 UTC, iccub approved these changes
Code looks good to me, we waiting on a final blue color for the button we added

2021-10-05 08:01 UTC, merged