Add custom gestural popover for future menu UI
brave/brave-ios pull request #42
Opened 2018-05-29 19:43 UTC by kylehickinson

Also adds `facebook/pop` library back into Cartfile

2018-05-29 19:43 UTC, kylehickinson commented
I'll rebase this branch once #40 is merged

2018-05-29 21:44 UTC, kylehickinson commented
Rebased

2018-05-30 14:55 UTC, jhreis requested changes
Not knowing the pop API well, it is a bit difficult to understand the context of some of this. Namely, the usage of CGFloat instead of Float, or some of the forced unwrappings used to get around Obj-C limitations. 

A few changes, but mostly some questions. Looks really solid, exciting to get this in.

2018-05-30 14:55 UTC, jhreis commented on Client/Extensions/POPExtensions.swift
> +//
Update copyright on file.

2018-05-30 14:55 UTC, jhreis commented on Client/Frontend/Popover/PopoverContainerView.swift
> +//
Update copyright on file.

2018-05-30 14:55 UTC, jhreis commented on Client/Frontend/Popover/PopoverContentComponent.swift
> +//
Update copyright on file.

2018-05-30 14:55 UTC, jhreis commented on Client/Helpers/BasicAnimationController.swift
> +//
Update copyright on file.

2018-05-30 14:55 UTC, jhreis commented on Client/Helpers/BasicAnimationController.swift
> +  private(set) weak var delegate: BasicAnimationControllerDelegate?
Can't this be a `let` as well, since it is only settable via the constructor?

2018-05-30 14:55 UTC, jhreis commented on Client/Extensions/POPExtensions.swift
> +    if pop_animationKeys() != nil {
This needed because of obj-c interface? I would think this would just be treated as a non-optional/optional.

2018-05-30 14:55 UTC, jhreis commented on Client/Extensions/POPExtensions.swift
> +  private func animate<T>(type: T.Type,
`type` here creates the `T` inference, but I think we can remove `type` if we just create the animation with a subclass:

instead of:
`animate(type: POPSpringAnimation.self, property: property, key: key, animation)`

use:
`POPSpringAnimation(property: property, key: key, animation)`

This would then receive generic inference from the constructor instead of a passed in param. Maybe I'm simplifying this too much, but worth looking at.

2018-05-30 14:55 UTC, jhreis commented on Client/Frontend/Popover/PopoverContainerView.swift
> +            backgroundView.backgroundColor = PopoverUX.backgroundColor
Thoughts about putting this all in `init` as opposed to `lazy vars` when creating the actual view?

2018-05-30 14:55 UTC, jhreis commented on Client/Frontend/Popover/PopoverContainerView.swift
> +            switch arrowDirection {
```
let yPosition = clampedArrowYOrigin == .down ? contentRect.size.height - 1.0 : 1.0
triangleLayer.position = CGPoint(x: clampedArrowXOrigin, y: clampedArrowYOrigin)
```

IMO nicer than a full switch statement. Maybe not quite as clear, since it only allows for two directions (treating .down/.up as binary).

2018-05-30 14:55 UTC, jhreis commented on Client/Extensions/POPExtensions.swift
> +      return pop_animationKeys().map { String(describing: $0) }
Not exactly sure what this is spitting out, but may want to consider using a `flatMap`, and `$0.description` is probably equivalent to the String(describing:) API.

2018-05-30 16:24 UTC, kylehickinson commented on Client/Extensions/POPExtensions.swift
> +//
Whoops, yeah sorry will do for all the files. I assume it needs to be:

```
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */
```

Correct?

2018-05-30 16:27 UTC, kylehickinson commented on Client/Helpers/BasicAnimationController.swift
> +  private(set) weak var delegate: BasicAnimationControllerDelegate?
You can't use `let` with `weak`. If I change it to `let`, won't `delegate` retain its parent causing a retain cycle?

2018-05-30 16:30 UTC, kylehickinson commented on Client/Extensions/POPExtensions.swift
> +    if pop_animationKeys() != nil {
Currently its not used, but I put it in there because pop isn't very Swift friendly and imports `pop_animationKeys` as `[Any]!` instead of `[String]`. 

This is simply a helper to get type-safe/nil-safe animation keys.

2018-05-30 16:35 UTC, kylehickinson commented on Client/Extensions/POPExtensions.swift
> +  private func animate<T>(type: T.Type,
I could do this, but in the end it may not use the typed animation created because it first checks to see if the animation is running using `key` at L47

2018-05-30 17:17 UTC, kylehickinson commented on Client/Frontend/Popover/PopoverContainerView.swift
> +            switch arrowDirection {
Yeah I could do this, originally I used switches for all in case we ever add left/right arrow directions. Since then it would give warnings for non-exhaustive switches everywhere we check it

2018-05-30 17:20 UTC, jhreis commented on Client/Extensions/POPExtensions.swift
> +  private func animate<T>(type: T.Type,
You would still have the `key` though, and also the generic type `T`, I just meant, that T can then be inferred by the instantiation class rather than the type being passed in. Since we don't use `type`, it is currently just being used to give the generic `T` a type. This could also be done by casting `T` to `type`

L47 for example could be using `as? type` as `type` and `T` are equivalent.

2018-05-30 17:21 UTC, jhreis commented on Client/Helpers/BasicAnimationController.swift
> +  private(set) weak var delegate: BasicAnimationControllerDelegate?
Ah, I did not know that. Interesting limitation.

2018-05-30 17:23 UTC, jhreis commented on Client/Extensions/POPExtensions.swift
> +    if pop_animationKeys() != nil {
If it is `[Any]!` almost certain it can't be `nil` without a forced unwrapping crash. Since accessing `pop_animationKeys()` would be forced unwrapped due to accessor type, I think it would would never even reach the equality check. Do you think this is not the case though?

2018-05-30 17:24 UTC, jhreis commented on Client/Frontend/Popover/PopoverContainerView.swift
> +            switch arrowDirection {
Gotcha, I think either is fine. Lots of 2 use switches, but probably not a huge issue. It is clear at least.

2018-05-30 17:27 UTC, kylehickinson commented on Client/Frontend/Popover/PopoverContainerView.swift
> +            backgroundView.backgroundColor = PopoverUX.backgroundColor
Do you mean like:

```swift
let backgroundView: UIView = {
    let view = UIView()
    view.backgroundColor = PopoverUX.backgroundColor
    view.layer.cornerRadius = PopoverUX.cornerRadius
    view.layer.shadowColor = PopoverUX.shadowColor.cgColor
    view.layer.shadowOffset = PopoverUX.shadowOffset
    view.layer.shadowRadius = PopoverUX.shadowRadius
    view.layer.shadowOpacity = PopoverUX.shadowOpacity
    view.translatesAutoresizingMaskIntoConstraints = false
    return view
}()
```

edit:
I actually prefer property setup at declaration. I am used to using [Then.swift](https://github.com/devxoul/Then), which makes it a bit easier to write.

Thoughts on using Then vs the manual way above?

2018-05-30 17:34 UTC, kylehickinson commented on Client/Extensions/POPExtensions.swift
> +    if pop_animationKeys() != nil {
Hmm you make a good point, but I'm fairly certain I've had this crash on me in the past in previous uses... For now I'm going to remove this entirely and if we need something in the future we can check it out again :)

2018-05-31 20:55 UTC, jhreis approved these changes

2018-05-31 20:55 UTC, merged