Fix #4208 - Reader-Mode Flaw
brave/brave-ios pull request #4209
Opened 2021-09-22 16:18 UTC by Brandon-T

## Summary of Changes

This pull request fixes #4208

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
- In the Hacker-One ticket. Since this is a flaw, we don't want it public, even though the severity is very low from what I can tell, as you have to break your own website to execute this.
- See Here: https://bravesoftware.slack.com/archives/G2KN13Z8C/p1632269939058200?thread_ts=1632267649.056500&cid=G2KN13Z8C

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2021-09-22 16:20 UTC, soner-yuksel approved these changes

2021-09-22 17:14 UTC, iccub requested changes

2021-09-22 17:14 UTC, iccub commented on Client/Frontend/UserContent/UserScripts/MainFrame/AtDocumentStart/ReaderMode.js
> +        readabilityResult.title = readabilityResult.title;
does it do anything now? left and right side are the same

2021-09-23 17:47 UTC, diracdeltas approved these changes

2021-09-23 19:30 UTC, iccub approved these changes

2021-09-23 19:55 UTC, jumde approved these changes

2021-09-24 12:51 UTC, merged