Nobug/tab tray refactor
brave/brave-ios pull request #4210
Opened 2021-09-22 16:51 UTC by iccub

## Summary of Changes

This pull request fixes #<number>

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2021-10-21 11:36 UTC, iccub commented on Client/Frontend/Browser/Tab Tray/TabTrayController2.swift
> +class TabTrayController2: UIViewController {
Once approved is ready i will rename it to `TabTrayController`, this is new file so did not want it to mess with the old tab tray vc class

2021-10-21 11:37 UTC, iccub commented on Client/Frontend/Browser/Tab Tray/TabTrayController2.swift
> +    func accessibilityScrollStatus(for scrollView: UIScrollView) -> String? {
This implementation is 100% taken from the old class

2021-10-21 11:52 UTC, iccub commented on Client/Frontend/Browser/Tab Tray/TabTrayView.swift
> +    class View: UIView {
this is old implementation as well

2021-10-28 20:41 UTC, Brandon-T commented
1. Open NTP.
2. Tap on Favourites (Wikipedia).
3. BEFORE it finishes loading, open another tab quickly.
4. Open Tab-Tray.
5. Screenshot is blank for Wikipedia.
6. Close Tab-Tray and go to Wikipedia Tab.
7. Wikipedia finishes loading.
8. Switch to the New Tab.
9. Open Tab-Tray.
10. Screenshot is still blank (it didn't update).

If you open Tab-Tray on wikipedia tab, screenshot updates just fine.

2021-10-28 20:52 UTC, Brandon-T requested changes
Crashes when opening multiple tabs (more than 3.. IE: 4, 5).
Switching tabs quickly seems to cause it. 
Before it finishes switching the tab, open tab-tray.
**Info sent in Slack.**

2021-10-29 20:01 UTC, Brandon-T approved these changes

2021-10-30 11:23 UTC, merged