[needsuplift] Fix #430: Fix NSKeyedArchiver/NSKeyedUnarchiver deprecation warnings
brave/brave-ios pull request #431
Opened 2018-11-21 04:23 UTC by Liunkae

This fixes the NSKeyedArchiver/NSKeyedUnarchiver deprecation warnings, as shown in #430.

## Pull Request Checklist

- [ ] My patch has gone through review and I have addressed review comments
- [x] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

- [x] I have updated the *Unit Tests* to cover new or changed functionality
- [x] I have updated the *UI Tests* to cover new or changed functionality
- [x] I have marked the bug with `[needsuplift]`
- [x] I have made sure that localizable strings use `NSLocalizableString()`

2018-11-21 21:29 UTC, kylehickinson requested changes
Thanks for grabbing this :)

2018-11-21 21:29 UTC, kylehickinson commented on BraveShared/Analytics/UserReferralProgram.swift
> +                    } catch {}
Can you add an error here?

```suggestion
                    } catch {
                        log.error("Failed to save URP custom header data \(headers) with error: \(error.localizedDescription)")
                    }
```

2018-11-21 21:29 UTC, kylehickinson commented on BraveShared/Analytics/UserReferralProgram.swift
> +            } catch {}
Same as above

2018-11-23 16:33 UTC, Liunkae commented on BraveShared/Analytics/UserReferralProgram.swift
> +                    } catch {}
Will do.

2018-11-23 23:25 UTC, cndouglas commented
@kylehickinson I added error handling as requested.

2018-11-24 00:57 UTC, kylehickinson approved these changes

2018-11-24 00:57 UTC, kylehickinson commented
Thanks again @Liunkae!

2018-11-24 00:57 UTC, merged