Fix #4308: Fix all Session Restore, Reader-Mode, GCDWebServer issues
brave/brave-ios pull request #4325
Opened 2021-10-15 01:43 UTC by Brandon-T

## Info:
- Fix all session restore, reader-mode, error page, certificate error page, etc. bugs.
- Used InternalURL and fix PrivilegedRequest.
- Get rid of most of GCDWebServer code.

## Summary of Changes
- Use `InternalURL`
- Use `PrivilegedRequest` which uses `InternalURL`
- Remove most `GCDWebServer` handlers to use `WKURLSchemeHandler` instead
- Update ErrorPage HTML and CSS
- Update NetCert HTML and CSS
- Update SessionRestore HTML
- Rewrote all Interstitial pages
- Update SessionData and SavedTab to handle persistent private mode (though, not enabled yet)
- Added migration `SessionData.updateSessionURLs` to migrate session restore URLs to use the proper schemes instead of (`GCDWebServer` schemes && `localhost`).

- **TODO**: Update Unit Tests!! (Help wanted :))

This pull request fixes #4308

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
- Test Reader-Mode
- Test Session Restore
- Test Session Restore of Japanese website with Kanji or Katakana characters in the URL
- Test Session Restore of multiple tabs
- Test About Home page
- Test About License page
- Test Error Pages like on `gsdgsdglkangajkngkalngakgdaga.com` or random website.
- Test Error Pages on bad certificate website like: `https://expired.badssl.com/`
- Test Error Pages when there is no network (turn on airplane mode).

## Screenshots:

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

2021-10-15 12:36 UTC, Brandon-T commented
Added Interstitial Pages:

<img src="https://user-images.githubusercontent.com/1530031/137487684-a2243bf8-7422-41c3-993b-f037e657ccc3.png" width="200" height="434"> <img src="https://user-images.githubusercontent.com/1530031/137487685-e0c6fd96-d308-4eee-a353-c54cabccc24f.png" width="200" height="434"> <img src="https://user-images.githubusercontent.com/1530031/137487687-b566217f-bf40-453a-8ad1-a898d045eeec.png" width="200" height="434"> <img src="https://user-images.githubusercontent.com/1530031/137488395-1d5658dc-2bce-42ab-a73e-7d5f531138b1.png" width="200" height="434">
<img src="https://user-images.githubusercontent.com/1530031/137496704-db44e4b4-a744-4519-9b2d-9a1b73ebd3ba.png" width="200" height="434">

2021-10-18 16:03 UTC, iccub requested changes
left few questions and nitpicks, will run this branch later for functional review

2021-10-18 16:03 UTC, iccub commented on Client/Application/Delegates/AppDelegate.swift
> +        guard !server.server.isRunning else { return }
I like `if server.server.isRunning { return }` more, more readable imo

2021-10-18 16:03 UTC, iccub commented on Client/Application/Delegates/AppDelegate.swift
> +            [ (AboutHomeHandler.path, AboutHomeHandler()),
Extra space after `[` character

2021-10-18 16:03 UTC, iccub commented on Client/Application/Delegates/AppDelegate.swift
> +        BookmarksInterstitialPageHandler.register(server) //TODO: PORT TO InternalSchemeHandler
Are these todos still needed?

2021-10-18 16:03 UTC, iccub commented on Client/Frontend/Browser/BrowserTrayAnimators.swift
> +            return InternalURL(url)?.isAboutURL ?? false
maybe convert to `InternalURL(url)?.isAboutURL == false`

2021-10-18 16:03 UTC, iccub commented on Client/Frontend/Browser/BrowserViewController.swift
> +            showNewTabPageController()
are we sure we want this when top toolbar is in overlay mode?

2021-10-18 16:03 UTC, iccub commented on Client/Frontend/Browser/BrowserViewController.swift
> +            if (!InternalURL.isValid(url: url) || url.isReaderModeURL), !url.isFileURL {
why did you switch from about-home to reader-mode url check here?

2021-10-18 16:03 UTC, iccub commented on Client/Frontend/Browser/BrowserViewController.swift
> +            // This is a terrible workaround for a bad iOS 12 bug where PDF
i wonder if we still need it considering this comment says iOS 12 bug?

2021-10-18 16:03 UTC, iccub commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
>      /// Allow local requests only if the request is privileged.
is this comment still relevant?

2021-10-18 16:03 UTC, iccub commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
> +                !(InternalURL(url)?.isSessionRestore ?? false),
convert to `== false`

2021-10-18 16:03 UTC, iccub commented on Client/Frontend/Browser/MetadataParserHelper.swift
> +//                TabEvent.post(.pageMetadataNotAvailable, for: tab)
do we use those tab events?

2021-10-18 16:03 UTC, iccub commented on Client/Frontend/Browser/SessionData.swift
> +                // TODO: handle reader pages ("http://localhost:6571/reader-mode/page?url=", "\(InternalScheme.url)/\(ReaderModeHandler.path)?url=")
this is for future reader mode work I assume?

2021-10-18 16:03 UTC, iccub commented on Client/Frontend/Browser/SessionRestoreHelper.swift
> +            if params["name"] as! String == "didRestoreSession" {
can we safely cast it?

2021-10-18 16:03 UTC, iccub commented on Client/Frontend/Browser/Tab.swift
> +        if let url = self.url, InternalURL(url)?.isAboutHomeURL ?? false, sessionData == nil, !restoring {
convert to `== false`

2021-10-18 16:03 UTC, iccub commented on Client/Frontend/Browser/TabManager.swift
> +                return url.isWebPage() && !(InternalURL(url)?.isAboutHomeURL ?? false)
convert to `== false`

2021-10-18 16:03 UTC, iccub commented on Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift
> +                if let url = tab.url, url.isWebPage(), !(InternalURL(url)?.isAboutHomeURL ?? false) {
convert to `== false`

2021-10-18 16:03 UTC, iccub commented on Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift
> +                    if let urlString = fetchedTab?.url, let url = URL(string: urlString), url.isWebPage(), !(InternalURL(url)?.isAboutHomeURL ?? false) {
convert to `== false`

2021-10-18 16:03 UTC, iccub commented on Shared/Extensions/URLExtensions.swift
> +        return aboutComponent?.hasPrefix("home") ?? false
convert to `== false`

2021-10-18 16:12 UTC, Brandon-T commented on Client/Application/Delegates/AppDelegate.swift
> +        BookmarksInterstitialPageHandler.register(server) //TODO: PORT TO InternalSchemeHandler
Yeah they are. They can stay for now because `reader-mode` and the safebrowsing and interstitial handlers are still using GCDWebServer.

2021-10-18 16:13 UTC, Brandon-T commented on Client/Frontend/Browser/BrowserTrayAnimators.swift
> +            return InternalURL(url)?.isAboutURL ?? false
Doesn't work if I do that. `InternalURL(url)` returns nil and when I do `isAboutURL` on it, it returns `Optional(nil)`. So `nil == false` returns false :(

https://github.com/brave/brave-ios/pull/4325#discussion_r731104547

2021-10-18 16:16 UTC, Brandon-T commented on Client/Frontend/Browser/BrowserViewController.swift
> +            if (!InternalURL.isValid(url: url) || url.isReaderModeURL), !url.isFileURL {
This check is checking specifically if the URL is NOT `errorPage` or `aboutHome` or `fileURL`.
The content of the `if-statement` runs `webView.evaluateSafeJavaScript(functionName: "\(ReaderModeNamespace).checkReadability"` which is only valid on a reader-mode page. Error page and about home should not support `reader-mode`.

So the check should actually be only if it is a reader-mode page or regular page.
So it is correct. The URL must not be a `valid` internal URL (regular page), OR it must be a valid reader-mode page.

2021-10-18 16:16 UTC, Brandon-T commented on Client/Frontend/Browser/BrowserViewController.swift
> +            // This is a terrible workaround for a bad iOS 12 bug where PDF
It is needed for iOS 12+.

2021-10-18 16:17 UTC, Brandon-T commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
>      /// Allow local requests only if the request is privileged.
Yes, it is valid. I'll update it to be a better comment.

2021-10-18 16:21 UTC, Brandon-T commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
> +                !(InternalURL(url)?.isSessionRestore ?? false),
That won't work. Try it in a playground:

```swift
import Foundation

class OptionalInit {
    init?() {
        return nil
    }

    var whatever: Bool {
        return false
    }
}

print(OptionalInit()?.whatever == false)
```

If it prints `false` it won't work. The `optional` returns `Optional(nil)` not `false`. So `Optional(nil) == false` returns `false` :(

2021-10-18 16:21 UTC, Brandon-T commented on Client/Frontend/Browser/MetadataParserHelper.swift
> +//                TabEvent.post(.pageMetadataNotAvailable, for: tab)
We don't have those added yet, but we can add them later. This class will need refactoring.

2021-10-18 16:22 UTC, Brandon-T commented on Client/Frontend/Browser/SessionData.swift
> +                // TODO: handle reader pages ("http://localhost:6571/reader-mode/page?url=", "\(InternalScheme.url)/\(ReaderModeHandler.path)?url=")
Yeah :) It is for when we move reader-mode to `WKURLSchemeHandler` instead of GCDWebServer.

2021-10-18 16:22 UTC, iccub commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
> +                !(InternalURL(url)?.isSessionRestore ?? false),
okay, ignore my other comments about it then, posted few of them :o

2021-10-18 16:23 UTC, Brandon-T commented on Client/Frontend/Browser/Tab.swift
> +        if let url = self.url, InternalURL(url)?.isAboutHomeURL ?? false, sessionData == nil, !restoring {
https://github.com/brave/brave-ios/pull/4325#discussion_r731104547

2021-10-18 16:23 UTC, Brandon-T commented on Client/Frontend/Browser/TabManager.swift
> +                return url.isWebPage() && !(InternalURL(url)?.isAboutHomeURL ?? false)
https://github.com/brave/brave-ios/pull/4325#discussion_r731104547

2021-10-18 16:23 UTC, Brandon-T commented on Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/Bookmarks/AddEditBookmarkTableViewController.swift
> +                if let url = tab.url, url.isWebPage(), !(InternalURL(url)?.isAboutHomeURL ?? false) {
https://github.com/brave/brave-ios/pull/4325#discussion_r731104547

2021-10-26 13:20 UTC, iccub approved these changes
I ran some tests and all works for me :)

2021-10-26 15:28 UTC, merged