Fix: # 4272 Buy Crypto UI. Integrated with searching, input, updates
brave/brave-ios pull request #4327
Opened 2021-10-15 20:32 UTC by nuo-xu

## Summary of Changes
This pr is building the Buy screen in iOS wallet.

- Buy Screen UI 
- Account picker integration
- Token search screen the integration
- User input for dollar amount 
- fetch buy url when press the buy button
- `BraveWallet.ERCToken` now using `symbol` as id

This pull request fixes #<number>

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

![simulator_screenshot_429D105B-3112-4205-AAA8-2747A1F24C5C](https://user-images.githubusercontent.com/1187676/137549756-8089f223-cb2d-4652-b7fa-43e1db97bd48.png)
![simulator_screenshot_92C9DC12-0B94-4A22-8B8C-75C74995F01B](https://user-images.githubusercontent.com/1187676/137549776-c6298d27-15bb-4543-b50c-e408302122a7.png)

## Review Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2021-10-15 20:44 UTC, kylehickinson requested changes

2021-10-15 20:44 UTC, kylehickinson commented on BraveWallet/Crypto/Search/BuyTokenSearchView.swift
> +    .listStyle(InsetGroupedListStyle())
This ListStyle should be applied to `TokenList`

2021-10-15 20:44 UTC, kylehickinson commented on BraveWallet/Crypto/Search/TokenListView.swift
> +struct TokenList<Content: View>: View {
`TokenList` is a good name, we should rename the file `TokenListView.swift` to `TokenList.swift`

2021-10-15 20:44 UTC, kylehickinson commented on BraveWallet/Crypto/Search/TokenListView.swift
> +        }
Remind me to make an extension for this 😂 Its gonna be used over and over again

2021-10-15 20:44 UTC, kylehickinson commented on BraveWallet/Crypto/Search/TokenListView.swift
> +          }
`Group` not needed here

2021-10-15 20:44 UTC, kylehickinson commented on BraveWallet/Crypto/Search/TokenListView.swift
> +    TokenList(tokens: Self.testTokens) { token in
`Self` probably not needed here

2021-10-15 20:44 UTC, kylehickinson commented on BraveWallet/Crypto/Stores/BuyTokenStore.swift
> +  private let keyringController: BraveWalletKeyringController
`keyringController` isn't used at all, can be removed

2021-10-15 20:44 UTC, kylehickinson commented on BraveWallet/Crypto/Stores/WalletStore.swift
> +      tokenRegistry: tokenRegistry)
nit: closing parentheses on new line

2021-10-15 20:44 UTC, kylehickinson commented on BraveWallet/WalletStrings.swift
> +      value: "Amount in USD",
This shouldn't be specific to USD, since it'll eventually be used for users specific currency.

So we should do `amountInCurrency`, with the value `Amount in %@`

2021-10-15 20:44 UTC, kylehickinson commented on BraveWallet/WalletStrings.swift
> +      comment: "The textFiled's placeholder for users to input dollar value of the crypto they want to buy"
typo :)

2021-10-15 20:44 UTC, kylehickinson commented on BraveWallet/Crypto/BuySwapSwap/BuyTokenView.swift
> +            Text("$")
Can you open a follow-up ticket to ensure we localize this `$` which may not apply to all currencies. Perhaps the UI itself will change to just show "USD"/"CAD"/"EUR"/etc. on the right-side of the text field

2021-10-15 20:44 UTC, kylehickinson commented on BraveWallet/WalletStrings.swift
> +      comment: "The title of the button for users to click when they are ready to buy"
Perhaps want to mention that `Wyre` is a product

2021-10-15 20:46 UTC, kylehickinson commented on BraveWallet/Crypto/Search/TokenListView.swift
> +    .listRowBackground(Color(.secondaryBraveGroupedBackground))
This is on the wrong view, should be on the `Section` one line above

2021-10-18 14:37 UTC, nuo-xu commented on BraveWallet/Crypto/BuySwapSwap/BuyTokenView.swift
> +            Text("$")
> may not apply to all currencies

Created ticket https://github.com/brave/brave-ios/issues/4341

2021-10-18 15:22 UTC, kylehickinson requested changes

2021-10-18 15:22 UTC, kylehickinson commented on BraveWallet/WalletStrings.swift
> +      comment: "The textField's placeholder for users to input dollar value of the crypto they want to buy"
Add a bit of information about what `%@` will turn into to help translators

2021-10-18 15:22 UTC, kylehickinson commented on BraveWallet/Crypto/Search/TokenList.swift
>            .multilineTextAlignment(.center)
nit: should be re-indented now that its not applying to a trailing closure

2021-10-18 15:39 UTC, kylehickinson approved these changes

2021-10-18 15:42 UTC, merged