Fix: #4273 Built Send Crypto Screen
brave/brave-ios pull request #4380
Opened 2021-10-21 02:59 UTC by nuo-xu

## Summary of Changes
- Built Send Crypto Screen UI
- Integrated the screen with token fetching/selection/balance

This pull request fixes #4273 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Screenshots:
![simulator_screenshot_C15EAA98-BA84-4483-8060-A40AC488C9AE](https://user-images.githubusercontent.com/1187676/138203447-adc85843-4b77-4a89-9d08-f5d9e328e2a0.png)

![simulator_screenshot_9BC6C333-EE90-460A-8CC8-FE4062E83249](https://user-images.githubusercontent.com/1187676/138203497-33960f70-2b22-404c-9180-5cbaf5eccd66.png)

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2021-10-21 20:00 UTC, kylehickinson requested changes

2021-10-21 20:00 UTC, kylehickinson commented on BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift
> +  }
Don't need this as its own `@State`, it should just calculate the amount from balance and then set `amountInput`

2021-10-21 20:00 UTC, kylehickinson commented on BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift
> +                .frame(width: length, height: length)
Set a `font` on this instead, `brave.clipboard` is a custom SF Symbol so no need to make it resizable/aspect-fit/frame modifiers

2021-10-21 20:00 UTC, kylehickinson commented on BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift
> +                .renderingMode(.template)
~We should make this a custom SF symbol and them mimic `brave.clipboard`. I will get you a SVG for it~

2021-10-21 20:00 UTC, kylehickinson commented on BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift
> +          header: WalletListHeaderView(title: Text(String.localizedStringWithFormat(Strings.Wallet.sendCryptoAmountTitle, sendTokenStore.selectedSendToken?.symbol ?? ""))),
Format to next line so it fits within ~110 char column

2021-10-21 20:00 UTC, kylehickinson commented on BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift
> +          TextField(String.localizedStringWithFormat(Strings.Wallet.sendCryptoAmountPlaceholder, sendTokenStore.selectedSendToken?.symbol ?? ""), text: $amountInput)
Format to next line so it fits within ~110 char column

2021-10-21 20:00 UTC, kylehickinson commented on BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift
> +          header: HStack {
No need for `HStack`

2021-10-21 20:00 UTC, kylehickinson commented on BraveWallet/Crypto/Stores/SendTokenStore.swift
> +          } else if let index = tokens.firstIndex(where: { $0.id == selectedToken.id && $0.contractAddress != selectedToken.contractAddress }) {
`id` comparison should be enough. And you can just do `first(where: { ... })` instead of first index

2021-10-21 20:00 UTC, kylehickinson commented on BraveWallet/Crypto/Stores/SendTokenStore.swift
> +            selectedSendToken = nil
Should default to `.eth`

2021-10-21 20:00 UTC, kylehickinson commented on BraveWallet/Crypto/Stores/SendTokenStore.swift
> +  private func balance(for token: BraveWallet.ERCToken) {
rename to `fetchBalance` since there's no completion block handling you back a balance

2021-10-21 20:00 UTC, kylehickinson commented on BraveWallet/Crypto/Stores/SendTokenStore.swift
> +          self.selectedSendTokenBalance = balance
Can you mark these `selectedSendTokenBalance` setters with `// TODO: convert from wei`

2021-10-21 20:00 UTC, kylehickinson commented on BraveWallet/Crypto/Stores/SendTokenStore.swift
> +    fetchAssetBalance()
Don't think you have to re-fetch asset balance when an account is added/removed as long as the selected account still exists.  Maybe add a check here to see if selected account exists in in the keyring.accountInfos

2021-10-21 20:00 UTC, kylehickinson commented on BraveWallet/WalletStrings.swift
> +      comment: "A title above the address you want to send to."
Add additional info in the comment with an example/context similar to `sendCryptoFromTitle`

2021-10-21 20:00 UTC, kylehickinson commented on BraveWallet/WalletStrings.swift
> +      value: "Enter address or url", // TODO: Get real copy
I don't think we need a TODO on this

2021-10-21 20:00 UTC, kylehickinson commented on BraveWallet/WalletStrings.swift
> +      value: "To", // TODO: Get real copy
Don't need todo on this

2021-10-21 20:00 UTC, kylehickinson commented on BraveWallet/WalletStrings.swift
> +      value: "From", // TODO: Get real copy
Don't need todo on this

2021-10-21 20:45 UTC, kylehickinson commented on BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift
> +                .renderingMode(.template)
Turns out we have one already, its `brave.qr-code`

2021-10-22 17:07 UTC, nuo-xu commented on BraveWallet/Crypto/Stores/SendTokenStore.swift
> +            selectedSendToken = nil
> Should default to `.eth`

if userAssets is empty that means user has no asset to send? why we default it to be `.eth`?

2021-10-22 17:19 UTC, nuo-xu commented on BraveWallet/Crypto/Stores/SendTokenStore.swift
> +    fetchAssetBalance()
> Don't think you have to re-fetch asset balance when an account is added/removed as long as the selected account still exists. Maybe add a check here to see if selected account exists in in the keyring.accountInfos

I wasn't too sure what this protocol is for that's why I fetch the assets there. But after your explanation, i think fetch assets in `selectedAccountChanged` is sufficient.

2021-10-25 21:32 UTC, kylehickinson requested changes

2021-10-25 21:32 UTC, kylehickinson commented on BraveWallet/Crypto/Scanner/WalletScannerView.swift
> +    ])
use SnapKit instead

2021-10-25 21:32 UTC, kylehickinson commented on BraveWallet/Crypto/Scanner/WalletScannerView.swift
> +  }()
```
private let captureSession = AVCaptureSession().then {
  $0.sessionPreset = .high
}
```

2021-10-25 21:32 UTC, kylehickinson commented on BraveWallet/Crypto/Scanner/WalletScannerView.swift
> +    previewLayer?.frame = view.layer.bounds
call `super.viewDidLayoutSubviews`

2021-10-25 21:32 UTC, kylehickinson commented on BraveWallet/Crypto/Scanner/WalletScannerView.swift
> +      $0.translatesAutoresizingMaskIntoConstraints = false
`isAccessibilityElement = false`

2021-10-25 21:32 UTC, kylehickinson commented on BraveWallet/Crypto/Scanner/WalletScannerView.swift
> +struct WalletScannerView: UIViewControllerRepresentable {
As per conversation: do something like this

```swift
struct WalletScannerView: View {
  @Binding var address: String
  @State private var isErrorPresented: Bool = false
  @Environment(\.presentationMode) @Binding private var presentationMode
  
  var simulatorBody: some View {
    
  }
  
  var body: some View {
    NavigationView {
    #if targetEnvironment(simulator)
    Text("Unable to scan on simulator")
      .onAppear {
        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
          address = ""
          presentationMode.dismiss()
        }
      }
    #else
    _WalletScannerView(address: _address)
      .ignoresSafeArea()
      .alert()
    #endif
    }
    .toolbar {
      ToolbarItemGroup(placement: .cancellationAction) {
        Text("")
      }
    }
  }
}
```

2021-10-26 21:36 UTC, kylehickinson requested changes

2021-10-26 21:36 UTC, kylehickinson commented on BraveWallet/Crypto/Scanner/WalletScannerView.swift
> +  @Binding var toAddress: String
This could technically be re-used for any sort of address scanning, right? Maybe lets rename it to `AddressQRCodeScannerView` or something and just have the binding be `address` instead of `toAddress`

2021-10-26 21:36 UTC, kylehickinson commented on BraveWallet/Crypto/Scanner/WalletScannerView.swift
> +    NavigationView {
Can this `NavigationView` can exist outside of `#if/#else`?

2021-10-26 21:36 UTC, kylehickinson commented on BraveWallet/Crypto/Scanner/WalletScannerView.swift
> +struct _WalletScannerView: UIViewControllerRepresentable {
Make this `private`

2021-10-26 21:36 UTC, kylehickinson commented on BraveWallet/Crypto/Scanner/WalletScannerView.swift
> +  var dismiss: (() -> Void)
nit: parenthesis not needed

2021-10-26 21:36 UTC, kylehickinson commented on BraveWallet/Crypto/Scanner/WalletScannerView.swift
>  class WalletScannerViewController: UIViewController {
Make this `private`

2021-10-26 21:36 UTC, kylehickinson commented on BraveWallet/Crypto/Scanner/WalletScannerView.swift
> +    dismiss: @escaping (() -> Void)
nit: parenthesis not needed

2021-10-26 21:36 UTC, kylehickinson commented on BraveWallet/Crypto/Scanner/WalletScannerView.swift
> +  var dismiss: (() -> Void)
nit: parenthesis not needed

2021-10-26 21:36 UTC, kylehickinson commented on BraveWallet/Crypto/Scanner/WalletScannerView.swift
> +      dismiss()
This should setup a generic error, not dismiss

2021-10-26 21:36 UTC, kylehickinson commented on BraveWallet/Crypto/Scanner/WalletScannerView.swift
>      }
These can be all combined into a simpler flow

```swift
if !isFinishScanning, 
    let stringValue = (metadataObjects.first as? AVMetadataMachineReadableCodeObject)?.stringValue, 
    stringValue.isAddress {
  address = stringValue
  dismiss()
} else {
  isErrorPresented = true
}
isFinishScanning = true
```

Are we treating non-address as errors as well? Are we going to have a special error message for that?

2021-10-26 21:36 UTC, kylehickinson commented on BraveWallet/Crypto/Stores/Address.swift
> +    return clean.filter(\.isHexDigit).count == clean.count
Can be changed to `return dropFirst(2).allSatisfy(\.isHexDigit)`

2021-10-27 02:37 UTC, nuo-xu commented on BraveWallet/Crypto/Scanner/WalletScannerView.swift
> +      $0.translatesAutoresizingMaskIntoConstraints = false
> `isAccessibilityElement = false`

it's right below at 159 😀

2021-10-27 03:01 UTC, nuo-xu commented on BraveWallet/Crypto/Scanner/WalletScannerView.swift
>      }
I checked other existed scanners they don't have output validation. We can treat it as invalid data to have a popup so that user knows the scan did happen but the data is wrong.

2021-10-28 15:28 UTC, kylehickinson requested changes

2021-10-28 15:28 UTC, kylehickinson commented on BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift
> +  @ScaledMetric var recentIconLength: CGFloat = 14.0
Make these private

2021-10-28 15:28 UTC, kylehickinson commented on BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift
> +            }
For some reason when I tap this button, it shows the QR code scanner. Can you check why this happens?

2021-10-28 15:29 UTC, kylehickinson commented on BraveWallet/Crypto/BuySwapSwap/SendTokenView.swift
> +            }
Oh its because you need to give both these buttons `.buttonStyle(PlainButtonStyle())` otherwise the entire cell becomes tappable

2021-10-28 15:39 UTC, kylehickinson approved these changes

2021-10-28 16:02 UTC, merged