Fix #3398: Add ability to search history by title or URL in the history list
brave/brave-ios pull request #4403
Opened 2021-10-25 19:34 UTC by soner-yuksel

Adding Search Bar and functionality to History View Controller

## Summary of Changes

This pull request fixes #3398

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Screenshots:

https://user-images.githubusercontent.com/6643505/138905049-9fdc94ec-b020-487e-9ae0-73e8e06fca9d.MP4

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

2021-10-26 15:42 UTC, nuo-xu commented on Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
> +        isHistoryBeingSearched = false
should we invalidate the timer here as well?

2021-10-26 15:49 UTC, iccub requested changes

2021-10-26 15:49 UTC, iccub commented on Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
> +            $0.searchBar.placeholder = "Search History"
localization

2021-10-26 15:49 UTC, iccub commented on Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
> +        guard !isHistoryBeingSearched else {
convert to `if`

2021-10-27 14:08 UTC, soner-yuksel commented on Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
> +        isHistoryBeingSearched = false
Well it will be humanly not possible to this action before timer invalidates itself there :) but yes technically we have to do it.
Fix at https://github.com/brave/brave-ios/pull/4403/commits/b374acb9329308b2ba1fa5be0a7aceb589678db6

2021-10-27 14:08 UTC, soner-yuksel commented on Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
> +            $0.searchBar.placeholder = "Search History"
Fix at https://github.com/brave/brave-ios/pull/4403/commits/b374acb9329308b2ba1fa5be0a7aceb589678db6

2021-10-27 14:09 UTC, soner-yuksel commented on Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
> +        guard !isHistoryBeingSearched else {
Change at https://github.com/brave/brave-ios/pull/4403/commits/b374acb9329308b2ba1fa5be0a7aceb589678db6

2021-10-27 14:22 UTC, nuo-xu approved these changes

2021-10-28 11:29 UTC, iccub commented on Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
> +    private var isHistoryBeingSearched: Bool = false
`Bool` can be removed

2021-10-28 11:29 UTC, iccub commented on Client/Frontend/Sync/BraveCore/History/HistoryFetchers.swift
> +        historyAPI?.search(withQuery: withQuery, maxCount: 200, completion: { [weak self] historyNodeList in
Could we make search to work past 200 entries limit? this might be helpful when looking for very old entries

2021-10-28 13:34 UTC, iccub approved these changes

2021-10-28 14:01 UTC, soner-yuksel commented on Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/HistoryViewController.swift
> +    private var isHistoryBeingSearched: Bool = false
Fix at https://github.com/brave/brave-ios/pull/4403/commits/448a3e698ff0a522b553d70ed28be974a064b8fe

2021-10-28 14:02 UTC, soner-yuksel commented on Client/Frontend/Sync/BraveCore/History/HistoryFetchers.swift
> +        historyAPI?.search(withQuery: withQuery, maxCount: 200, completion: { [weak self] historyNodeList in
Yeah this will actually bring 200 entries for the search query so it should be fine.

2021-10-28 15:17 UTC, merged