Fix: #4466 - Add Release Notes for 1.32.1
brave/brave-ios pull request #4467
Opened 2021-11-04 14:45 UTC by srirambv

## Summary of Changes

This pull request fixes #4466

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:

NA

## Screenshots:

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [X] Issue and pull request is assigned to a milestone (should happen at merge time).

2021-11-04 15:11 UTC, iccub approved these changes

2021-11-09 04:36 UTC, kjozwiak requested changes

2021-11-09 04:36 UTC, kjozwiak commented on CHANGELOG.md
> +- Added CarPlay support for playlist. ([#3673](https://github.com/brave/brave-ios/3673))
nit: should capitalize `playlist` -> `Playlist` as we're referring to the feature itself in this instance.

2021-11-09 04:36 UTC, kjozwiak commented on CHANGELOG.md
> +- Added a new section in history for entries older than last month. ([#4040](https://github.com/brave/brave-ios/4040))
nit: should add `browsing history` to be more specific. Just mentioning `history` could be anything without context.

2021-11-09 04:36 UTC, kjozwiak commented on CHANGELOG.md
> +- Added an option to disable "Add to playlist" button in toolbar.  ([#4234](https://github.com/brave/brave-ios/4234))
nit: there's a double space between the issue description and link.

2021-11-09 04:36 UTC, kjozwiak commented on CHANGELOG.md
> +- Implemented 'Bookmark all tabs' feature. ([#4132](https://github.com/brave/brave-ios/4132))
nit: use `"` or the CHANGELOG will get formatted. We usually don't use the `formatting` but use "formatting".

2021-11-09 04:36 UTC, kjozwiak commented on CHANGELOG.md
> +- Fixed app freeze when Rewards are enabled. ([#3941](https://github.com/brave/brave-ios/3941))
nit: something like the following would sound a bit better:

```
Fixed app freeze when enabling rewards.
```

2021-11-09 04:36 UTC, kjozwiak commented on CHANGELOG.md
> +- Fixed favorites title when there are no favorites. ([#4128](https://github.com/brave/brave-ios/4128))
hmmm maybe adding a bit more context? For example:

```
 - Removed the "Favorites" title in absence of any favorites under New Tab Page when focusing on URL bar
```

2021-11-09 17:00 UTC, kjozwiak approved these changes
LGTM 👍 Awesome work.

2021-11-09 18:41 UTC, merged

2021-11-09 18:43 UTC, kjozwiak commented
@srirambv merged so I can get the ones for `1.32.2` created 👍 Mind updating https://github.com/brave/brave-ios/releases/tag/untagged-d376a299cb09f299baa8 whenever you get the chance? Thanks sir!

2021-11-10 06:00 UTC, srirambv commented
@kjozwiak its done. Sorry for the delay in updating the releases

2021-11-10 17:03 UTC, kjozwiak commented
> @kjozwiak its done. Sorry for the delay in updating the releases

no worries 👍 Thanks for getting the notes done! I'll get the `1.32.2` notes created which are really small so shouldn't take too long.