Fix #4677: Prefill default buy/send/swap token if user comes from token details screen
brave/brave-ios pull request #4756
Opened 2021-12-20 22:07 UTC by nuo-xu

This pull request fixes #4677 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2021-12-20 23:01 UTC, soner-yuksel commented
BraveWalletTests are failing.

2021-12-21 02:46 UTC, kylehickinson requested changes

2021-12-21 02:46 UTC, kylehickinson commented on BraveWallet/Crypto/BuySendSwap/BuySendSwapDestination.swift
> +  case swap(BraveWallet.ERCToken? = nil)
If all of these take the same arg, it doesn't make sense to use an enum w/ associated value. Better to keep `BuySendSwapDestination` the same and put it inside a container `struct` i.e.

```swift
struct BuySendSwapDestination: Identifiable, Equatable, Hashable {
   enum Kind: Identifiable, CaseIterable, Equatable, Hashable { case buy, send, swap }
   var kind: Kind
   var initialToken: BraveWallet.ERCToken?
   var id: String { kind.id }
}
```

2021-12-21 16:27 UTC, nuo-xu commented
> BraveWalletTests are failing.

fixed the unit tests :)

2021-12-21 16:52 UTC, kylehickinson requested changes
1. Maybe add some unit tests for prefilled tokens to ensure the selected tokens are correct.
2. If a user taps "buy" from a token that doesn't exist in the buy list supported by Wyre don't we need some sort of validation there before setting it as the `selectedBuyToken`?

2021-12-21 19:33 UTC, nuo-xu commented
> 
hey @kylehickinson 
1. I will add unit tests to test prefilled tokens
2. This is clearly mobile only UX problem since desktop has no such flow that you click into token details and then go to buy token from there. So on desktop, the panel will only give you a list of Wyre supported tokens from `TokenRegistery.buyTokens`. I've tried this case on the current mobile flow(I added a random ERC20 token to my visible assets and try to buy this token from the token details screen), since the buy url is generated using account address and the token symbol, the url is still valid with website UI also makes sense. It is just going to be impossible for you to buy this token. I think this is acceptable behaviour for now.
Screenshot: 
![IMG_87611756725F-1](https://user-images.githubusercontent.com/1187676/146987056-f2afdb9c-b7c5-49e1-8598-7c680ff668e1.jpeg)

2021-12-21 20:42 UTC, Brandon-T requested changes

2021-12-21 20:42 UTC, Brandon-T commented on BraveWallet/Crypto/Stores/SwapTokenStore.swift
> +          if let fromToken = selectedFromToken, fromToken.symbol.uppercased() == "BAT" {
Maybe store `BAT` and `DAI` as constants somewhere?

2022-01-04 21:28 UTC, kylehickinson approved these changes

2022-01-10 11:05 UTC, iccub commented
Needs test plan

2022-01-12 19:50 UTC, nuo-xu commented
> Needs test plan

Test plan added

2022-01-12 19:59 UTC, Brandon-T approved these changes

2022-01-12 21:27 UTC, merged