Fix #4841: Restore transformation-style tab tray animation
brave/brave-ios pull request #4842
Opened 2022-01-11 18:30 UTC by kylehickinson

## Summary of Changes

This pull request fixes #4841

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

- Access the tab tray as usual from the browser
- Add new tabs until the number of tabs exceeds the on-screen space
- Verify that tabs transform correctly even when the tab would be off-screen initially (and vice-versa tapping on a partially off-screen tab, or tapping done while selected tab is off-screen)
- Verify private mode acts as normal
- Verify removing all tabs acts as normal

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2022-01-11 18:31 UTC, kylehickinson commented
Improvements that could happen: Instead of taking a screenshot of the NTP/web page we should use the actual BVC and do scale + anchorPoint animations so that we are safer from screenshot & final view not matching causing a slight mismatch.

2022-01-14 15:45 UTC, iccub requested changes
iPad regressed slightly, animation works nice but only 2 tabs are shown per row,
should be 3 per row

<img width="533" alt="Zrzut ekranu 2022-01-14 o 16 42 27" src="https://user-images.githubusercontent.com/6950387/149543567-4821f97e-c2a9-4cfd-8877-fa8da9d99506.png">

2022-01-14 20:34 UTC, iccub approved these changes

2022-01-14 20:35 UTC, merged

2022-01-19 17:43 UTC, Uni-verse commented
Verification PASSED on `iPhone 12 Pro` running `iOS 15.1.1` using build `version 1.35 (22.1.14.22)`

Test Scenarios (for each device)

- Access the tab tray as usual from the browser
- Add new tabs until the number of tabs exceeds the on-screen space
- Verify that tabs transform correctly even when the tab would be off-screen initially (and vice-versa tapping on a partially off-screen tab, or tapping done while selected tab is off-screen)
- Verify private mode acts as normal
- Verify removing all tabs acts as normal

![IMG_2338](https://user-images.githubusercontent.com/17885425/150184174-2f0c31dc-dda4-4e1c-8de9-666acfc2dcb2.PNG)

https://user-images.githubusercontent.com/17885425/150184192-b4af1464-c900-4931-a278-2cf4704a0646.MP4

Verification PASSED on `iPhone X` running ` iOS 14.4.2` using build `version 1.35 (22.1.14.22)`

![IMG_2577](https://user-images.githubusercontent.com/17885425/150184880-0750a3f2-8b8f-4d05-8b6c-8522fc27216d.PNG)

https://user-images.githubusercontent.com/17885425/150184902-bf57a0e0-14a5-4e6b-8d36-318c96a6ae1c.MP4

Verification PASSED on `iPad (7th Gen)` running `iPadOS 14.4.2` using build `version 1.35 (22.1.14.22)`

![IMG_0099](https://user-images.githubusercontent.com/17885425/150185038-98eb02a4-d144-46c6-a5ba-64237a1eff1f.PNG)
![IMG_0100](https://user-images.githubusercontent.com/17885425/150185050-0b05f8e2-814b-4b00-b2b8-40f64047264e.PNG)
![IMG_0101](https://user-images.githubusercontent.com/17885425/150185060-79c03e5a-94eb-4069-ad96-40b1078e6547.PNG)