Fix #4777:  Update reset wallet to call BraveWalletService.reset
brave/brave-ios pull request #4931
Opened 2022-02-01 22:58 UTC by nuo-xu

## Summary of Changes
Core had an update to solve resetting `KeyringService` is not resetting `RpcService`.
Hence iOS side needs to update to call the correct reset.
According to bbondy, `BraveWalletService.reset` is the only one we need. ref: https://github.com/brave/brave-ios/issues/4777#issuecomment-1006113518 

This pull request fixes #4777 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2022-02-01 23:04 UTC, kylehickinson requested changes

2022-02-01 23:04 UTC, kylehickinson commented on BraveWallet/Crypto/Stores/KeyringStore.swift
> +  private let walletService: BraveWalletBraveWalletService // for wallet reset
Remove this and `reset` from `KeyringStore` and use wallet service directly in settings instead. Then use the observer to handle the logic from reset (`isOnboardingVisible`/`Self.resetKeychainStoredPassword`)

2022-02-02 03:06 UTC, nuo-xu commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift
> +                }
@kylehickinson this is what i meant - big init.

2022-02-03 16:31 UTC, kylehickinson requested changes

2022-02-03 16:31 UTC, kylehickinson commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+Menu.swift
> +                }
Remove this, add the check in SettingsViewController when deciding whether or not to add the row

2022-02-03 16:31 UTC, kylehickinson commented on BraveWallet/Crypto/Stores/CryptoStore.swift
> +
Is there any reason for this to be nil other than off screen? If not, then just make this lazy instead? `private(set) lazy var settingsStore = SettingsStore(keyringService: keyringService, walletService: walletService)` and then use directly

2022-02-03 16:31 UTC, kylehickinson commented on BraveWallet/Crypto/Stores/CryptoStore.swift
> +  }
This is no longer needed?

2022-02-03 16:51 UTC, kylehickinson commented on BraveWallet/Crypto/Accounts/AccountsHeaderView.swift
> +  var cryptoStore: CryptoStore
You can just pass `SettingsStore` in here, its going to be evaluated immediately anyways since `NavigationLink` isn't lazy

2022-02-03 18:58 UTC, kylehickinson requested changes

2022-02-03 18:58 UTC, kylehickinson commented on Client/Frontend/Settings/SettingsViewController.swift
> +        if #available(iOS 14.0, *), let settingsStore = walletSettingsStore {
Lets remove the iOS 14 check, we're 14 min now, its no longer needed

2022-02-03 18:58 UTC, kylehickinson commented on Client/Frontend/Settings/SettingsViewController.swift
> +                    self.dataSource.sections = self.sections
Redundant else clause, just move the `self.dataSource.sections = copyOfSections` outside of the scope of this branch

2022-02-03 19:05 UTC, kylehickinson approved these changes

2022-02-03 19:24 UTC, merged