No bug: Added a new attribute to handle dapps permission associate with dapps url and account addresses.
brave/brave-ios pull request #5030
Opened 2022-02-25 23:04 UTC by nuo-xu

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2022-02-28 15:03 UTC, iccub requested changes

2022-02-28 15:03 UTC, iccub commented on Data/models/Domain.swift
> +        let _context: WriteContext = isPrivateBrowsing ? .new(inMemory: true) : .new(inMemory: false)
Are wallet and dapp features supported in private browsing mode?

2022-02-28 15:03 UTC, iccub commented on Data/models/Domain.swift
> +                   wallet_permittedAccounts = [permittedAccounts, account].joined(separator: ",")
Is this how we do it on other platforms?
I feel like this is asking for trouble, what if for some reason `account` will contain a comma character,
it can be used as a sql injection in worst case, adding two accounts separated by a comma under one `account` String

Maybe store all accounts under a json then deserialize it or look for another way to store an array of data in CoreData,
I'm not in this project so maybe i'm missing something

2022-02-28 16:19 UTC, nuo-xu commented on Data/models/Domain.swift
> +        let _context: WriteContext = isPrivateBrowsing ? .new(inMemory: true) : .new(inMemory: false)
Currently, users can access to wallet in private browsing mode.

2022-02-28 16:20 UTC, kylehickinson commented on Data/models/Domain.swift
> +        let _context: WriteContext = isPrivateBrowsing ? .new(inMemory: true) : .new(inMemory: false)
Its currently in discussion but the assumption is no dapp features in private mode

2022-02-28 16:28 UTC, nuo-xu commented on Data/models/Domain.swift
> +                   wallet_permittedAccounts = [permittedAccounts, account].joined(separator: ",")
here the `account` is an eth address which is 42-char hexadecimal address.

2022-03-01 14:15 UTC, iccub commented on Data/models/Domain.swift
> +                   wallet_permittedAccounts = [permittedAccounts, account].joined(separator: ",")
Maybe add a check to verify that the 42-char hexadecimal address is indeed what is being passed in `account` argument? and to make sure no comma characters are contained in the `account` arg

Looks like simple length check and comma check should be enough to guard this code

2022-03-03 04:45 UTC, nuo-xu commented on Data/models/Domain.swift
> +                   wallet_permittedAccounts = [permittedAccounts, account].joined(separator: ",")
added additional address check at [[1295873](https://github.com/brave/brave-ios/pull/5030/commits/12958731ab4ac173ffec08d1fba9343d61470ed1)](url)

2022-03-03 04:46 UTC, nuo-xu commented on Data/models/Domain.swift
> +        let _context: WriteContext = isPrivateBrowsing ? .new(inMemory: true) : .new(inMemory: false)
removed `isPrivateBrowsing` arg at [1295873](https://github.com/brave/brave-ios/pull/5030/commits/12958731ab4ac173ffec08d1fba9343d61470ed1)

2022-03-03 09:27 UTC, iccub approved these changes
Looking good thanks :) maybe add small a comment about the `count == 42`, explaining why this hardcoded number is used

2022-03-03 15:55 UTC, merged