[WIP] Fix #2830: Add Night Mode
brave/brave-ios pull request #5082
Opened 2022-03-09 21:18 UTC by soner-yuksel

## Summary of Changes

This pull request fixes #2830

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

![test](https://user-images.githubusercontent.com/6643505/157537612-f0cde26f-36a5-4e97-85c1-e68fa42dcf0a.png)

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2022-03-13 14:58 UTC, Brandon-T approved these changes

2022-03-14 13:48 UTC, iccub commented
Blocking for now, i have design concerns over this

2022-03-16 18:58 UTC, iccub requested changes

2022-03-16 18:58 UTC, iccub commented on BraveShared/BraveStrings.swift
> +            value: "MODE",
Write it the normal way, then we can uppercase it in code

2022-03-16 18:58 UTC, iccub commented on Client/Application/ClientPreferences.swift
> +        static let nightModeEnabled = Option<Bool>(key: "general.night-mode-theme", default: false)
nitpick, key should be `general.night-mode-enabled`

2022-03-16 18:58 UTC, iccub commented on Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/MenuViewController.swift
> +    var icon: UIImage?
I don't think this has to be optional? in code below you fallback to an empty UIImage regardless

2022-03-16 18:58 UTC, iccub commented on Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/NightModeMenuButton.swift
> +        .accessibility(label: Text("Night Mode"))
we can use localized string for that, i think you simply copied from the vpn cell, for that case `Brave VPN` is not supposed to be translated at all

2022-03-16 18:58 UTC, iccub commented on Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/NightModeMenuButton.swift
> +            let toggle = Toggle("Action Toggle", isOn: isNightModeEnabledBinding)
This text should not be needed

2022-03-16 18:58 UTC, iccub commented on Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/NightModeMenuButton.swift
> +        Group {
I think you could remove the `Group` here and the separate declaration, place it like

```
Toggle("Action Toggle", isOn: isNightModeEnabledBinding)
.labelsHidden()
.toggleStyle(SwitchToggleStyle(tint: .accentColor))
```

2022-03-16 18:58 UTC, iccub commented on Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/NightModeMenuButton.swift
> +        .frame(maxWidth: .infinity, minHeight: 48.0, alignment: .leading)
`alignment` needed here?

2022-03-16 18:58 UTC, iccub commented on Client/Frontend/Browser/Toolbars/BottomToolbar/Menu/NightModeMenuButton.swift
> +        changeNightModePreference(enabled)
I think all of this mode changing logic could be removed,
instead we could add a preference observer directly to the TabManager,
and if night mode is detected we call the `NightModeHelper.setNightMode`

2022-03-16 23:29 UTC, iccub approved these changes

2022-03-16 23:45 UTC, merged

2022-04-08 03:56 UTC, TaxingAuthority commented
Is it possible to have the option for the new night mode to turn on and off with the iOS setting? As it is now the toggle stays in night mode when iOS  changes to light appearance. Thanks for all the work!