Fix #5172Adding blocklist functionality and night mode darker colors
brave/brave-ios pull request #5173
Opened 2022-03-29 20:51 UTC by soner-yuksel

## Summary of Changes

This pull request fixes #<number>

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2022-03-30 21:24 UTC, iccub requested changes
Code looks ok, found one bug, details in DM with Soner

2022-03-30 21:24 UTC, iccub commented on Client/Frontend/Browser/Tab.swift
> +  var fetchedURL: URL? {
Can you add a small comment in code what is this is getter for?

2022-03-31 20:34 UTC, soner-yuksel commented
> Code looks ok, found one bug, details in DM with Soner

The problems with Private Mode is fixed and list of website that will be locked is updated and comment is added.

2022-04-05 09:54 UTC, iccub approved these changes
Looks good and all runtime bugs are resolved

2022-04-05 09:54 UTC, iccub commented on Shared/Extensions/URLExtensions.swift
> +                    "search.brave", "wowhead"]
very nice find with the search.brave.com domain

2022-04-05 15:36 UTC, merged