No Bug: Bump BraveCore to 1.39.81 beta
brave/brave-ios pull request #5289
Opened 2022-04-26 14:34 UTC by kylehickinson

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2022-04-26 14:50 UTC, iccub approved these changes

2022-04-26 15:03 UTC, soner-yuksel requested changes
Can we hold on merging it until tomorrowy please ? I need to make some additional manual tests password sync related..

2022-04-26 20:39 UTC, Brandon-T approved these changes

2022-04-27 13:50 UTC, soner-yuksel approved these changes
Everything seems good, sorry for the delay here.

2022-04-27 15:34 UTC, merged