No bug: Wallet favicon loader/fetcher using FavIconImageRenderer
brave/brave-ios pull request #5327
Opened 2022-05-05 13:33 UTC by nuo-xu

## Summary of Changes
Using FavIconImageRenderer to access FaviconFetcher to load web image. 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2022-05-09 13:22 UTC, Brandon-T approved these changes

2022-05-09 13:42 UTC, StephenHeaps reviewed
Couple comments; might update the `fatalError` to an `assert` and merge this week while you're away. `NewSiteConnectionView` can be updated for loading state if needed before dapps build flag removed.

2022-05-09 13:42 UTC, StephenHeaps commented on BraveWallet/FaviconReader.swift
> +    fatalError()
I think we should just assert here? Then if we miss passing in the environment we'll fail to load rather than crash.

2022-05-09 13:42 UTC, StephenHeaps commented on BraveWallet/Panels/Connect/NewSiteConnectionView.swift
> +          ProgressView()
Should we use the globe image here? Or add an `isLoading` parameter and use `ProgressView` when loading, and globe when not loading & image is nil? Maybe fine on this view, but wouldn't want a loading icon on the dapp request views at least.

2022-05-10 14:57 UTC, kylehickinson requested changes

2022-05-10 14:57 UTC, kylehickinson commented on BraveWallet/FaviconReader.swift
> +public class UnimplementedFaviconRenderer: WalletFaviconRenderer {
We should make this private since we don't actually want anyone using an unimplemented version

2022-05-10 14:57 UTC, kylehickinson commented on BraveWallet/Panels/Connect/NewSiteConnectionView.swift
> +  @State private var favicon: UIImage = .init()
Not used?

2022-05-10 14:57 UTC, kylehickinson commented on BraveWallet/Panels/Connect/NewSiteConnectionView.swift
> +  @Environment(\.faviconRenderer) var renderer: WalletFaviconRenderer
Why do we fetch the environment in each view using a `FaviconReader` instead of just just reading it inside `FaviconReader`?

2022-05-10 14:57 UTC, kylehickinson commented on BraveWallet/Panels/Connect/NewSiteConnectionView.swift
> +        loader: .init(renderer: renderer)
This is going to make a new loader every time `body` is recomputed, is that intended?

2022-05-10 14:57 UTC, kylehickinson commented on Client/Frontend/Browser/Playlist/Utilities/PlaylistThumbnailUtility.swift
> +  func loadIcon(siteURL: URL, kind: FaviconFetcher.Kind = .favicon, persistent: Bool, completion: ((UIImage?) -> Void)?) {
At this point we should probably move `FaviconImageRenderer` somewhere else since its no longer used specifically to playlist

2022-05-10 14:57 UTC, kylehickinson commented on BraveWallet/FaviconReader.swift
> +}
These dont need to be public

2022-05-10 18:28 UTC, dhemp approved these changes

2022-05-10 18:32 UTC, StephenHeaps commented on BraveWallet/FaviconReader.swift
> +    fatalError()
Fixed in [80db112](https://github.com/brave/brave-ios/pull/5327/commits/80db11250caa72cdabb7d9606afabc746e5257fe)

2022-05-10 18:32 UTC, StephenHeaps commented on BraveWallet/FaviconReader.swift
> +public class UnimplementedFaviconRenderer: WalletFaviconRenderer {
Fixed in [80db112](https://github.com/brave/brave-ios/pull/5327/commits/80db11250caa72cdabb7d9606afabc746e5257fe)

2022-05-10 18:33 UTC, StephenHeaps commented on BraveWallet/FaviconReader.swift
> +}
Fixed in [80db112](https://github.com/brave/brave-ios/pull/5327/commits/80db11250caa72cdabb7d9606afabc746e5257fe)

2022-05-10 18:33 UTC, StephenHeaps commented on Client/Frontend/Browser/Playlist/Utilities/PlaylistThumbnailUtility.swift
> +  func loadIcon(siteURL: URL, kind: FaviconFetcher.Kind = .favicon, persistent: Bool, completion: ((UIImage?) -> Void)?) {
Fixed in [1b87e1c](https://github.com/brave/brave-ios/pull/5327/commits/1b87e1cfc7f56c678a416a13c5e9bed3a0ec629d)

2022-05-10 18:33 UTC, StephenHeaps commented on BraveWallet/Panels/Connect/NewSiteConnectionView.swift
> +  @Environment(\.faviconRenderer) var renderer: WalletFaviconRenderer
Fixed in [b326ad5](https://github.com/brave/brave-ios/pull/5327/commits/b326ad5c4ad6c47b6b4668b825ec9afc156bafd2)

2022-05-10 18:33 UTC, StephenHeaps commented on BraveWallet/Panels/Connect/NewSiteConnectionView.swift
> +        loader: .init(renderer: renderer)
Fixed in [b326ad5](https://github.com/brave/brave-ios/pull/5327/commits/b326ad5c4ad6c47b6b4668b825ec9afc156bafd2)

2022-05-10 19:10 UTC, kylehickinson approved these changes

2022-05-11 15:00 UTC, Brandon-T commented
Rebased onto Development.

2022-05-11 16:45 UTC, merged