Fix 5403: Close wallet panel when user goes to full screen wallet or full screen wallet settings from panel
brave/brave-ios pull request #5408
Opened 2022-05-31 17:49 UTC by nuo-xu

Changing UX: Close wallet panel when user goes to full screen wallet or full screen wallet settings from panel

This pull request fixes #5403 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`

## Test Plan:
Please refer to the issue.

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2022-05-31 18:16 UTC, kylehickinson requested changes

2022-05-31 18:16 UTC, kylehickinson commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+Wallet.swift
> +    }
Why can't this call just happen in the call above?

2022-05-31 18:16 UTC, kylehickinson commented on BraveWallet/WalletHostingViewController.swift
> +  func onFullScreenWallet(_ viewController: UIViewController)
Naming needs work, you're saying to full screen wallet but you pass an arbitrary `UIViewController`. Overall this is confusing.

2022-05-31 18:17 UTC, kylehickinson commented on BraveWallet/WalletHostingViewController.swift
> +  func onFullScreenWallet(_ viewController: UIViewController)
Also please avoid prefixing methods with "on"

2022-06-01 16:45 UTC, kylehickinson requested changes

2022-06-01 16:45 UTC, kylehickinson commented on BraveWallet/WalletHostingViewController.swift
> +  func walletPanel(_ presentWalletWithContext: PresentingContext)
Pass in the wallet panel so that you don't have to use `presentedViewController` down below:

```swift
func walletPanel(
  _ panel: WalletPanelHostingController, 
  presentWalletWithContext: PresentingContext
)
```

2022-06-01 21:26 UTC, StephenHeaps approved these changes

2022-06-01 21:52 UTC, kylehickinson approved these changes

2022-06-02 13:18 UTC, merged