Fixed #518 for migration case
brave/brave-ios pull request #599
Opened 2018-12-06 18:02 UTC by danishjafri88

Fixes a case in #518 which happens during 1.6 to 1.7 migration. Since default favs are already created their syncOrder is nil during db migration. This causes duplication in Fav screen.

## Pull Request Checklist

- [ ] My patch has gone through review and I have addressed review comments
- [ ] My patch has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!`

- [ ] I have updated the *Unit Tests* to cover new or changed functionality
- [ ] I have updated the *UI Tests* to cover new or changed functionality
- [ ] I have marked the bug with `[needsuplift]`
- [ ] I have made sure that localizable strings use `NSLocalizableString()`

## Screenshots

If your patch includes user interface changes that you would like to suggest or that you would like UX to look at, please include them here.

## Notes for testing this patch

If useful, please leave notes for QA, explaining what this patch changes and how it can be best tested and verified.

2018-12-06 18:23 UTC, kylehickinson requested changes

2018-12-06 18:23 UTC, kylehickinson commented on Client.xcodeproj/project.pbxproj
> +						DevelopmentTeam = CZ8C3324BS;
Please remove all changes to `project.pbxproj`

2018-12-06 18:23 UTC, kylehickinson commented on Client/Entitlements/FennecApplication.entitlements
> +		<string>group.com.danish.brave</string>
Please remove

2018-12-06 18:30 UTC, danishjafri88 commented on Client.xcodeproj/project.pbxproj
> +						DevelopmentTeam = CZ8C3324BS;
:) didnt uncheck these while committing. Removed

2018-12-06 19:32 UTC, kylehickinson submitted a review, later dismissed

2018-12-06 19:32 UTC, kylehickinson commented
Seems fine to me but will wait for @iccub to review as well before merging

2018-12-07 03:07 UTC, jhreis commented
This may not be needed, so please do not merge yet.

2018-12-07 21:39 UTC, jhreis commented
Thanks for this, we decided to revert back to using just the bookmark `order` property so this is not needed right now.

Refs:
https://github.com/brave/brave-ios/pull/602
https://github.com/brave/brave-ios/pull/600

2018-12-07 21:39 UTC, closed without merging