Fix #5881: Password Protection for Account Private Key
brave/brave-ios pull request #6151
Opened 2022-10-11 17:33 UTC by StephenHeaps

## Summary of Changes
- Add password protection to view an account's private key
- This PR depends on refactor in https://github.com/brave/brave-ios/pull/6149

This pull request fixes #5881

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
1. Open account details
2. Tap 'Private Key'
3. Tap biometrics button (face id / touch id) on device, confirm password is auto-filled if available
4. Tap 'Show private key' button to reveal the private key
5. Tap 'Hide private key' button to hide the private key

## Screenshots:

![private key](https://user-images.githubusercontent.com/5314553/195160525-ef9b61c3-a97a-481f-9eb5-7b6f5e1c21ea.png)

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2022-10-12 16:15 UTC, nuo-xu requested changes
Once i reveal my private key, the `Hide Private Key` button is not enabled. 
Also can you please fix the `Back` button color? Should be `.braveOrange` its broken with iOS 16 SDK

2022-10-12 18:04 UTC, StephenHeaps commented
@nuo-xu 
> Once i reveal my private key, the Hide Private Key button is not enabled.
Fixed in [d5f3ce4](https://github.com/brave/brave-ios/pull/6151/commits/d5f3ce49d712fa320636f99ff49bcb07919451c1)

> Also can you please fix the Back button color? Should be .braveOrange its broken with iOS 16 SDK
Fixed in [f4eb5e4](https://github.com/brave/brave-ios/pull/6151/commits/f4eb5e474cebb89c2e64486a037c44f82a704997)

Note: This PR can't merge until issue with account removal PR is resolved.

2022-10-17 13:13 UTC, nuo-xu approved these changes

2022-10-17 20:49 UTC, merged

2022-10-18 18:12 UTC, stoletheminerals commented
lgtm