[WIP] Fix #5722: Update user rating prompt logic
brave/brave-ios pull request #6210
Opened 2022-10-19 21:01 UTC by soner-yuksel

## Summary of Changes

This pull request fixes #5722

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2022-10-21 14:08 UTC, iccub requested changes

2022-10-21 14:08 UTC, iccub commented on Client/Frontend/Analytics/AppReviewManager.swift
> +// Copyright 2021 The Brave Authors. All rights reserved.
it's almost 2023!

2022-10-21 14:08 UTC, iccub commented on Client/Frontend/Analytics/AppReviewManager.swift
> +  /// Method for handling changes to main criteriainside the various parts in application
space between `criteriainside`

2022-10-21 14:08 UTC, iccub commented on Client/Frontend/Analytics/AppReviewManager.swift
> +  /// - Parameter mainCriteria: Type of the main Criteria
Wrong comment, should say about `subCriteria`

2022-10-21 14:08 UTC, iccub commented on Client/Frontend/Analytics/AppReviewManager.swift
> +  private let daysInUseMaxPeriod = 7
`daysInUseMaxPeriod` and `dappConnectionPeriod` can be of Timeinterval type here. just adding `days` to the number. Instead of having to call it later in code

2022-10-21 14:08 UTC, iccub commented on Sources/BraveShared/Preferences.swift
> +    public static let numberPlaylistItemsAdded =  Option<Int>(key: "review.numberBookmarksAdded", default: 0)
duplicate preference key

2022-10-21 14:08 UTC, iccub commented on Sources/BraveWallet/Extensions/AppRatingRequestAction.swift
> +// Copyright 2021 The Brave Authors. All rights reserved.
2022

2022-10-21 18:56 UTC, soner-yuksel commented on Client/Frontend/Analytics/AppReviewManager.swift
> +  private let daysInUseMaxPeriod = 7
Fixed https://github.com/brave/brave-ios/pull/6210/commits/08c4574b75a593f76483d1b298ffadc060125109

2022-10-21 18:56 UTC, soner-yuksel commented on Sources/BraveShared/Preferences.swift
> +    public static let numberPlaylistItemsAdded =  Option<Int>(key: "review.numberBookmarksAdded", default: 0)
Fixed https://github.com/brave/brave-ios/pull/6210/commits/08c4574b75a593f76483d1b298ffadc060125109

2022-10-24 11:28 UTC, stoletheminerals approved these changes

2022-10-24 11:28 UTC, stoletheminerals commented on Client/Frontend/Analytics/AppReviewManager.swift
> +  /// Method for handling changes to main criteriainside the various parts in application
Needs a space -> criteriainside

2022-10-25 16:55 UTC, soner-yuksel commented on Client/Frontend/Analytics/AppReviewManager.swift
> +  /// Method for handling changes to main criteriainside the various parts in application
Fixed at https://github.com/brave/brave-ios/pull/6210/commits/a037bf15c32bf9efff8568bdfdc64aaa19941010

2022-10-26 19:34 UTC, iccub approved these changes
Looks good approving :)
We still have to make sure QA can test this feature out, at least partially

2022-10-27 21:10 UTC, soner-yuksel commented
> Looks good approving :) We still have to make sure QA can test this feature out, at least partially

@iccub Merging the PR so I can perform the SPM target move of User Retention Items including AppReview. We can have another tiny PR for testing changes.

2022-10-27 21:11 UTC, merged