Js/improve cosmetic filters injection
brave/brave-ios pull request #6212
Opened 2022-10-20 15:47 UTC by cuba

## Summary of Changes

This pull request fixes #<number>

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2022-10-25 11:19 UTC, cuba commented on .gitignore
> -scripts/
Had to remove this otherwise we can't add any new scripts to the project

2022-10-26 18:37 UTC, Brandon-T requested changes

2022-10-26 18:37 UTC, Brandon-T commented on Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Sandboxed/SiteStateListenerScriptHandler.swift
> +        print(frameInfo)
Remove?

2022-10-26 18:37 UTC, Brandon-T commented on Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/SelectorsPollerScript.js
> +      !url.startsWith('https://'))
What if it is `./../some/path`?

2022-10-26 18:41 UTC, Brandon-T commented
`SelectorPollingScript` is sandboxed so looks good to me.

The `FrameChecker` script is not, and should access any message handlers because it is arbitrarily injected from the engine code :) I checked and didn't see any handlers registered for it, so should be alright. But if it changes in the future we should check it again.

Perhaps might be a good idea to add a comment there. Other than that, PR looks good to me.

2022-10-27 08:54 UTC, cuba commented on Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Sandboxed/SiteStateListenerScriptHandler.swift
> +        print(frameInfo)
Ahh oops

2022-10-27 08:55 UTC, cuba commented on Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/SelectorsPollerScript.js
> +      !url.startsWith('https://'))
no idea...I didn't write this

2022-10-27 09:00 UTC, cuba commented on Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Sandboxed/SiteStateListenerScriptHandler.swift
> +        print(frameInfo)
Fixed

2022-10-27 09:04 UTC, cuba commented
Well the frame checker by itself doesn't do anything. It's a general purpose script. (I was actually using it for more than just wrapping these engine scripts but had problems with browser benchmarks so I decided to modify my strategy slightly). I can add a comment but the frame check wrapper doesn't really assume anything

2022-10-27 12:19 UTC, Brandon-T approved these changes

2022-10-28 16:04 UTC, pes10k commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
> +      if mainDocumentURL != tab?.currentPageData?.mainFrameURL {
will this reset the state of cosmetic filter page data if the URL changes in a way that doesn't result in a navigation (i.e. that keeps the currnet frame)?  Im thinking of things like the History API or changing the URL fragment.

2022-10-28 16:56 UTC, iccub requested changes
One safety change requested. Other than that i run this branch for a bit and the adblocking quality is greatly improved

2022-10-28 16:56 UTC, iccub commented on Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/ScriptHandlers/Sandboxed/SiteStateListenerScriptHandler.swift
> +        let args = String(data: data, encoding: .utf8)!
can we unwrap it? this handler can get called on any website and the risk of crashing is too high

2022-10-28 17:02 UTC, iccub approved these changes
my previous comment is invalid

2022-10-31 14:43 UTC, stoletheminerals requested changes
Looks good to me, just one minor change needed.

2022-10-31 14:43 UTC, stoletheminerals commented on Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/SelectorsPollerScript.js
> +window.__firefox__.execute(function($) {
Please move this script to `../Sandboxed/`

2022-11-01 11:09 UTC, cuba commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
> +      if mainDocumentURL != tab?.currentPageData?.mainFrameURL {
no it will not change it. As long as the page doesn't change this won't change the data.

2022-11-01 11:09 UTC, cuba commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
> +      if mainDocumentURL != tab?.currentPageData?.mainFrameURL {
I hope this is ok

2022-11-01 21:57 UTC, pes10k commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
> +      if mainDocumentURL != tab?.currentPageData?.mainFrameURL {
okie dokie, sounds good.

2022-11-02 11:17 UTC, cuba commented on Client/Frontend/UserContent/UserScripts/Scripts_Dynamic/Scripts/Paged/SelectorsPollerScript.js
> +window.__firefox__.execute(function($) {
Done

2022-11-02 11:21 UTC, stoletheminerals approved these changes

2022-11-02 13:51 UTC, merged