Fix #6154: Make SolanaWeb3 interface not accessible by Pages
brave/brave-ios pull request #6264
Opened 2022-10-27 13:38 UTC by Brandon-T

## Security Review
- https://github.com/brave/security/issues/1040

## Summary of Changes
- Hide SolanaWeb3 in anonymous namespace variable only known to the Swift code by name.

The way the code works is that it generates a random UUIDv4 (we call this the namespace).
Then we inject JS code into that namespace like:

```javascript
// Global variable with random namespace name.
// Pages cannot enumerate variables so it isn't possible to know that this variable exists
// unless the page bruteforces all UUIDv4's and guesses this variable name.

let W02C00302CE624DAEAD70FDEE19594856;

__firefox__.execute(function($, $Object) {
    // Pages cannot access local scope variables or code!
    inject_our_SolanaWeb3_Javascript_Here_as_LOCAL_scope();

    // Initialize our namespace to a hardened dictionary
    W02C00302CE624DAEAD70FDEE19594856 = $({
        "solanaWeb3": $(solanaWeb3)  // Hardened solanaWeb3 local scope object
    });
});
```

Now whenever our code needs to make calls to `solanaWeb3`, we have to do:
```javascript
W02C00302CE624DAEAD70FDEE19594856.solanaWeb3.WHATEVER_HERE

// Example:
let pubKey = new W02C00302CE624DAEAD70FDEE19594856.solanaWeb3.PublicKey(...);

return pubKey;  // Maybe $(pubKey) to harden it? But not sure if objects should be mutable.
```

Any page attempting to do `new solanaWeb3.PublicKey` will find that it doesn't exist and can't be accessed since it is not in global scope. The page would have to know our UUID generated variable name.
We could proxy all calls to our `W02C00302CE624DAEAD70FDEE19594856.solanaWeb3` as well, so that all returned objects/functions/values are immutable. Just not sure that this is needed or WHY.

This pull request fixes #6154

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2022-10-27 14:55 UTC, thypon commented
A bunch of questions here:

- Is this preventing the page from enumerating the objects defined on the `window|global` and finding this specific object?
- Is it possible to redefine that particular object?
- Do we incur in any significant performance penalty proxy calling everything to that object?

2022-10-27 23:50 UTC, stoletheminerals commented
If someone wants to test dynamically don't forget to enable `isSolanaDappsEnabled` feature flag in `WalletConstants.swift`

2022-11-14 20:17 UTC, StephenHeaps reviewed
Functionality wise working great, thanks 👍 . Couple small comments to address before merging but otherwise lgtm.

2022-11-14 20:17 UTC, StephenHeaps commented on Client/Frontend/Sync/WebFilter/Bookmarks/WalletHandler.swift
> +//
Needs updated to use Brave copyright comment

2022-11-14 20:17 UTC, StephenHeaps commented on Sources/BraveWallet/WalletConstants.swift
> +  public static let isSolanaDappsEnabled: Bool = true
Fine until approved, but we should restore this to false before merging. We'll remove this flag and enable Solana Dapps by default in https://github.com/brave/brave-ios/issues/6154 with full Solana Dapps security review after this PR merges 🙂

2022-11-14 20:28 UTC, StephenHeaps commented on Client/Frontend/Sync/WebFilter/Bookmarks/WalletHandler.swift
> +//
Actually seems like this file might not be needed anymore / not in this PR?

2022-11-14 21:24 UTC, stoletheminerals commented on Client/Frontend/Browser/UserScriptManager.swift
> +      console.log(\(UserScriptManager.walletSolanaNameSpace));
Do we need this?

2022-11-15 01:19 UTC, kdenhartog commented
curious what the answers are to these questions: https://github.com/brave/brave-ios/pull/6264#issuecomment-1293649596

2022-11-22 21:41 UTC, Brandon-T commented on Client/Frontend/Browser/UserScriptManager.swift
> +      console.log(\(UserScriptManager.walletSolanaNameSpace));
Not needed.

2022-11-22 21:43 UTC, Brandon-T commented
> A bunch of questions here:
> 
> * Is this preventing the page from enumerating the objects defined on the `window|global` and finding this specific object?
> * Is it possible to redefine that particular object?
> * Do we incur in any significant performance penalty proxy wrapping everything in that object?

The page cannot enumerate the hidden solanaWeb3 object as it is local and they can't get it as it's wrapped in a UUID generated variable name which the page would take forever to guess.

The page cannot redefine that object because it doesn't know its name since it is randomly generated.

No performance penalty for wrapping it in that object.

2022-11-22 21:59 UTC, StephenHeaps reviewed
Everything working as expected for me. Just need to remove the unused `WalletHandler.swift` file.

2022-11-22 21:59 UTC, StephenHeaps commented on Client/Frontend/Sync/WebFilter/Bookmarks/WalletHandler.swift
> +//
This file is unused, should be removed if not needed

2022-11-22 22:05 UTC, StephenHeaps approved these changes

2022-11-22 22:22 UTC, StephenHeaps requested changes
Resolved in [0ff753b](https://github.com/brave/brave-ios/pull/6264/commits/0ff753b5a1880b1c8cfe42894bf14d808e12966c).

~Spoke too soon, _success_ flow for `Sign Transaction` & `Sign All Transactions (single)` are failing for me now; seems related to `solanaWeb3.Transaction` which both of `signTransaction` & `signAllTransactions` requests should return.~

1. Open pwgoom.csb.app
2. Connect and tap `Sign Transaction`
3. Tap `Continue`
4. Tap `Sign`

https://user-images.githubusercontent.com/5314553/203433063-5b423176-f6b2-4bf2-8fbf-6f3f7b0cd93f.mp4

2022-11-23 14:21 UTC, StephenHeaps approved these changes

2022-11-23 17:30 UTC, nuo-xu approved these changes
PR lgtm. Tested it with test dapp. all the requests look and being handled correctly.

2022-11-29 07:03 UTC, kdenhartog commented
> The page cannot redefine that object because it doesn't know its name since it is randomly generated.

I think I've found a way to discover the value of the object via the console, but it doesn't seem programatically accessible from my testing.
![Screenshot 2022-11-29 at 7 49 45 PM](https://user-images.githubusercontent.com/23125059/204458810-b65e6919-c525-4f6e-a366-ec8272059a90.png)

Additionally, I wasn't able to properly pollute the object either. So AFAICT this solution should be G2G. I'm going to approve. @thypon or @stoletheminerals feel free to close this one out if you're alright with the current solution as well.

2022-11-29 07:05 UTC, kdenhartog approved these changes

2022-11-29 14:02 UTC, stoletheminerals commented
> I think I've found a way to discover the value of the object via the console (note the `W5...` is the value of `UserScriptManager.walletSolanaNameSpace`), but it doesn't seem programatically accessible from my testing.

Good catch @kdenhartog. It's possible to access it programatically by calling `solana.signMessage.toString()`. @Brandon-T we may need to overwrite it the same way you did for scripts with message handlers.

2022-11-29 16:23 UTC, Brandon-T commented
> > I think I've found a way to discover the value of the object via the console (note the `W5...` is the value of `UserScriptManager.walletSolanaNameSpace`), but it doesn't seem programatically accessible from my testing.
> 
> Good catch @kdenhartog. It's possible to access it programatically by calling `solana.signMessage.toString()`. @Brandon-T we may need to overwrite it the same way you did for scripts with message handlers.

Fixed and pushed. It was a regression but I made the code much more robust and detection of what should be overridden is much better :)
Also I made the namespace inaccessible in stack-traces, so if an exception happens during injection or even as a result of a function call, the namespace name will not be in the stack-trace.

2022-11-30 00:40 UTC, kdenhartog commented
> > I think I've found a way to discover the value of the object via the console (note the `W5...` is the value of `UserScriptManager.walletSolanaNameSpace`), but it doesn't seem programatically accessible from my testing.
> 
> Good catch @kdenhartog. It's possible to access it programatically by calling `solana.signMessage.toString()`. @Brandon-T we may need to overwrite it the same way you did for scripts with message handlers.

Nice job finding a way to get it programatically accessible, I'm glad I posted it here then. Seems like @Brandon-T fix for it should address it.

Something else odd I found was that window.solana.publicKey._bn.* has quite a few math functions underneath it that were usable, but I couldn't do anything malicious with it. For example, window.solana.publicKey._bn.nmul(0) sets the publicKey to 0.

From a cryptography perspective that shouldn't have any affect since this is the public key and the EdDSA functions are designed so that they shouldn't be exploitable with malicious public keys. I do want to play around with it a bit more though because it may be possible to use this to bypass permissions for using keys or something like that. @thypon curious if you or @stoletheminerals can come up with a way to abuse this. To me, this just seems like a side effect of web3.js making their publicKey object extend a BN.js object and would actually be a vulnerability of their library if this is possible to abuse.

2022-11-30 17:14 UTC, stoletheminerals commented on Client/Frontend/Browser/UserScriptManager.swift
> +      console.log(\(UserScriptManager.walletSolanaNameSpace));
@Brandon-T can you remove it then? 🙂

2022-11-30 17:30 UTC, stoletheminerals approved these changes
Just one minor logging issue. `SolanaWeb3` looks secure now. Though some `solana` properties are overwritable, I believe we don't want to freeze them for the same reason we don't freeze `ethereum` object.
Looks good, amazing job @Brandon-T

2022-12-01 10:14 UTC, thypon approved these changes

2022-12-01 15:20 UTC, Brandon-T commented on Client/Frontend/Browser/UserScriptManager.swift
> +      console.log(\(UserScriptManager.walletSolanaNameSpace));
Removed.

2022-12-01 16:22 UTC, merged