Fix #6320: Fix issue with long wait before downloading files
brave/brave-ios pull request #6321
Opened 2022-11-03 20:48 UTC by cuba

## Summary of Changes

Do an initial download instead of waiting on `ResourceDownloaderStream`

This pull request fixes #6320 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

On ticket

## Screenshots:

N/A

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2022-11-03 20:49 UTC, cuba commented on Client/WebFilters/AdBlockEngineManager.swift
>              resultString = "not compiled"
This file is just an output cleanup for debugging purposes. No real change here otherwise

2022-11-03 20:49 UTC, cuba commented on Client/WebFilters/ContentBlocker/ContentBlockerHelper.swift
>      #endif
This file is just an output cleanup for debugging purposes. No real change here otherwise

2022-11-03 20:49 UTC, cuba commented on Client/WebFilters/ContentBlocker/ContentBlockerManager.swift
> +    Self.log.debug("Compiled \(resources.count, privacy: .public) additional block list resources: \(resourcesString, privacy: .public))")
This file is just an output cleanup for debugging purposes. No real change here otherwise

2022-11-03 20:49 UTC, cuba commented on Client/WebFilters/ResourceDownloaderStream.swift
> +
This is the actual fix

2022-11-03 20:50 UTC, cuba commented on Client/WebFilters/ResourceDownloaderStream.swift
> +  private var firstLoad = true
Made this a struct in order to conform to Sendable

2022-11-03 20:52 UTC, cuba commented on Client/WebFilters/AdBlockEngineManager.swift
> +      log.debug("Loaded \(self.enabledResources.count, privacy: .public) (total) engine resources: \(resourcesString, privacy: .public)")
This is just an output cleanup for debugging purposes. No real change here otherwise

2022-11-03 22:36 UTC, iccub approved these changes

2022-11-04 16:16 UTC, iccub requested changes
`testSequenceWithErrorDownload` test does not pass after the changes

2022-11-04 23:01 UTC, iccub approved these changes

2022-11-04 23:01 UTC, merged