Fix #2123 - #1048: Allow ‘Reopen Last Closed Tab’ Shortcut (iPadOS) - Add Shake to Reopen in the Tab screen
brave/brave-ios pull request #6838
Opened 2023-01-25 22:40 UTC by soner-yuksel

## Summary of Changes

This pull request fixes #2123
This pull request fixes #1048

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

Reopen Last Closed Tab Shortcut:

- Hold cmd and chose Close All Tabs shortcut or Press cmd+shift+t
- A new tab should be opened with last recently closed tab

This will work both in browser controller and Tab Tray

Shake to Reopen:

- Shake while on Tab Tray
- A dialog should appear to warn if user wants to reopen the last closed tab (latest recently closed
- Open should open a latest closed tab in a new tab

## Screenshots:

Reopen Last Closed Tab Shortcut:

https://user-images.githubusercontent.com/6643505/213610478-d0297bdc-95e5-4d59-8531-53c4e6263cb8.mov

Shake to Reopen:

https://user-images.githubusercontent.com/6643505/213610514-db2f83ca-681f-49ab-9606-3778dc800ff2.MP4

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2023-01-30 15:52 UTC, iccub requested changes

2023-01-30 15:52 UTC, iccub commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+KeyCommands.swift
> +    braveTalkJitsiCoordinator.toggleMute()
Kyle removed JitsiSDK from prod builds and it does not throw any compile error in debug mode so be careful.
Now we have to add `#if canImport(BraveTalk)` statements to each of the JitsiSDK calls.
See this pull request for more details https://github.com/brave/brave-ios/pull/6843

2023-01-30 15:52 UTC, iccub commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+KeyCommands.swift
> +    guard let recentlyClosed = RecentlyClosed.all().first else {
Any private mode considerations here?

2023-01-30 15:52 UTC, iccub commented on Client/Frontend/Browser/Tabs/TabTray/TabTrayController+KeyCommands.swift
> +    guard let recentlyClosed = RecentlyClosed.all().first else {
same q about the private mode

2023-01-30 15:52 UTC, iccub commented on Client/Frontend/Browser/Tabs/TabTray/TabTrayController.swift
> +            RecentlyClosed.remove(with: recentlyClosedTab.url)
same q about private mode

2023-01-30 20:16 UTC, soner-yuksel commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+KeyCommands.swift
> +    braveTalkJitsiCoordinator.toggleMute()
Thanks for the warning.
Change at https://github.com/brave/brave-ios/pull/6838/commits/d03b63c0ac2329e95aff8e96b2bd856566b535c3

2023-01-30 20:44 UTC, soner-yuksel commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+KeyCommands.swift
> +    guard let recentlyClosed = RecentlyClosed.all().first else {
You are totally right here, we are not adding private browsing elements to recently closed however the command actions should not work here also. Good catch :tada Fix at https://github.com/brave/brave-ios/pull/6838/commits/a89cbeb80c398da2fd40bf9905d5dd0703d221a5

2023-01-30 20:44 UTC, soner-yuksel commented on Client/Frontend/Browser/Tabs/TabTray/TabTrayController+KeyCommands.swift
> +    guard let recentlyClosed = RecentlyClosed.all().first else {
Fix at https://github.com/brave/brave-ios/pull/6838/commits/a89cbeb80c398da2fd40bf9905d5dd0703d221a5

2023-01-30 20:44 UTC, soner-yuksel commented on Client/Frontend/Browser/Tabs/TabTray/TabTrayController.swift
> +            RecentlyClosed.remove(with: recentlyClosedTab.url)
Fix at https://github.com/brave/brave-ios/pull/6838/commits/a89cbeb80c398da2fd40bf9905d5dd0703d221a5

2023-01-31 14:43 UTC, iccub approved these changes
nice :)

2023-01-31 15:37 UTC, merged