Fix #6917 - Fix Favicons showing transparent & caching
brave/brave-ios pull request #6950
Opened 2023-02-15 18:04 UTC by Brandon-T

## Summary of Changes
- Fix Favicons showing transparent
- Fix defaulting to monogram and to globe icon on failure 
- Fix padding of monogram icons
- Fix padding on transparent favicons
- Remove caching of bundled icons otherwise NTP never shows the fetched icons. 
- Fix icon transparency for blurred backgrounds

This pull request fixes #6917

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
1. On NTP, tap on `Show More` to show the Brave Support Icon
2. It should show the support icon!

1. On NTP, tap on `Show More`.
2. Tap on Reddit.
3. Show the Tab Switcher
4. Favicon should show!
5. Close the tab.
6. On NTP, tap on `Show More`.
7. Reddit icon should be updated!
8. Repeat steps for Youtube and Amazon.

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2023-02-15 20:06 UTC, StephenHeaps approved these changes

2023-02-16 12:37 UTC, iccub requested changes

2023-02-16 12:37 UTC, iccub commented on Sources/Favicon/UIImage+FaviconRenderer.swift
> +        let ratio = 64.0 / min(idealSize.width, idealSize.height)
guard against division by zero maybe

2023-02-16 15:29 UTC, iccub approved these changes

2023-02-16 16:01 UTC, merged