[WIP] Fix #7172: Update App Review lLogic
brave/brave-ios pull request #7201
Opened 2023-04-04 16:30 UTC by soner-yuksel

## Summary of Changes

This pull request fixes #7172

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2023-04-07 18:13 UTC, iccub requested changes
Add comments to all enum cases for 3 app-review types, rest looks very good to me :)

2023-04-07 18:13 UTC, iccub commented on Sources/Growth/AppReviewManager.swift
> +    case revisedCrossPlatform
Can you add comments for each case explaining them? Hard to tell difference between `revised` and `revisedCrossPlatform`

2023-04-07 18:13 UTC, iccub commented on Tests/GrowthTests/AppReviewManagerLegacyTests.swift
> +// Copyright 2022 The Brave Authors. All rights reserved.
2023

2023-04-11 14:52 UTC, soner-yuksel commented on Sources/Growth/AppReviewManager.swift
> +    case revisedCrossPlatform
Added comments at https://github.com/brave/brave-ios/pull/7201/commits/ee1cd20a0ad4a5bb121231ae3c5a9db53624b614

2023-04-11 14:52 UTC, soner-yuksel commented on Tests/GrowthTests/AppReviewManagerLegacyTests.swift
> +// Copyright 2022 The Brave Authors. All rights reserved.
Fixed at https://github.com/brave/brave-ios/pull/7201/commits/ee1cd20a0ad4a5bb121231ae3c5a9db53624b614

2023-04-11 14:54 UTC, iccub approved these changes
Thank you

2023-04-11 17:14 UTC, merged