Fix Brave Ads initialization
brave/brave-ios pull request #7318
Opened 2023-04-21 22:16 UTC by tmancey

## Summary of Changes

This pull request fixes https://github.com/brave/brave-core/pull/18199

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2023-04-24 16:10 UTC, kylehickinson requested changes
Ads initialization also happens when Brave News is enabled (see FeedDataSource.swift)

2023-04-24 16:10 UTC, kylehickinson commented on Sources/Brave/Frontend/Rewards/BraveRewards.swift
> +      self.ads.initialize() { success in
Its possible this flow fails if `GetRewardsWallet` on the ledger side returns a `nullptr` for the wallet, therefore we have to change this flow a bit. If wallet is nil what is the flow? Do we initialize ads anyways? If not, then `isAdsInitialized` should be flipped back at the `guard let wallet = wallet else { return }` part

2023-04-26 12:38 UTC, tmancey commented on Sources/Brave/Frontend/Rewards/BraveRewards.swift
> +      self.ads.initialize() { success in
Fixed as we should only set the wallet before calling `initialize` if the wallet is valid, otherwise we just initialize for Brave News

2023-04-26 14:27 UTC, kylehickinson requested changes
Still haven't fixed news initialization in https://github.com/brave/brave-ios/blob/a6907cc0f521115f357be9564f71f5068231daaf/Sources/BraveNews/Customize/NewsSettingsView.swift#L274

2023-04-27 09:56 UTC, tmancey commented
> Ads initialization also happens when Brave News is enabled (see FeedDataSource.swift)

Discussed with @kylehickinson on a DM and no changes are required in FeedDataSource.swift because ads should be initialized without a wallet if only Brave News is enabled and Ads are not enabled

2023-04-27 15:20 UTC, kylehickinson commented
Waiting for relevant changes to be uplifted in core

2023-04-28 15:26 UTC, kylehickinson commented on Sources/Brave/Frontend/Rewards/BraveRewards.swift
> +          self?.isAdsInitialized = false
This does not compile: 

```
❌  /Users/runner/work/brave-ios/brave-ios/Sources/Brave/Frontend/Rewards/BraveRewards.swift:91:15: cannot use optional chaining on non-optional value of type 'BraveRewards'

          self?.isAdsInitialized = false
       ^```

2023-05-01 07:58 UTC, tmancey commented on Sources/Brave/Frontend/Rewards/BraveRewards.swift
> +          self?.isAdsInitialized = false
Fixed

2023-05-03 14:27 UTC, kylehickinson approved these changes

2023-05-03 14:28 UTC, merged