Fix #7233: Wallet Tx Activity Supports multiple networks
brave/brave-ios pull request #7441
Opened 2023-05-11 14:57 UTC by nuo-xu

## Summary of Changes
Currently, all the screens that display transaction information is restricted by the default network from the current user selected account's coin type. Core now removes this restriction, so front-end is now able to fetch tx for all networks.

This pull request fixes #7233 #7385

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:

1. Open Brave browser and login to Brave Wallet
2. make some transaction using the same coin type but in different networks. (For example: Using a solana account to make some tx on Solana Mainnet and Solana Devnet. Using a eth account to make some tx on Eth mainnet and Goerli)
3. Confirm or reject those tx
4. Go to Activity tab
5. Observe that all non-rejected for all accounts in all networks will be displayed 
6. Go to each account screen 
7. Observe that all tx made by this account in all networks will be displayed 
8. Go to activity history from the wallet panel 
9. Observe that all tx made by this account in all networks will be displayed 
10. Click the global BSS button and choose a different network.
11. Repeat from step 4
12. Step 5, 7 and 9 should also be expected. 

## Screenshots:

https://github.com/brave/brave-ios/assets/1187676/7c750d9c-f8fa-44b4-a835-14ebbb13aff4

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2023-05-11 15:13 UTC, StephenHeaps requested changes

2023-05-11 15:13 UTC, StephenHeaps commented on Tests/BraveWalletTests/AccountActivityStoreTests.swift
Can we update to include transactions from 2 different Ethereum networks in `testUpdateEthereumAccount()` and update `testUpdateSolanaAccount()` to include transactions from 2 different Solana networks?

2023-05-11 15:13 UTC, StephenHeaps commented on Tests/BraveWalletTests/TransactionsActivityStoreTests.swift
Can we update the existing `testUpdate()` test to include transactions from 2 different Ethereum networks and 2 different Solana networks? And another test that tests against the network filter with a specific network applied?

2023-05-12 04:02 UTC, nuo-xu commented on Tests/BraveWalletTests/AccountActivityStoreTests.swift
updated in [36061f7](https://github.com/brave/brave-ios/pull/7441/commits/36061f7c44ae8e31113db61535f01fd5573b82de)

2023-05-12 04:02 UTC, nuo-xu commented on Tests/BraveWalletTests/TransactionsActivityStoreTests.swift
updated in [36061f7](https://github.com/brave/brave-ios/pull/7441/commits/36061f7c44ae8e31113db61535f01fd5573b82de)

2023-05-12 15:21 UTC, StephenHeaps commented on Sources/BraveWallet/Preview Content/MockContent.swift
> +          chainId: BraveWallet.GoerliChainId,
This should be `BraveWallet.MainnetChainId` because that is what is set on the transaction: https://github.com/brave/brave-ios/blob/36061f7c44ae8e31113db61535f01fd5573b82de/Sources/BraveWallet/Preview%20Content/MockContent.swift#L213

Can we fix all these values while we are here as we had discussed?
Each of the Ethereum transactions has 2 `chainId` properties (one at root, at one in the `txDataUnion`)
`previewConfirmedSend`, `previewConfirmedSwap`, `previewConfirmedERC20Approve`

2023-05-12 15:21 UTC, StephenHeaps commented on Tests/BraveWalletTests/TransactionsActivityStoreTests.swift
Something about this test is causing flakey results. Failed on CI and local, but some re-runs pass.

2023-05-12 19:57 UTC, nuo-xu commented on Tests/BraveWalletTests/TransactionsActivityStoreTests.swift
fixed in [0317c77](https://github.com/brave/brave-ios/pull/7441/commits/0317c77b3272075b1805baac2699f45b5ef48c2f)

2023-05-12 20:18 UTC, StephenHeaps approved these changes

2023-05-12 20:18 UTC, StephenHeaps commented on Sources/BraveWallet/Extensions/SolanaTxManagerProxyExtensions.swift
> +  ) async -> [String: UInt64] {
Is this needed? Can't we use the existing function above, or remove the function above and use this instead?

2023-05-15 15:38 UTC, merged