Fix #7435: Fix typo in localization key (HistortMenuItem -> HistoryMe…
brave/brave-ios pull request #7444
Opened 2023-05-11 21:14 UTC by jlerner

…nuItem)

## Summary of Changes

This pull request fixes #<number>

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2023-05-11 22:15 UTC, iccub requested changes

2023-05-11 22:15 UTC, iccub commented on App/BraveWidgets/WidgetStrings.swift
> +    public static let historyMenuItem = NSLocalizedString("widgets.HistoryMenuItem", bundle: widgetBundle, value: "History", comment: "Title for history menu item")
Only this line has to be changed. All the other .strings files are generated automatically by our scripts

2023-05-17 17:00 UTC, soner-yuksel commented
Hi @jlerner, closing the PR for now. Please feel free to make another PR with the fix mentioned in comment https://github.com/brave/brave-ios/pull/7444#discussion_r1191741824. Thanks for contribution

2023-05-17 17:00 UTC, closed without merging

2023-06-02 16:30 UTC, adityarajpt commented
@iccub @soner-yuksel can you please point me to the script you mentioned that will be handling the generation

2023-06-02 17:01 UTC, soner-yuksel commented
@adityarajpt like @iccub said

Kus change there, thats all you need to do.

https://github.com/brave/brave-ios/pull/7444#discussion_r1191741824

2023-06-02 17:18 UTC, adityarajpt commented
@soner-yuksel open a PR: https://github.com/brave/brave-ios/pull/7559

I wanted to explore how we are generating .strings files, that's why I was asking about the script