Fixed bug #673 by making cell textLabel's number of lines as 0
brave/brave-ios pull request #745
Opened 2019-01-16 18:22 UTC by danishjafri88

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [ ] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New files have MPL-2.0 license header.

## Test Plan:

### Screenshots:

## Reviewer Checklist:

- [ ] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [ ] Issues are assigned to at least one epic.
- [ ] Issues include necessary QA labels:
  - [ ] `QA/(Yes|No)`
  - [ ] `release-notes/(include|exclude)`
  - [ ] `bug` / `enhancement`
- [ ] Necessary security reviews have taken place.
- [ ] Adequate test coverage exists to prevent regressions.
- [ ] Adaquate test plan exists for QA to validate (if applicable)

2019-01-16 18:28 UTC, kylehickinson requested changes

2019-01-16 18:28 UTC, kylehickinson commented on Client/Frontend/Settings/SettingsViewController.swift
> +class MultilineButtonCell: ButtonCell {
These classes should all be `private`

2019-01-16 22:26 UTC, danishjafri88 commented on Client/Frontend/Settings/SettingsViewController.swift
> +class MultilineButtonCell: ButtonCell {
Made them fileprivate Thanks!

2019-01-16 23:36 UTC, kylehickinson approved these changes

2019-01-18 19:21 UTC, jhreis approved these changes

2019-01-18 19:21 UTC, jhreis requested changes
@danishjafri88 can you fix the merge conflicts on this?

2019-01-21 21:42 UTC, danishjafri88 commented
@jhreis  merge conflicts resolved

2019-01-22 20:28 UTC, jhreis approved these changes

2019-01-22 20:29 UTC, merged