Ref #3939: Add support to Apple Screen Time Limits
brave/brave-ios pull request #7639
Opened 2023-06-25 15:44 UTC by domcorvasce

## Summary of Changes

This pull request fixes #3939. It adds support for:

<details>
  <summary>tracking web pages usage</summary>
  <img src="https://github.com/brave/brave-ios/assets/61356846/4c07b189-607f-421d-bc80-cab7bf09ae39" width="512">
</details> 

<details>
  <summary>setting usage limits per single web page</summary>
  <img src="https://github.com/brave/brave-ios/assets/61356846/4d035da6-1d7f-4013-9b1f-ea154c18f6aa" width="256">
</details> 

The Screen Time API is not well documented. I benefitted from reading https://github.com/mozilla-mobile/firefox-ios/pull/15111.

There is no way to test this feature using the Simulator. You need a real device.

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

1. Build the app on your real device
3. Go to Settings > Screen Time > turn it on if you didn't already
4. Go to Settings > Screen Time > App limits > Add Limit and add a one minute limit on a website of your choice
5. Open the app and visit the website you set the limit on. Browse it for one minute

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2023-06-26 13:56 UTC, iccub commented
Code looks legit, thanks @domcorvasce.
This PR will stay open for a bit, we have to test it well then make a security review for it

2023-06-26 14:09 UTC, soner-yuksel commented on Sources/Brave/Frontend/Browser/BrowserViewController.swift
> +    view.addSubview(screenTimeViewContainer.view)
Can we use snapkit for the sake of unity?

```
stackView.snp.makeConstraints {
  screenTimeViewContainer.view.edges.equalToSuperview()
}
```

2023-07-05 14:07 UTC, iccub requested changes
There's one change required.
Currently this implementation screen limit covers entire screen because it's added to the BrowserViewController.
We have to add it somewhere at the webview constraints level so the user can change to another tab.
It would also have to be one `STWebpageController` per tab.
I will try to update this code, find a good place for it

2023-07-06 13:24 UTC, domcorvasce commented
> Currently this implementation screen limit covers entire screen because it's added to the BrowserViewController.
> We have to add it somewhere at the webview constraints level so the user can change to another tab.

I went for Safari behaviour but I double-checked and it indeed the view controller is attached to the specific tab
I'll give it a try on the weekend ⚡

2023-07-07 19:14 UTC, domcorvasce commented
@iccub I moved the logic into `Tab` and I've checked that tabs switch is possible. It now follows Safari's behaviour (check top PR description for the up-to-date screenshot).

One quick note about [Tab.swift:180](https://github.com/brave/brave-ios/pull/7639/files#diff-e1de1b26b97c278da85da2f7ed234633875e7038d34c41306b48cbdb2d82329fR180): even though we suppress usage recording, assuming the user already maxed out the available time we need to set the active URL to `null` when within a private tab so the ST view is not shown.

2023-07-11 19:22 UTC, iccub requested changes
The placement is good now, I am able to switch tabs.

I noticed one bug that bypasses the screen limit though.

STR:
1. Open new tab
2. Enter url of the website you passed the limit on
3. It will show screen limit screen correctly 
4. Now press back arrow to take you to NTP, then forward back to the website

Result is the website does not show the limit screen anymore, you can refresh and navigate within that tab without any limits

Don't feel pressured to fix that if you don't want to, we can try to find the cause of the problem too

2023-07-11 19:28 UTC, iccub commented
I also noticed the screen limit is ignored in private mode. Safari does not do that. It is a product decision however, we have to decide on that behavior.
Should be fine since all screen time data is saved locally only

2023-07-11 21:02 UTC, domcorvasce commented
> I also noticed the screen limit is ignored in private mode. Safari does not do that. It is a product decision however, we have to decide on that behavior.
> Should be fine since all screen time data is saved locally only

I see. They’re attaching the ST controller to block websites that hit the usage limit in non private tabs but they don’t actively track page usage in private tabs (try browsing a website in private mode and it won’t show up in your Screen Time breakdown)

2023-07-14 18:13 UTC, aherrera31 commented
Question -- would this update also replicate Safari's behavior of syncing time spent on individual websites with ScreenTime, as opposed to aggregating and simply showing cumulative time spent on "Brave Browser"?

Thanks for building this! Have been waiting for this feature for a loooooong time! You all rock!

2023-07-14 18:16 UTC, domcorvasce commented
> Question -- would this update also replicate Safari's behavior of syncing time spent on individual websites with ScreenTime, as opposed to aggregating and simply showing cumulative time spent on "Brave Browser"?
> 
> Thanks for building this! Have been waiting for this feature for a loooooong time! You all rock!

Yep. For instance:

![](https://user-images.githubusercontent.com/61356846/248568291-4c07b189-607f-421d-bc80-cab7bf09ae39.jpeg)

2023-07-14 18:25 UTC, aherrera31 commented
> > Would this update also replicate Safari's behavior of syncing time spent on individual websites with ScreenTime, as opposed to aggregating and simply showing cumulative time spent on "Brave Browser"?
> 
> Yep

Grazie mille!

2023-08-03 16:01 UTC, iccub commented
small update on this one. i ran this branch for a while and i've been getting multiple random crash related to screen time. we are investigating the probme

2023-08-07 03:42 UTC, link1day commented
I have Brave browser freshly downloaded for iOS. Screentime /time limit websites  is not working.  Is there a solution on this page, can someone explain further? Do I need to just download something from here to add to that browser?

2023-08-18 16:25 UTC, bgala commented
Can this support extent to private browsing mode?

2023-08-18 16:32 UTC, iccub commented
@bgala the time limits I hope yes.
Recording web usage no.

We will try to match what Safari does

2023-08-29 11:34 UTC, iccub commented
There's been couple bigger problems and I made a new one here https://github.com/brave/brave-ios/pull/7983

2023-08-29 11:34 UTC, closed without merging