Fix #739: Supporting favorites without http/https prefix
brave/brave-ios pull request #768
Opened 2019-01-20 10:22 UTC by JonKaleidoscope

**Fix** https://github.com/brave/brave-ios/issues/739

## Submitter Checklist:

- [x] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [x] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New files have MPL-2.0 license header.

## Test Plan:

### Screenshots:

## Reviewer Checklist:

- [x] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [x] Issues are assigned to at least one epic.
- [x] Issues include necessary QA labels:
  - [x] `QA/(Yes|No)`
  - [x] `release-notes/(include|exclude)`
  - [x] `bug` / `enhancement`
- [x] Necessary security reviews have taken place.
- [x] Adequate test coverage exists to prevent regressions.
- [x] Adaquate test plan exists for QA to validate (if applicable)

## Other Comments

This change enables the _Favorites_ to accept pretty much any string not just URL's. The _Favorites_ UI allowed for easier changes but modifying the _Bookmarks_ to accept values that are not URL's is little more involved. In the nature of keeping PR's small, I think those changes would be better served in another PR.

The `BookmarksViewController` uses `URLRow` which requires the value to be an actual `URL`. [See details here](https://github.com/brave/brave-ios/blob/12df4aac9219cc6795866eab9de16f8696d5e45f/Client/Frontend/Menu/BookmarksViewController.swift#L95)

2019-01-30 23:04 UTC, jhreis commented
Hey, @JonKaleidoscope just wanted to let you know. I will get to your PR on Friday. It is really solid looking, just want to run some manual tests on it, but extremely thorough. Truly appreciate it. We haven't forgotten about it 😄 we've just been pretty swamped.

2019-01-31 01:26 UTC, JonKaleidoscope commented
No worries @jhreis , just glad to know I was not forgotten. I am happy to help out where I can. Feel free to direct me to any other area where you think I can help out.

2019-02-06 20:38 UTC, jhreis requested changes
Really slick, super great PR, just a few super small comments, and a merge conflict, will merge after that. Greatly appreciate this! 😄

2019-02-06 20:38 UTC, jhreis commented on Client/Frontend/Browser/HomePanel/FavoritesViewController.swift
> +    init(profile: Profile, dataSource: FavoritesDataSource = FavoritesDataSource()) {
Love the use of composition here, nice architectural improvement.

2019-02-06 20:38 UTC, jhreis commented on Client/Frontend/Browser/HomePanel/FavoritesViewController.swift
> +    internal let dataSource: FavoritesDataSource
Any reason this can't stay `private`?

2019-02-06 20:38 UTC, jhreis commented on Client/Frontend/Browser/BrowserViewController.swift
> +    func didSelect(urlString: String) {
This isn't technically a `url` anymore, right? Maybe maybe something like `input` instead?

2019-02-06 23:39 UTC, JonKaleidoscope commented on Client/Frontend/Browser/HomePanel/FavoritesViewController.swift
> +    internal let dataSource: FavoritesDataSource
I think in the midst of trying to write some unit I exposed this variable. I was able to get around this my injecting the `dataSource` during initilaization. I will return in back to private.

2019-02-07 21:42 UTC, jhreis commented on Client/Frontend/Browser/HomePanel/FavoritesViewController.swift
> +    internal let dataSource: FavoritesDataSource
👍 also, in a test file if you use `@testable` to import a module, it ignores scope, so private functions/properties are accessible, but composition works here too.

2019-02-07 21:43 UTC, jhreis commented
Just a merge conflict left, I will get around to fixing this later if you don't have time to get around to it. Will merge once that's done. Really nice PR, thanks!

2019-02-07 23:05 UTC, JonKaleidoscope commented on Client/Frontend/Browser/HomePanel/FavoritesViewController.swift
> +    internal let dataSource: FavoritesDataSource
I wish the `@testable` modifier worked like this but unfortunately it does not. It only exposes properties/types/functions that are `internal`.

**When you write an app with a unit test target, the code in your app needs to be made available to that module in order to be tested. By default, only entities marked as open or public are accessible to other modules. However, a unit test target can access any internal entity, if you mark the import declaration for a product module with the `@testable` attribute and compile that product module with testing enabled.**
  [Swift Docs - Access Control](https://docs.swift.org/swift-book/LanguageGuide/AccessControl.html#)

Other Reading: 
https://cocoacasts.com/how-to-unit-test-private-methods-in-swift/

2019-02-08 00:40 UTC, JonKaleidoscope commented
Apologies on the merge commit. I thought I brought the commit forward. It should be good now.

2019-02-12 21:35 UTC, jhreis approved these changes
This is great, really appreciate it!

2019-02-12 21:36 UTC, merged