Fix #76: Updated Brave README.
brave/brave-ios pull request #77
Opened 2018-07-03 13:09 UTC by jhreis

2018-07-03 13:26 UTC, iccub requested changes

2018-07-03 13:26 UTC, iccub commented on README.md
> +This branch currently supports iOS 10 and 11, and is written in Swift 4.
We don't support iOS 10.

2018-07-03 13:26 UTC, iccub commented on README.md
> +Firefox for iOS
🦁for iOS

2018-07-03 13:26 UTC, iccub commented on README.md
> +For bug fixes and features for the upcoming release, please see the associated milestone branch (e.g. *v2.1.3*).
We don't to that atm. We could tell them to check milestone label, not branch.

2018-07-03 13:26 UTC, iccub commented on README.md
>  We encourage you to participate in this open source project. We love Pull Requests, Bug Reports, ideas, (security) code reviews or any kind of positive contribution. Please read the [Community Partic
Replace with `community.brave`, remove Mozilla's link

2018-07-03 13:26 UTC, iccub commented on README.md
>      sh ./bootstrap.sh
Add code signing how-to, where to locate `.xconfig` file, how to set it up, and when it's needed(testing on a device only).

2018-07-03 13:26 UTC, tmancey reviewed
Looking great, please see my feedback

2018-07-03 13:26 UTC, tmancey commented on README.md
> +* All pull requests must be associated with a specific Github issue.
Github should be GitHub

2018-07-03 13:26 UTC, tmancey commented on README.md
> -This branch only works with Xcode 9.3 and supports iOS 10, and 11.
Was it intentional to leave out the Xcode version?

2018-07-03 13:30 UTC, iccub commented on README.md
>  * <code>git rebase --whitespace=fix</code> can also be used to remove whitespace from your commits before issuing a pull request.
I don't think we want that too, we want to keep whitespace, right?

2018-07-03 14:12 UTC, kylehickinson commented on README.md
>    * Exception: we use 4-space indentation instead of 2.
Are we switching to 2 or keeping 4? If we're keeping it at 4 I'm going to add 4-space requirements to top level folders in #61

2018-07-03 14:12 UTC, kylehickinson commented on README.md
>  * <code>git rebase --whitespace=fix</code> can also be used to remove whitespace from your commits before issuing a pull request.
The first option only trims whitespace at the end of lines and the second trims empty lines so I think this is correct

2018-07-03 14:16 UTC, iccub commented on README.md
>  * <code>git rebase --whitespace=fix</code> can also be used to remove whitespace from your commits before issuing a pull request.
I was referring to `git rebase --whitespace=fix`, does that remove whitespaces from empty lines?

2018-07-03 15:03 UTC, kylehickinson commented on README.md
>  * <code>git rebase --whitespace=fix</code> can also be used to remove whitespace from your commits before issuing a pull request.
Ah, sorry my eyes just went to green lines when commenting. Yes you are correct `whitespace=fix` will default to trailing whitespace **and** whitespace-only lines therefore if we want users to deselect the second option in Xcode, then yeah we don't want this.

2018-07-03 15:11 UTC, jhreis commented on README.md
> +For bug fixes and features for the upcoming release, please see the associated milestone branch (e.g. *v2.1.3*).
Good catch.

2018-07-03 15:12 UTC, jhreis commented on README.md
>  We encourage you to participate in this open source project. We love Pull Requests, Bug Reports, ideas, (security) code reviews or any kind of positive contribution. Please read the [Community Partic
Do you know where our guidelines are located?

2018-07-03 15:13 UTC, jhreis commented on README.md
> -This branch only works with Xcode 9.3 and supports iOS 10, and 11.
Yeah, a pain to keep updated manually. Once we use scripts to update this, I think it will be easier to keep updated. Thoughts?

2018-07-03 15:14 UTC, jhreis commented on README.md
>    * Exception: we use 4-space indentation instead of 2.
For now, I think we should keep 4, at least until we release and are stabilized. Main thing here is that pulling in changes from other sources will be much more annoying if we change our indentation level.

2018-07-03 15:19 UTC, jhreis commented on README.md
>  * <code>git rebase --whitespace=fix</code> can also be used to remove whitespace from your commits before issuing a pull request.
Thoughts on this in general? I generally don't like clearing out empty lines, I also find FF is pretty inconsistent with this, most of their files don't seem to follow this.

2018-07-03 20:18 UTC, srirambv requested changes

2018-07-03 20:18 UTC, srirambv commented on README.md
> +* Bugs:           [File a new bug](https://github.com/brave/brave-ios/issues/new) • [Existing bugs](https://github.com/brave/brave-ios/issues)
Existing bug should go in next line

2018-07-04 16:43 UTC, tmancey commented on README.md
> -This branch only works with Xcode 9.3 and supports iOS 10, and 11.
Sounds good to me 👍

2018-07-05 11:19 UTC, jhreis commented on README.md
> +* Bugs:           [File a new bug](https://github.com/brave/brave-ios/issues/new) • [Existing bugs](https://github.com/brave/brave-ios/issues)
They are just hyper links, so it ends up looking like:
> Bugs: [File a new bug] • [Existing bugs]

Both under the "Bugs" title. I think it mostly just looks confusing here with the huge hyperlinks in literal text, although they do not show up in the formatted README.

2018-07-05 11:49 UTC, iccub approved these changes
All looks good to me now.

2018-07-05 11:49 UTC, iccub commented on README.md
> +The easiest known way to find your team ID is to log into your [Apple Developer](https://developer.apple.com) account. After logging in, the team ID is currently shown at the end of the URL:
Great addition to code signing instructions, nice work.

2018-07-11 14:50 UTC, srirambv approved these changes

2018-07-11 15:24 UTC, merged