Issue 666: Prevent address bar spoofing using data: URLs
brave/brave-ios pull request #773
Opened 2019-01-22 05:13 UTC by jumde

fix https://github.com/brave/brave-ios/issues/666

`data:` urls are not supported on major mobile browsers. On Brave iOS data URLs
are not parsed correctly. 

Try opening `data:text/html;base64,SGVsbG8gV29ybGQhCg==` in Desktop vs Mobile Browser

This PR removes support for data URLs in new tabs.

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [ ] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New files have MPL-2.0 license header.

## Test Plan:

1.  Navigate to http://dustiest-limitation.000webhostapp.com/data.html
2. Click on Google.com - data URL should not open

## Reviewer Checklist:

- [ ] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [ ] Issues are assigned to at least one epic.
- [ ] Issues include necessary QA labels:
  - [ ] `QA/(Yes|No)`
  - [ ] `release-notes/(include|exclude)`
  - [ ] `bug` / `enhancement`
- [ ] Necessary security reviews have taken place.
- [ ] Adequate test coverage exists to prevent regressions.
- [ ] Adaquate test plan exists for QA to validate (if applicable)

2019-01-22 07:17 UTC, jumde commented
cc: @tomlowenthal

2019-01-22 14:49 UTC, iccub commented
What more needs to be done in this pr @jumde?

Also I would rename the commit to say something like `disable support for data scheme`, it is a generic change that fixes the security issue as well.

2019-01-22 17:02 UTC, jumde commented
@iccub - I'm checking out the test suite to see if any test can be added for this change. 

Updated the commit message, thank you

2019-01-22 22:18 UTC, iccub commented
`testSuggestClient` broke it seems

2019-01-22 22:40 UTC, iccub commented
Tests work on my local machine, I will rerun Travis

2019-01-22 22:56 UTC, iccub approved these changes
Looks good to me and the commit message is great, thanks.

Approving and waiting for @jhreis for final approval and merge

2019-02-06 20:45 UTC, jhreis requested changes
Just one small critique. Also we should update the `testschemeIsValid` unit test to include a `"data"` url inside `badurls`.

2019-02-06 20:45 UTC, jhreis commented on Shared/Extensions/URLExtensions.swift
> +private let permanentURISchemes = ["aaa", "aaas", "about", "acap", "acct", "cap", "cid", "coap", "coaps", "crid", "dav", "dict", "dns", "example", "file", "ftp", "geo", "go", "gopher", "h323", "http"
I'm not so sure that we should modify this list, as it is pulled from an external source. What about creating a list of exceptions underneath / above?

Something like:

```
private let permanentURISchemes = // ...
private let ignoredSchemes = ["data"]
private let supportedSchemes = permanentURISchemes.removeAll(where: ignoredSchemes.contains)
```

Then just update `schemeIsValid` to use `supportedSchemes`:

```
    public var schemeIsValid: Bool {
        guard let scheme = scheme else { return false }
        return supportedSchemes.contains(scheme.lowercased())
    }
```

2019-02-07 18:29 UTC, jhreis commented on Shared/Extensions/URLExtensions.swift
> +private let supportedSchemes = permanentURISchemes.filter { !ignoredSchemes.contains($0) }
Made a mistake previously with the `removeAll`, however the inverse of `filter` is `drop`, and will probably look a bit cleaner:

```suggestion
private let supportedSchemes = permanentURISchemes.drop(where: ignoredSchemes.contains)
```

2019-02-12 20:19 UTC, jhreis commented on Shared/Extensions/URLExtensions.swift
> +private let supportedSchemes = permanentURISchemes.filter { !ignoredSchemes.contains($0) }
This is wrong too. 😄

2019-02-12 20:19 UTC, jhreis approved these changes

2019-02-12 20:20 UTC, merged