Add Release Notes for iOS Release 1.51.2
brave/brave-ios pull request #7781
Opened 2023-07-25 20:37 UTC by Uni-verse

## Summary of Changes

This pull request fixes #7684 

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:

N/A

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2023-07-25 23:58 UTC, kjozwiak requested changes
LGTM other than few nits re: formatting/capitalization.

2023-07-25 23:58 UTC, kjozwiak commented on CHANGELOG.md
> +- Fixed ads event reporting for sponsored images on new tab page. ([#7566](https://github.com/brave/brave-ios/issues/7566))
nit re: formatting: Should be a space between the release version and the release notes. We also usually capitalize New Tab Page.

2023-07-26 10:27 UTC, iccub approved these changes

2023-07-26 16:28 UTC, kjozwiak approved these changes

2023-07-26 16:28 UTC, kjozwiak commented on CHANGELOG.md
nit: there's an extra here. Can fix that now or in the next release note. Other than that, LGTM 👍

2023-07-27 18:34 UTC, merged