Updated text for restore tabs page
brave/brave-ios pull request #7834
Opened 2023-08-05 12:49 UTC by adityagi02

## Summary of Changes
We need to match other apps in iOS, which states `App quit unexpectedly.`, attached screenshot for reference. All other text is same as stated in issue.

This pull request fixes #7695

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:

## Screenshots:

<img width="540" alt="61074599-80a28c80-a431-11e9-8e64-b5092b1ad879" src="https://github.com/brave/brave-ios/assets/77538183/83c4c1a3-96ef-429e-bf3b-562efb860d22">

![safaricrashes](https://github.com/brave/brave-ios/assets/77538183/1fdf93be-7daf-4f90-b329-ed4f6303ac6b)

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2023-08-07 14:54 UTC, iccub approved these changes

2023-08-07 14:56 UTC, iccub requested changes
Looks good. Can you update the button to say `Yes` instead of `Okay`?
It's this one `restoreTabAffirmativeButtonTitle`

2023-08-07 15:24 UTC, adityagi02 commented
Sure!

2023-08-07 16:01 UTC, iccub requested changes

2023-08-07 16:01 UTC, iccub commented on Sources/BraveStrings/Resources/de.lproj/BraveShared.strings
> +"RestoreTabAffirmativeButtonTitle" = "Ja";
Contents in .strings files are generated automatically. You can remove it. only the change to `BraveStrings` files is what we need.
Sorry if I was not clear enough

2023-08-07 16:20 UTC, adityagi02 commented on Sources/BraveStrings/Resources/de.lproj/BraveShared.strings
> +"RestoreTabAffirmativeButtonTitle" = "Ja";
np, i did the required changes.

2023-08-07 16:21 UTC, iccub requested changes

2023-08-07 16:21 UTC, iccub commented on Sources/BraveStrings/Resources/zh.lproj/BraveShared.strings
> +"RestoreTabAffirmativeButtonTitle" = "是的";
3 more languages .strings files left to remove. Rest looks great

2023-08-07 16:35 UTC, adityagi02 commented on Sources/BraveStrings/Resources/zh.lproj/BraveShared.strings
> +"RestoreTabAffirmativeButtonTitle" = "是的";
Thanks for pointing out, i think i made commit faster than xcode even counted it:)

2023-08-07 16:44 UTC, iccub approved these changes
thank you :)

2023-08-08 15:14 UTC, adityagi02 commented
When will this pr merge😅

2023-08-08 15:27 UTC, iccub commented
now!

2023-08-08 15:28 UTC, merged