Fix #7886: Add 1.57 translations.
brave/brave-ios pull request #7914
Opened 2023-08-22 15:00 UTC by iccub

## Summary of Changes

This pull request fixes #7886 

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [x] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [x] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [x] Adequate unit test coverage exists to prevent regressions.
- [x] Adequate test plan exists for QA to validate (if applicable).
- [x] Issue and pull request is assigned to a milestone (should happen at merge time).

2023-08-22 15:56 UTC, nuo-xu requested changes

2023-08-22 15:56 UTC, nuo-xu commented on Sources/BraveWallet/Resources/zh.lproj/BraveWallet.strings
> +"wallet.copiedToPasteboard" = "已複製";
```suggestion
"wallet.copiedToPasteboard" = "已复制";
```

2023-08-22 15:56 UTC, nuo-xu commented on Sources/BraveWallet/Resources/zh.lproj/BraveWallet.strings
> +"wallet.newPasswordPlaceholder" = "輸入新密碼";
```suggestion
"wallet.newPasswordPlaceholder" = "输入新密码";
```

2023-08-22 15:56 UTC, nuo-xu commented on Sources/BraveWallet/Resources/zh.lproj/BraveWallet.strings
> +"wallet.passwordPlaceholder" = "請輸入密碼";
```suggestion
"wallet.passwordPlaceholder" = "请输入密码";
```

2023-08-22 15:56 UTC, nuo-xu commented on Sources/BraveWallet/Resources/zh.lproj/BraveWallet.strings
> +"wallet.repeatedPasswordPlaceholder" = "重新輸入密碼";
```suggestion
"wallet.repeatedPasswordPlaceholder" = "重新输入密码";
```

2023-08-22 17:16 UTC, soner-yuksel commented on Sources/BraveStrings/Resources/tr.lproj/BraveShared.strings
> +"login.syncSetPasscodeAlertDescription" = "Senkronizasyon zincirine bir cihaz eklemek veya şifre senkronizasyonunu açmak veya kapatmak için, önce cihazınıza bir parola belirlemeniz gerekmektedir.";
"Senkronizasyon zincirine bir cihaz eklemek veya şifre senkronizasyonunu açmak veya kapatmak için, önce cihazınıza bir pin kodu belirlemeniz gerekmektedir."

2023-08-22 17:16 UTC, soner-yuksel commented on Sources/BraveStrings/Resources/tr.lproj/BraveShared.strings
> +"privacy.tab.tray.passcode.alert" = "Özel gezinme moduna geçmek için, önce cihazınıza bir parola belirlemeniz gerekmektedir.";
"Özel gezinme moduna geçmek için, önce cihazınıza bir pin kodu belirlemeniz gerekmektedir.";

2023-08-22 17:43 UTC, soner-yuksel approved these changes

2023-08-23 13:40 UTC, nuo-xu approved these changes

2023-08-23 13:54 UTC, merged