Fix #79: Port TabMO to tab manager.
brave/brave-ios pull request #80
Opened 2018-07-06 09:39 UTC by iccub

Modified `TabMO`:
- added `screenshotUUID`, v2 uses different mechanism for restoring screenshots
- removed `isClosed`, `isPrivate`, these are not used anymore

The main goal of this PR was to replace saving tab data to sqlite to our core data `TabMO` model. I left most of v2 `TabManager` logic and added v1 code parts only when needed.

I would say functionality wise it's 90% complete now. Tab saving/restoring works, private tabs are never saved to TabMO, new tab has 'New tab' title. 
One not implemented thing is restoring favicons, I will do that in a separate PR.

There is one bug, when restoring tabs, the home panel is shown for a split second. I will fix it after my topsites/homepanel migratoin from v1 is approved and merged.

2018-07-06 20:58 UTC, kylehickinson submitted a review, later dismissed
Looks good, just some minor nit picks.

Also general question: How deep is SwiftyJSON used? Do you think it's realistic to remove it and switch to Swift's built-in `Codable`?

2018-07-06 20:58 UTC, kylehickinson commented on Data/models/TabMO.swift
> +public typealias SavedTab = (id: String, title: String, url: String, isSelected: Bool, order: Int16, screenshot: UIImage?, history: [String], historyIndex: Int16)
I feel like this is way too long for a tuple, is there a reason this isn't a `struct`?

2018-07-06 20:58 UTC, kylehickinson commented on Client/Frontend/Browser/Tab.swift
> +        // Pulls restored session data from a previous SavedTab to load into the Browser. If it's nil, a session restore
Nit pick (probably from copy-paste): `Browser` back to `Tab`

2018-07-06 20:58 UTC, kylehickinson commented on Client/Frontend/Browser/TabManager.swift
> +            for i in 0..<self.tabs.count {
Can be condensed: `for (i, tab) in self.tabs.enumerated()`

2018-07-06 20:58 UTC, kylehickinson commented on Client/Frontend/Browser/TabManager.swift
> +        if urlString.contains("localhost") { return nil }
Can probably be added in the guard to only have 1 `return nil`

2018-07-06 20:58 UTC, kylehickinson commented on Shared/Extensions/StringExtensions.swift
> +    }
Nit-pick: Spacing

2018-07-06 20:58 UTC, kylehickinson commented on Client/Frontend/Browser/TabManager.swift
> +                // tab.restore(webView, restorationData: data)
Can be removed since its called right below

2018-07-10 09:59 UTC, tmancey commented on Client/Frontend/Browser/Tab.swift
> +            var prev = ""
nit: abbreviations should only be used if widely used in the English language according to Apple documentation, prev should ideally be previous

2018-07-10 09:59 UTC, tmancey commented on Client/Frontend/Browser/Tab.swift
> +                let curr = updatedURL.regexReplacePattern("https?:..", with: "")
nit: curr should ideally be current

2018-07-10 09:59 UTC, tmancey commented on Client/Frontend/Browser/Tab.swift
> +            jsonDict["currentPage"] = Int(currentPage) as AnyObject
Stringly typed code is error-prone to misspellings and If we do make a spelling error, the compiler won't be able to help us catch those bugs. Should we not be moving these to constants?

2018-07-10 09:59 UTC, tmancey commented on Client/Frontend/Browser/Tab.swift
> +            // lastRequest?.addValue(WebServer.uniqueBytes, forHTTPHeaderField: WebServer.headerAuthKey)
nit: Commented out code should be removed or if further changes are required in a future commit TODO: should be added

2018-07-10 09:59 UTC, tmancey commented on Client/Frontend/Browser/Tab.swift
> +        return url.baseDomain == "localhost" && url.absoluteString.contains("about/home/#panel=0")
Stringly typed code is error-prone to misspellings and If we do make a spelling error, the compiler won't be able to help us catch those bugs. Should we not be moving these to constants?

2018-07-10 09:59 UTC, tmancey commented on Data/models/DataController.swift
>              print("No context on save")
nit: Good time to change print to log.debug?

2018-07-10 09:59 UTC, tmancey commented on Data/models/TabMO.swift
> +    @discardableResult
nit: for consistency @discardableResult should be on same line as func

2018-07-10 09:59 UTC, tmancey commented on Client/Application/DebugSettingsBundleOptions.swift
> +        return attachLogsToDebugEmail &&  MFMailComposeViewController.canSendMail()
nit: spacing after &&

2018-07-10 09:59 UTC, tmancey commented on Client/Frontend/Browser/Tab.swift
> +            return title.range(of: "localhost") == nil ? title : ""
Stringly typed code is error-prone to misspellings and If we do make a spelling error, the compiler won't be able to help us catch those bugs. Should we not be moving these to constants?

2018-07-10 09:59 UTC, tmancey commented on Data/models/TabMO.swift
>          // BRAVE TODO: uncomment
nit: No commented out code?

2018-07-10 09:59 UTC, tmancey commented on Data/models/TabMO.swift
> +        if let s = tabData.screenshot {
nit: abbreviations should only be used if widely used in the English language according to Apple documentation, s should ideally be screenshot

2018-07-10 13:18 UTC, iccub commented on Client/Frontend/Browser/Tab.swift
> +            return title.range(of: "localhost") == nil ? title : ""
I think words like `localhost`, `http`, `https` are simple enough to not needing to extract them to constants. This is what the current FF convention is at least.
FF doesn't use too many string constants in such cases, do you think it's worth doing even for simple strings?

2018-07-11 13:48 UTC, jhreis commented
@kylehickinson Yes, certainly worth considering switching to codable, although for now I think we should avoid. Would be an independent migration I think. At least when it comes to moving code from current project over. If anyone wants to use it on new pieces that is totally grand.

2018-07-11 15:34 UTC, jhreis commented on Client/Frontend/Browser/Tab.swift
> +            return title.range(of: "localhost") == nil ? title : ""
Why not just use `contains`?

`return title.contains("localhost") ? title : ""`

2018-07-11 15:45 UTC, jhreis requested changes

2018-07-11 15:45 UTC, jhreis commented on Client/Frontend/Browser/TabManager.swift
> +            // tab.sessionData = savedTab.sessionData
Any reason this is commented out? If so, just remove it.

2018-07-11 15:45 UTC, jhreis commented on Client/Frontend/Browser/TabManager.swift
> +            // FIXME: only selected tab has webView attached
Use `TODO` easier to find.

2018-07-11 15:45 UTC, jhreis commented on Client/Frontend/Browser/TabManager.swift
> +            let data = SavedTab(id: tabUUID, title: savedTab.title ?? "", url: url, isSelected: savedTab.isSelected, order: savedTab.order, screenshot: nil, history: history, historyIndex: savedTab.u
Isn't `title` here an optional? Do we need to fall back to empty string here?

2018-07-11 15:45 UTC, jhreis commented on Data/models/TabMO.swift
> +    public class func get(by id: String?, context: NSManagedObjectContext) -> TabMO? {
Not sure `by: String` is clear enough, I think `byId` is probably more clear. Does look funny, could switch it to something like `fromId` or `byID`.

2018-07-11 15:45 UTC, jhreis commented on Data/models/TabMO.swift
> +        fetchRequest.predicate = NSPredicate(format: "\(#keyPath(TabMO.syncUUID)) == %@", id)
Really interesting. Had to look up the new `#keyPath` usage here. Nice improvement.

2018-07-12 01:14 UTC, jhreis approved these changes

2018-07-12 01:14 UTC, jhreis commented on Client/Frontend/Browser/Tab.swift
> +private let log = Logger.browserLogger
I think we should make this global thing honestly. Basically like `print`

2018-07-12 12:33 UTC, tmancey commented on Client/Frontend/Browser/SessionData.swift
> +    struct Keys {
"history" and "currentPage" in ```Browser.swift``` should be changed to use these keys for ```SessionData```

2018-07-12 12:33 UTC, tmancey commented on Client/Frontend/Browser/Tab.swift
> +private let log = Logger.browserLogger
👍

2018-07-12 12:33 UTC, tmancey commented on Storage/DiskImageStore.swift
> +    @discardableResult open func clearExcluding(_ keys: Set<String>) -> Success {
Added ```@discardableResult``` however the function ```clearExcluding``` is not called from this PR

2018-07-12 12:33 UTC, tmancey commented on Data/models/TabMO.swift
> -        fetchRequest.predicate = NSPredicate(format: "isPrivate == true")
Why has `isPrivate` been removed or is the tab inherently private?

2018-07-12 12:33 UTC, tmancey commented on Shared/Extensions/StringExtensions.swift
> +    public func regexReplacePattern(_ pattern:String, with:String) -> String {
nit: spacing

2018-07-12 12:33 UTC, tmancey commented on Shared/Extensions/StringExtensions.swift
> +        let regex = try! NSRegularExpression(pattern:pattern, options: [])
nit: spacing

2018-07-12 12:33 UTC, tmancey commented on Data/models/TabMO.swift
> -//        tab.isPrivate = PrivateBrowsing.singleton.isOn
Why has isPrivate been removed or is the tab inherently private?

2018-07-12 12:33 UTC, tmancey commented on Client/Frontend/Browser/SessionData.swift
> +        let urlStrings = urls.map { $0.absoluteString }
Urls should be retrieved from the "urls" key in the following dictionary which is implemented in this class on line 14

```
var jsonDictionary: [String: Any] {
    return [
        "currentPage": String(self.currentPage),
        "lastUsedTime": String(self.lastUsedTime),
        "urls": urls.map { $0.absoluteString }
    ]
}
```

2018-07-12 12:40 UTC, jhreis commented on Data/models/TabMO.swift
> -        fetchRequest.predicate = NSPredicate(format: "isPrivate == true")
`isPrivate` is in current code because private tabs are stored, we do not store them (except in memory), so no need to have this flag. `isPrivate` is more of an application state than a tab flat.

2018-07-12 13:03 UTC, iccub commented on Client/Frontend/Browser/Tab.swift
> +private let log = Logger.browserLogger
We do it that way in all other files, ff uses the same convention too. If we want to change it we should do it in a separate PR.

2018-07-12 16:26 UTC, tmancey commented on Data/models/TabMO.swift
> -//        tab.isPrivate = PrivateBrowsing.singleton.isOn
Joel commented in another comment "isPrivate is in current code because private tabs are stored, we do not store them (except in memory), so no need to have this flag. isPrivate is more of an application state than a tab flat."

2018-07-12 16:26 UTC, tmancey commented on Data/models/TabMO.swift
> -//        tab.isPrivate = PrivateBrowsing.singleton.isOn
👍

2018-07-12 16:37 UTC, tmancey approved these changes

2018-07-12 16:38 UTC, tmancey approved these changes

2018-07-12 18:20 UTC, jhreis commented on Client/Frontend/Browser/SessionData.swift
> +    struct Keys {
https://github.com/brave/brave-ios/pull/80/commits/b50d7e599b1dd7a5ff8ad228abf236e63a91c72b

2018-07-12 18:21 UTC, merged