Add Release Notes for iOS Release 1.57
brave/brave-ios pull request #8428
Opened 2023-11-16 18:25 UTC by Uni-verse

## Summary of Changes

This pull request fixes [#8029](https://github.com/brave/brave-ios/issues/8029)

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:

N/A

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2023-11-16 18:46 UTC, iccub approved these changes

2023-11-17 12:36 UTC, srirambv requested changes
Rest looks good

2023-11-17 12:36 UTC, srirambv commented on CHANGELOG.md
> +- Fixed crash when switching to Polygon Network in Brave Wallet “Swap” view. ([#7907](https://github.com/brave/brave-ios/issues/7907))
nit: Network -> network

2023-11-17 12:36 UTC, srirambv commented on CHANGELOG.md
> +- Added handling of empty state(s) for Brave Wallet Portfolio filters. ([#7618](https://github.com/brave/brave-ios/issues/7618))
nit: state(s) -> state. 

No multiple states available so no need to pluralize it

2023-11-17 12:36 UTC, srirambv commented on CHANGELOG.md
> +- Fixed URLs for i.redd.it posts on subreddits from forming incorrectly when using [old.reddit.com](http://old.reddit.com/) website redirect. ([#7873](https://github.com/brave/brave-ios/issues/7873))
nit:  add quotes for i.redd.it

2023-11-17 12:36 UTC, srirambv commented on CHANGELOG.md
> +- Fixed Recent Searches to update UI when using “clear” button. ([#4923](https://github.com/brave/brave-ios/issues/4923))
nit: quotes for "Recent Searches" to keep it consitent

2023-11-17 16:10 UTC, Uni-verse commented
> Rest looks good

Thanks @srirambv, changes are made.

2023-11-17 17:24 UTC, kjozwiak requested changes

2023-11-17 17:24 UTC, kjozwiak commented on CHANGELOG.md
> +- Updated logic for the Default Browser prompt on New Tab Page. ([#7860](https://github.com/brave/brave-ios/issues/7860))
nit: I don't think `Default Browser` needs to be capitalized in this instance. Can just be the following:

```
- Updated logic for the default browser prompt on New Tab Page. ([#7860](https://github.com/brave/brave-ios/issues/7860))
```

2023-11-17 17:24 UTC, kjozwiak commented on CHANGELOG.md
> +- Updated Sync Chain authentication logic to support Biometrics when enabling password sync or adding a new device. ([#7849](https://github.com/brave/brave-ios/issues/7849))
nit: Probably don't need to have `Biometrics` capitalized in this instance.

2023-11-17 17:24 UTC, kjozwiak commented on CHANGELOG.md
> +- Updated that VPN Support Contact Form to append the issue category to the email subject field as well as body. ([#7828](https://github.com/brave/brave-ios/issues/7828))
nit: remove `that` from the beginning. Don't think it's needed.

2023-11-17 17:24 UTC, kjozwiak commented on CHANGELOG.md
> +- Fixed issue with “Block Cookie Consent Notices” toggle switch being enabled when upgrading browser version. ([#7920](https://github.com/brave/brave-ios/issues/7920))
nit: probably don't need `version` at the end. It's obvious that the version will be different when updating. Can just use:

```
- Fixed issue with “Block Cookie Consent Notices” toggle switch being enabled when upgrading browser. ([#7920](https://github.com/brave/brave-ios/issues/7920))
```

2023-11-17 17:24 UTC, kjozwiak commented on CHANGELOG.md
> +- Fixed crash when migrating with very many tabs open. ([#7857](https://github.com/brave/brave-ios/issues/7857))
nit: doesn't really sound right with `very`. Did the migration happen during update? Maybe we can call that out for some context. Maybe something as follows:

```
- Fixed crash when migrating after update when browser has many tabs opened. ([#7857](https://github.com/brave/brave-ios/issues/7857))
```

2023-11-17 17:24 UTC, kjozwiak commented on CHANGELOG.md
> +- Fixed tabs to close properly with window.close(). ([#7796](https://github.com/brave/brave-ios/issues/7796))
Can probably remove this one from the notes. I don't most people will understand the above. Maybe we can change it to something as follows:

```
Fixed tabs not being closed correctly in certain cases.
```

2023-11-17 17:24 UTC, kjozwiak commented on CHANGELOG.md
> +- Fixed crash in tab view when tapping “Private” flag while actively dragging a tab. ([#7737](https://github.com/brave/brave-ios/issues/7737))
I don't have a lot of context but is `flag` the right word? Is it referring to the `Private` button?

2023-11-17 17:24 UTC, kjozwiak commented on CHANGELOG.md
> +- Fixed issue allowing users to bypass the Browser Lock window using the “Cancel” button. ([#7893](https://github.com/brave/brave-ios/issues/7893))
nit: Lets but `Browser Lock` in quotes --> `"Browser Lock"`

2023-11-17 18:03 UTC, Uni-verse commented on CHANGELOG.md
> +- Updated that VPN Support Contact Form to append the issue category to the email subject field as well as body. ([#7828](https://github.com/brave/brave-ios/issues/7828))
Good catch, thanks!

2023-11-17 18:06 UTC, Uni-verse commented on CHANGELOG.md
> +- Fixed tabs to close properly with window.close(). ([#7796](https://github.com/brave/brave-ios/issues/7796))
Will use your suggestion. Thanks.

2023-11-17 18:09 UTC, Uni-verse commented
@kjozwiak Thanks for reviewing. https://github.com/brave/brave-ios/commit/7ee8accb03510fa1d5927529186db5396846c905

2023-11-19 05:47 UTC, kjozwiak approved these changes
LGTM 👍

2023-11-20 06:43 UTC, srirambv approved these changes
++

2023-11-20 14:29 UTC, merged