Add Release Notes for iOS Release 1.58
brave/brave-ios pull request #8491
Opened 2023-11-27 21:14 UTC by Uni-verse

## Summary of Changes

This pull request fixes [#8487](https://github.com/brave/brave-ios/issues/8487)

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:

N/A

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2023-11-28 09:53 UTC, iccub approved these changes

2023-11-28 11:55 UTC, srirambv requested changes

2023-11-28 11:55 UTC, srirambv commented on CHANGELOG.md
> +- Added Coinbase Pay on-ramp for Brave Wallet buy flows. [(#7880](https://github.com/brave/brave-ios/issues/7880))
Maybe reword as  `Added Coinbase Pay as an On-ramp provider.`

2023-11-28 11:55 UTC, srirambv commented on CHANGELOG.md
> +- Added Stripe on-ramp for Brave Wallet buy flows. ([#7794](https://github.com/brave/brave-ios/issues/7794))
Maybe reword as  `Added Stripe as an On-ramp provider.`

2023-11-28 11:55 UTC, srirambv commented on CHANGELOG.md
> +- Added the ability for users to choose which Solana account to choose when connecting to Solana DApps. ([#7637](https://github.com/brave/brave-ios/issues/7637))
Maybe reword to `Added ability to choose Solana account when connecting to Solana DApp.`

2023-11-28 11:55 UTC, srirambv commented on CHANGELOG.md
> +- Updated default buy currency and removed field placeholder for Stripe on ramp flow. ([#7709](https://github.com/brave/brave-ios/issues/7709))
Maybe reword to `Removed placeholder value in "Buy" screen and updated default currency to USD`

Placeholder is removed for all on-ramp not just for Stripe so no need to mention the provider here.

2023-11-28 11:55 UTC, srirambv commented on CHANGELOG.md
> +- Refactored Selected Account in Brave Wallet. ([#7723](https://github.com/brave/brave-ios/issues/7723))
Marked it as exclude so can remove it

2023-11-28 11:55 UTC, srirambv commented on CHANGELOG.md
> +- Fixed backup flow to show as completed when initiated from “Accounts” tab. ([#8120](https://github.com/brave/brave-ios/issues/8120))
Change to `Fixed wallet backup flow  when initiated from "Accounts" tab`

2023-11-28 14:20 UTC, Uni-verse commented
Thanks for the review @srirambv 

https://github.com/brave/brave-ios/commit/76f2640abe4f90df655f77a481afa756a0b8b5c9

2023-11-29 21:51 UTC, kjozwiak requested changes

2023-11-29 21:51 UTC, kjozwiak commented on CHANGELOG.md
> +- Implemented “Copy clean URL” feature on iOS. ([#6179](https://github.com/brave/brave-ios/issues/6179))
Probably don't need to mention iOS as the CHANGELOG/Release notes are specifically for iOS in this case.

2023-11-29 21:51 UTC, kjozwiak commented on CHANGELOG.md
> +- Added “Suppress” button to “Allow link to switch apps?” pop-up as reported on HackerOne by amit5533.  [#7835](https://github.com/brave/brave-ios/issues/7835)
nit: extra space after the period (before issue link)

2023-11-29 21:51 UTC, kjozwiak commented on CHANGELOG.md
> +- Added support for Playlist on https://www.x.com. ([#7896](https://github.com/brave/brave-ios/issues/7896))
Maybe add this below the https://www.bitchute.com so both `Playlist` support issue are together?

2023-11-29 21:51 UTC, kjozwiak commented on CHANGELOG.md
> +- Added logic for device limitations when joining existing Sync chain. ([#7887](https://github.com/brave/brave-ios/issues/7887))
nit: Sync probably doesn't need to be capitalized in this instance unless using `Brave Sync`.

2023-11-29 21:51 UTC, kjozwiak commented on CHANGELOG.md
> +- Removed Zip Foundation dependency. ([#7901](https://github.com/brave/brave-ios/issues/7901))
Can probably remove this one TBH. I don't mind keeping it but don't think it will add much value to regular users.

2023-11-29 21:51 UTC, kjozwiak commented on CHANGELOG.md
> +- Removed a script on YouTube which caused ads to be shown. ([#8239](https://github.com/brave/brave-ios/issues/8239))
Rather than mentioning scripts being removed, can do something more general:

```
- Fixed ads being shown on YouTube in certain cases.
```

2023-11-29 21:51 UTC, kjozwiak commented on CHANGELOG.md
> +- Fixed app from crash when changing VPN regions after switching to IKEv2 protocol. ([#8235](https://github.com/brave/brave-ios/issues/8235))
Maybe something like this?

```
- Fixed crash when changing VPN regions after switching to IKEv2 protocol. ([#8235](https://github.com/brave/brave-ios/issues/8235))
```

2023-11-29 21:51 UTC, kjozwiak commented on CHANGELOG.md
> +- Fixed problem with the “Bookmarks” switch in Sync Settings being disabled when enabling other switches. ([#8148](https://github.com/brave/brave-ios/issues/8148))
nit: Sync probably doesn't need to be capitalized in this instance unless using `Brave Sync`. Lets add `"Settings"` in quotes as well.

2023-11-29 21:51 UTC, kjozwiak commented on CHANGELOG.md
> +- Added support for more regions for Brave News opt-in card. ([#7932](https://github.com/brave/brave-ios/issues/7932))
I think we can just say that we added Brave News support for those specific regions. For example:

```
- Added Brave News support for "Germany", "France", "India" & "Austria".
```

2023-12-01 10:25 UTC, srirambv approved these changes
++ for Web3

2023-12-01 15:05 UTC, Uni-verse commented
@kjozwiak  Appreciate the review.

2023-12-04 23:36 UTC, kjozwiak approved these changes
LGTM 👍 Awesome work.

2023-12-06 16:48 UTC, merged