Fix #8345, #8425: Add 'Creating Wallet...' step to onboarding
brave/brave-ios pull request #8509
Opened 2023-11-30 20:33 UTC by StephenHeaps

## Summary of Changes
- Wallet data files are now registered & downloaded when a wallet is created or restored for the first time (existing Wallet users are already registered). This means we'll have a longer asynchronous time between user tapping `Continue` on password step before the wallet is setup. To handle this case, a `Creating Wallet...` view is used.
Adds a down carat button to the Onboarding flow when `Creating Wallet...` is shown so user knows they can dismiss. Dismissal will not cancel wallet creation, it will continue in background (wallet data files fetched in background).

This pull request fixes #8345,
fixes #8425

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:
### Create Wallet flows
1. Start from fresh install (so wallet data files need to download)
2. Open Wallet onboarding and use create new wallet flow.
    - The `Creating Wallet...` step is after pressing `Continue` on Create a Password view. Onboarding should progress as normal.
3. Verify it continues with onboarding flow works as expected (`Creating Wallet` view could be missed on faster internet connection).
4. Delete Brave app & re-install.
5. Test create wallet flow from fresh install, but disable or use network link conditioner to severely slow network connection before tapping `Continue` on Create a Password view. 
6. Dismiss wallet via down-arrow button on `Creating Wallet...` view.
7. Re-open Wallet; Portfolio should be shown. You can re-enable regular network conditions and the wallet data files will download in the background. Some asset icons won't be visible until download completes (and icons moved off screen & back on). Should be an uncommon case.

### Restore Wallet flows
1. Start from fresh install (so wallet data files need to download)
2. Open Wallet onboarding and use restore wallet flow.
3. When entering seed phrase, type it invalid phrase like `1` for each word (each field must be populated).
4. Tap `Continue` and `Create a Password` modal is opened.
5. Verify passwords must match for continue button to be enabled.
6. Tap `Continue`. Verify `Create a Password` modal dismisses to show invalid seed phrase error.
7. Enter correct seed phrase and tap `Continue`.
8. Verify it continues with onboarding flow works as expected (`Creating Wallet` view could be missed on faster internet connection).
9. Delete Brave app & re-install.
10. Test restore wallet flow from fresh install again, but disable or use network link conditioner to severely slow network connection before tapping `Continue` on Create a Password view. 
11. Dismiss wallet via down-arrow button on `Creating Wallet...` view.
12. Re-open Wallet; Portfolio should be shown. You can re-enable regular network conditions and the wallet data files will download in the background. Some asset icons won't be visible until download completes (and icons moved off screen & back on). Should be an uncommon case.

### iPad Split Screen bug #8425
I was unable to reproduce this bug, but @srirambv got it a couple times. I've added additional protections for the case where a user has 2 Brave windows open both showing Wallet onboarding (and forced non-dismissal scenario in code to test). In the case where the 2nd window does _not_ automatically dismiss onboarding after the 1st window creates the wallet, tapping `Continue` will dismiss the onboarding flow instead of creating a second wallet / duplicate Ethereum & Solana accounts.

## Screenshots:

<video src="https://github.com/brave/brave-ios/assets/5314553/8acb7a5f-667e-45b2-8832-cf57f02ee954"> | <video src="https://github.com/brave/brave-ios/assets/5314553/27487502-9b5c-4082-861c-018e6e38ab5c">
--|--
<video src="https://github.com/brave/brave-ios/assets/5314553/2cee5fb9-ab90-4998-a3ce-b3d77949d153"> | <video src="https://github.com/brave/brave-ios/assets/5314553/754ce0d5-de30-45c6-98d2-f62ce57b2d5b">

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2023-12-04 15:49 UTC, nuo-xu commented
found two issues:
1. ~~backup banner will show in **Restore Wallet flows** after step 12 before i change the network to normal.~~ [[Existed issue](https://github.com/brave/brave-browser/issues/33750)]
2. ~~continue with the first issue. A crash will happen if i lock the wallet from portfolio.~~[Resolved]

2023-12-04 19:20 UTC, StephenHeaps commented
> found two issues:
> 
> 1. backup banner will show in **Restore Wallet flows** after step 12 before i change the network to normal.
> 2. continue with the first issue. A crash will happen if i lock the wallet from portfolio.

Discussed offline but the crash only occurs when using a debug build of BraveCore, I reported previously: https://github.com/brave/brave-browser/issues/33750. On release builds it will fail silently internally in core.

The issue with backup banner showing after restore (until network callback received) is resolved in [de5cd5c](https://github.com/brave/brave-ios/pull/8509/commits/de5cd5c221eb23439167d415058f0aa6650ab8c4).

2023-12-06 17:12 UTC, nuo-xu requested changes

2023-12-06 17:12 UTC, nuo-xu commented on Sources/BraveWallet/Crypto/Onboarding/RestoreWalletView.swift
> +    }
.overlay seems like not going to make content in fullscreen
![Simulator Screenshot - iPhone 15 Pro - 2023-12-06 at 11 18 15](https://github.com/brave/brave-ios/assets/1187676/94dcc4ae-de7e-4bca-a457-014ccfc3070b)

2023-12-06 17:58 UTC, StephenHeaps commented on Sources/BraveWallet/Crypto/Onboarding/RestoreWalletView.swift
> +    }
Nice catch, fixed in [a244b48](https://github.com/brave/brave-ios/pull/8509/commits/a244b488c75d6ea754d61208ac35001a76de410e) (needs dark mode to see background colour difference).

2023-12-06 19:23 UTC, nuo-xu approved these changes

2023-12-07 14:15 UTC, merged