Fix #8565: Re-enable Screen-Time.
brave/brave-ios pull request #8611
Opened 2024-01-03 17:59 UTC by Brandon-T

## Summary of Changes
- Enable Screen-Time again.
- Instead of setting the URL to about blank, remove the controller from the view.
- Fix the order of functions and call the correct functions when doing child controller logic.

This pull request fixes #8565

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2024-01-03 18:05 UTC, soner-yuksel approved these changes

2024-01-03 18:05 UTC, iccub approved these changes

2024-01-04 11:53 UTC, iccub requested changes
Few ways to bypass it:
1. https://github.com/brave/brave-ios/issues/8579
2. Open new tab and type the blocked url directly
3. Tab restoration

2024-01-04 18:51 UTC, iccub approved these changes
thank you very much
commits are not signed btw

2024-01-04 20:04 UTC, merged