Fix #8590: Wallet Swap Service Refactor also Bump Core to 1.63.90
brave/brave-ios pull request #8613
Opened 2024-01-03 22:19 UTC by nuo-xu

## Summary of Changes
Core bump to 1.63.90
Swap Store class refactor 

This pull request fixes #8590

## Submitter Checklist:

- [x] *Unit Tests* are updated to cover new or changed functionality
- [x] User-facing strings use `NSLocalizableString()`
- [x] New or updated UI has been tested across:
  - [x] Light & dark mode
  - [x] Different size classes (iPhone, landscape, iPad)
  - [x] Different dynamic type sizes

## Test Plan:

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2024-01-03 22:21 UTC, soner-yuksel commented
@nuo package-lock.json difference shouldn't no be necessary. Did you use npm `install` or npm `update` ?

2024-01-04 15:44 UTC, StephenHeaps approved these changes
2 minor nits

2024-01-04 15:44 UTC, StephenHeaps commented on Tests/BraveWalletTests/SwapTokenStoreTests.swift
> +        completion(nil, nil, "Test Internal Error")
We should use `XCTFail` here instead

2024-01-04 15:44 UTC, StephenHeaps commented on Tests/BraveWalletTests/SwapTokenStoreTests.swift
> +        completion(nil, nil, "Test Internal Error")
Similar here, use `XCTFail`

2024-01-04 16:04 UTC, StephenHeaps requested changes
I forgot the `package-lock.json` changes, we should resolve that before merge 🙂

2024-01-04 16:37 UTC, StephenHeaps approved these changes

2024-01-04 18:50 UTC, merged