Add Release Notes for iOS Release 1.61
brave/brave-ios pull request #8692
Opened 2024-01-23 21:44 UTC by Uni-verse

## Summary of Changes

This pull request fixes [#8578](https://github.com/brave/brave-ios/issues/8578)

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:

N/A

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2024-01-24 05:39 UTC, srirambv requested changes
++ for remaining web3 entries

2024-01-24 05:39 UTC, srirambv commented on CHANGELOG.md
> +- Updated UI and functionality for the NFT details page. ([#8064](https://github.com/brave/brave-ios/issues/8064))
nit: NFT -> "NFT" to keep consistency

2024-01-24 05:39 UTC, srirambv commented on CHANGELOG.md
> +- Implemented new UI for the “Activity” Tab in Brave Wallet. ([#8349](https://github.com/brave/brave-ios/issues/8349))
nit: Tab -> tab

2024-01-24 05:39 UTC, srirambv commented on CHANGELOG.md
> +- Updated UI and functionality for “NFT” Tab under “Portfolio.” ([#8063](https://github.com/brave/brave-ios/issues/8063))
nit: Tab -> tab

2024-01-24 05:39 UTC, srirambv commented on CHANGELOG.md
> +- Fixed pop-ups to be dismissed when Brave Wallet is auto-locked. ([#8412](https://github.com/brave/brave-ios/issues/8412))
change to 
> Fixed NFT auto-discover and remove modals to be dismissed when Brave wallet gets auto-locked

2024-01-24 17:13 UTC, iccub approved these changes

2024-01-24 20:48 UTC, Uni-verse commented
> ++ for remaining web3 entries

Thanks for reviewing, changes made - https://github.com/brave/brave-ios/commit/d1b4da168fee02b968b729d56703237cc49c0bff

2024-01-29 22:51 UTC, kjozwiak requested changes

2024-01-29 22:51 UTC, kjozwiak commented on CHANGELOG.md
> +- Added  “Redeem Code” button for custom offer codes in the VPN subscription page. ([#8365](https://github.com/brave/brave-ios/issues/8353))
nit: extra space between `Added` & `Redeem`. The GH issue and the displayed issue number don't match. Link using `8365` but pointing to https://github.com/brave/brave-ios/issues/8353.

2024-01-29 22:51 UTC, kjozwiak commented on CHANGELOG.md
> +- Fixed orientation lock for Brave sync screens. ([#6275](https://github.com/brave/brave-ios/issues/6275))
Should capitalize `sync` in this case as you're referring to `Brave Sync`.

2024-01-29 22:51 UTC, kjozwiak commented on CHANGELOG.md
> +- Fixed adding correct video to Playlist on https://twitter.com/. ([#8479](https://github.com/brave/brave-ios/issues/8479))
Can probably word this a bit better. Maybe something along the lines of the following?

```
- Fixed incorrect video being added to Playlist on https://twitter.com/. ([#8479](https://github.com/brave/brave-ios/issues/8479))
```

2024-01-29 22:51 UTC, kjozwiak commented on CHANGELOG.md
> +- Fixed bookmark count to include bookmarks in subfolders and enabled all URLs in subfolders to be opened as well when using “Open All” action. ([#8169](https://github.com/brave/brave-ios/issues/8169
I don't think we need `as well` in this case. The following probably sounds better:

```
- Fixed bookmark count to include bookmarks in subfolders and enabled all URLs in subfolders to be opened when using “Open All” action. ([#8169](https://github.com/brave/brave-ios/issues/8169))
```

2024-01-29 22:51 UTC, kjozwiak commented on CHANGELOG.md
> +- Fixed main menu items to all have the same font color. ([#8396](https://github.com/brave/brave-ios/issues/8396))
hmm I think we can probably word this one a bit better. Maybe something along the lines of the following:

```
- Fixed certain items under main menu using incorrect font color. ([#8396](https://github.com/brave/brave-ios/issues/8396))
```

2024-02-08 17:55 UTC, kjozwiak approved these changes
LGTM 👍

2024-02-13 06:25 UTC, srirambv requested changes
Rest all looks good

2024-02-13 06:25 UTC, srirambv commented on CHANGELOG.md
> +- Updated UI and functionality for the "NFT" details page. ([#8064](https://github.com/brave/brave-ios/issues/8064))
Maybe just have it as `- Updated NFT details to new layout `

2024-02-13 06:25 UTC, srirambv commented on CHANGELOG.md
> +- Updated UI and functionality for “NFT” tab under “Portfolio.” ([#8063](https://github.com/brave/brave-ios/issues/8063))
Maybe just have it as `- Updated NFT tab UI to new layout`

2024-02-13 06:25 UTC, srirambv commented on CHANGELOG.md
> +- Fixed NFT auto-discover and remove modals to be dismissed when Brave Wallet gets auto-locked. ([#8412](https://github.com/brave/brave-ios/issues/8412))
Change to `- Fixed NFT auto-discover popup not being dismissed when Brave Wallet gets auto-locked`

2024-02-14 17:54 UTC, srirambv approved these changes
++

2024-02-22 20:33 UTC, merged