Add Release Notes for iOS Release 1.61.1
brave/brave-ios pull request #8770
Opened 2024-02-22 20:48 UTC by Uni-verse

## Summary of Changes

This pull request fixes #[8625](https://github.com/brave/brave-ios/issues/8625)

## Submitter Checklist:

- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New or updated UI has been tested across:
  - [ ] Light & dark mode
  - [ ] Different size classes (iPhone, landscape, iPad)
  - [ ] Different dynamic type sizes

## Test Plan:

N/A

## Screenshots:

## Reviewer Checklist:

- [ ] Issues include necessary QA labels:
  - `QA/(Yes|No)`
  - `bug` / `enhancement`
- [ ] Necessary [security reviews](https://github.com/brave/security/issues/new/choose) have taken place.
- [ ] Adequate unit test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable).
- [ ] Issue and pull request is assigned to a milestone (should happen at merge time).

2024-02-22 20:49 UTC, Uni-verse commented
@iccub Could you please add tag for 1.61.1 whenever you get a chance, thanks!

2024-02-22 23:07 UTC, kjozwiak requested changes
Added a few nit/improvements that can be made.

2024-02-22 23:07 UTC, kjozwiak commented on CHANGELOG.md
> +- Fixed Ad notification click event not triggering on iOS. ([#8619](https://github.com/brave/brave-ios/issues/8619))
I don't think you need to mention `iOS` as these notes are all related to `iOS`. So probably can use:

```
- Fixed Brave Ad notification click event not being triggered. ([#8619](https://github.com/brave/brave-ios/issues/8619))
```

Added `Brave` in front of `ad` just so users don't get confused about that `ad` were talking about.

2024-02-23 14:10 UTC, iccub approved these changes

2024-02-26 17:29 UTC, kjozwiak approved these changes
LGTM 👍

2024-02-26 19:52 UTC, Uni-verse commented
> LGTM 👍

Appreciate the review!

2024-02-26 19:52 UTC, merged