Updated the checks to set shields.
brave/brave-ios pull request #945
Opened 2019-03-07 15:23 UTC by danishjafri88

Older checks used to fail in certain conditions. Updated to make sure it works.

## Submitter Checklist:

- [ ] Submitted a [ticket](https://github.com/brave/brave-ios/issues) for my issue if one did not already exist.
- [ ] My patch or PR title has a standard commit message that looks like `Fix #123: This fixes the shattered coffee cup!` (or `No Bug: <message>` if no relevant ticket)
- [ ] *Unit Tests* are updated to cover new or changed functionality
- [ ] User-facing strings use `NSLocalizableString()`
- [ ] New files have MPL-2.0 license header.

## Test Plan:

### Screenshots:

## Reviewer Checklist:

- [ ] PR is linked to an issue via [Zenhub](https://www.zenhub.com/extension).
- [ ] Issues are assigned to at least one epic.
- [ ] Issues include necessary QA labels:
  - [ ] `QA/(Yes|No)`
  - [ ] `release-notes/(include|exclude)`
  - [ ] `bug` / `enhancement`
- [ ] Necessary security reviews have taken place.
- [ ] Adequate test coverage exists to prevent regressions.
- [ ] Adequate test plan exists for QA to validate (if applicable)

2019-06-24 14:50 UTC, jhreis requested changes

2019-06-24 14:50 UTC, jhreis commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
> +            var frame: WKFrameInfo? = nil
Do not need to specify ` = nil`, remove.

2019-06-24 14:50 UTC, jhreis commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+WKNavigationDelegate.swift
> +            if frame?.securityOrigin.protocol == "" {
use `.isEmpty`

2019-07-15 15:24 UTC, iccub approved these changes

2019-08-08 19:27 UTC, jhreis approved these changes

2019-08-08 19:28 UTC, merged